meedan/check-api

app/controllers/application_controller.rb, config/initializers/rails_admin.rb, public/403.html, test/integration/admin_integration_test.rb
On denied access the user is redirect to a Forbidden page
When not authed the user is redirected to the login page
=> Ticket #5580: Handle denied access and not authed on AdminUI

app/models/project_media.rb, db/migrate/20170218133223_reindex_dynamic_annotations.rb
re-index es to add dynamic annotation mapping 
started from Caio's script https://github.com/meedan/check-api/blob/develop/db/migrate/20161107180246_reindex_annotations.rb and add small changes to store parent id
=> Ticket #5725

.codeclimate.yml, app/models/ability.rb, app/models/admin_ability.rb, app/models/user.rb, config/initializers/rails_admin.rb, lib/check_basic_abilities.rb, test/models/admin_ability_test.rb
The abilities used on Admin UI will not use context_team and check
permissions based on the teams that the logged in user is admin
=> Ticket #5755: Add AdminAbility to be used on Admin UI

config/initializers/rails_admin.rb, test/integration/admin_integration_test.rb
The fields that should not be displayed on creation had the options
`visible` and `hide`. Changed the order of lines because in those cases
the `hide` should override the `visible` cases and be the last one
Also fixed configuration of team `name` and `slug` that were as
`read_only` for admins on `new` page
=> Ticket #6610: Allow creation of teams on Admin UI

app/models/annotations/comment.rb, app/models/annotations/status.rb, app/models/concerns/team_duplication.rb, config/initializers/location_search.rb, config/initializers/paper_trail.rb
- skip `paper trail`s callbacks if it is being copied
- add default status on project media if the original status is invalid
- don't notify if copied status is terminal
- check if file `response_geolocation` exist before trying to get its value
- skip validation of comment text when being copied
- check if element is present on mapping before set it as `item` on PaperTrail::Version copy
=> Ticket #6599: Fix errors on team duplication

app/models/source.rb, app/models/user.rb, config/initializers/rails_admin.rb, lib/sample_data.rb, test/models/user_test.rb
Also:
- the image added on User registration will be set as source file
- the image on omniauth_info will be set as source avatar
=> Ticket #6831: Remove `profile_image` from User page

app/models/admin_ability.rb, test/models/admin_ability_test.rb
Team owners can manage only objects of their teams
=> Ticket #6897: Fix Admin UI permissions

app/mailers/admin_mailer.rb, app/models/team.rb, test/controllers/elastic_search_2_test.rb, test/mailers/admin_mailer_test.rb
The owners with emails notifications disabled don't receive a copy of download link
=> Ticket #7526: Send project export link only to owners with member status

.travis.yml, lib/tasks/export_team.rake
- Include data from users that created items on teams but are not members
- Sensitive data are replaced by default values
- Fix: avoid crash when query tables that are related to other tables and `get_ids(<other table>)` is empty
- Dump the database in batches to avoid problems with big tables
- Allow adding list of tables to not include on dump
=> Ticket #7550: Enhancements and fixes on team dump

app/graph/types/query_type.rb, app/models/concerns/project_media_creators.rb, app/models/link.rb, test/controllers/graphql_controller_3_test.rb
Only normalize it when the original is not found
=> Ticket #7696: Normalize the URL when receiving a GraphQL query

lib/tasks/data/pg_export.rb
This exports more dynamic_annotation_fields:
* those with field_name=smooch_user_data
* those with field_name=smooch_data that annotate Team, not ProjectMedia
These are crucial Workbench workflows.
=> export_team: export Project/Team annotations

lib/tasks/data/pg_export.rb
Previously, we weren't exporting annotations related to BotResources -- meaning swaths of conversations.
=> pg_export: export BotResources annotations

.travis.yml, Dockerfile, production/Dockerfile
Set UTF-8 capable locale. Avoid installing region specific locales to conserve storage.
=> Set locale to C.UTF-8 rather than en_US.UTF-8.

.gitlab-ci.yml
This change updates the GitLab-CI deploy process to also update the check-api-workbench scheduled task when updating the other check-api tasks.
In the future this will be handled by the Terraform project for check-api, but in interim, perform updates via GitLab as well.
=> Update the workbench copy scheduled task definition when updating check-api tasks

lib/tasks/data/push_all_configured_teams_to_workbench.rake, lib/tasks/data/push_team_to_workbench.rake, lib/tasks/data/workbench_upload.rb
Also, retry uploads on failure and skip uploads when the retries fail.
**TO DEPLOY**, be sure to change the CSV to match the new schema. Instead
of `workflow_id` and `step_id`, there is now just one column,
`workbench_step_url`. To migrate your CSV, apply a formula:
```workbench_step_url = "https://app.workbenchdata.com/api/v1/workflows/" + workflow_id + "/steps/" + step_id + "/files"```
For instance, now a valid CSV looks like:
```
team_slug,workbench_step_url,api_token
my-team-1,https://app.workbenchdata.com/api/v1/workflows/123456/steps/step-abcdef/files,SoMe-Tok3n
my-team-1,https://app.workbenchdata.com/api/v1/workflows/123456/steps/step-bcdefg/files,4n0th3r-70k_n
```
=> Upload to Workbench TUS URLs

.gitlab-ci.yml
This change uses the `--exclusive-secrets` option when deploying new task definitions via `ecs-deploy`. This allows us to remove deprecated SSM parameters from the parameter store without encountering hung deployments.
=> Use exclusive secrets option when deploying task updates

config/initializers/jsonapi_resources.rb
This appears on the top level of every query response in a `meta` object, per the JSONAPI spec.
=> Configuring JSONAPI to return record count

app/resources/api/v2/workspace_resource.rb, config/initializers/jsonapi_resources.rb
I am changing the default paginator to type `paged`, which works better with the material-ui pagination system, and changing `WorkspaceResource` to be unpaginated because I need the names of all available workspaces to do fast autocompletion and selection clientside.
=> Pagination changes to v2 endpoints

app/models/bot/alegre.rb, test/models/bot/alegre_test.rb
We recently changed the `threshold` variable throughout alegre to a dictionary rather than a float so we could pack more metadata about the provenance of the threshold into the variable (and could make more conditional decisions based on that metadata). When I did this, I did not update the conditions sent to the *image* similarity endpoint, nor did I test it in QA (as we were only updating text cases. We have many tests on image similarity, but none that confirm the data being sent to alegre. we now have a fix for the bug as well as test cases to cover this situation.
=> CHECK-607 resolve missing cases in tests, fix query sent to alegre on image similarity lookup

lib/tasks/data/pg_export.rb
The Workbench Check module is seeing long delays, and the `versions` table is a prime culprit.
By only SELECTing the data the Workbench module needs, a Workbench "Items" sqlite3 query of today's India Today database dropped from 34s to 13s on my dev machine. File size shrank 45%, too.
The downside: this new export format doesn't capture "all the data". If we ever want to extend the Workbench module's capabilities, we'll need to alter `pg_export`.
=> pg_export: nix most of the versions table

.gitlab-ci.yml
When watching the deploy earlier today, I noticed that the workbench copy task is deployed before the check-api task itself. Because the workbench copy task is a scheduled task, this should actually be done AFTER the check-api task itself is updated. I suspect this is behind the periodic workbench failures.
This change deploys the workbench copy task after the other check-api tasks are deployed, ensuring it will use the most recent revision for the scheduled task.
=> Deploy the workbench copy task updated after deploying the API task

app/models/annotations/task.rb, config/initializers/field_formatters.rb, config/initializers/field_searches.rb, config/initializers/field_validators.rb, config/locales/en.yml, db/migrate/20220124165559_create_url_task_type.rb, db/schema.rb
This creates a new annotation type called `"url"`. The data structure that it expects to store is an array of objects, each containing two strings, `"url"`, and `"title"`. The `title` is optional and may be an empty string. The `title` property should always be there, and if "empty" should be an empty string and never `null`.
```json
[
{ "url": "http://example.com", "title": "Example Web Site" },
{ "url": "https://meedan.com", "title": "Meedan" },
]
```
The formatted output (aka `Task.first_response_value`) is the JSON string of the object above.
Validation checks to see if if each `url` in each object in the array is a valid http or https url. If one or more urls is invalid, it returns an error and specifies each invalid url in the error message.
Tests coming in a future PR.
=> URL Annotation

app/models/annotations/task.rb, test/models/project_media_test.rb
When the response for a file upload task is a file URL, that file will be downloaded and saved, as if it was uploaded from the UI.
=> Ticket CHECK-1340: Support file uploads

config/initializers/honeycomb.rb
For the past two days we've hit burst protection limits on Honeycomb.
This change cuts the sample rate in half, which should work well for the near future.
=> Cut honeycomb sample rate by half since we are starting to hit burst protection limits.

app/models/bot/smooch.rb, app/models/concerns/smooch_menus.rb, app/models/concerns/smooch_messages.rb, app/models/concerns/smooch_search.rb, db/migrate/20220221205147_add_tipline_bot_v2_settings_to_smooch_bot.rb, db/schema.rb, test/models/bot/smooch_5_test.rb, test/models/bot/smooch_6_test.rb
* Search for URLs and their content (CHECK-1408)
* Fixing race condition when two search queries are submitted by the same user in a short interval (CHECK-1415)
* Do not ask for language confirmation all the time and don't timeout too often (CHECK-1405)
* Append "please confirm your language" localized in all supported languages (CHECK-1460)
* Evoke both vector model and ElasticSearch when looking for similar texts (CHECK-1419)
* New tipline search settings: similarity threshold and maximum number of words for keyword search (CHECK-1441)
* Updated copy for default messages in English (CHECK-1461)
=> Improvements and fixes for tipline bot v2

.gitlab-ci.yml, scripts/uptime-maintenance.py
This change invokes a script to pause the Uptime checks when check-api deploys a new revision. This will avoid false alarms during deployment.
=> Pause uptime checks

config/initializers/honeycomb.rb
We received another notice that we're exceeding limits. The increase in both Tipline and Check Web activity seems to be driving the increase. This cuts sample rate by half, which should bring us back under limits with additional spare capacity.
=> Cut honeycomb sample rate by half, as we are again exceeding limits.

config/initializers/honeycomb.rb
As noted, there is a daily quota derived from monthly limits. We've been exceeding the daily quota the last few days, and this will ensure we're below both the daily and monthly limits.
=> Cut honeycomb sample rate by half again, as we are now exceeding daily limits.

app/models/concerns/smooch_search.rb
I earlier committed code for this improvement already, but I think it is better to explicitly compare against the `Bot::Alegre::ELASTICSEARCH_MODEL` constant when ordering results. We don't have any vector model that alphabetically comes before "e", but we could in the future and that would break the previous fix without warning, which is bad. This PR fixes that.
=> CHECK-1537 - Prefer vector models to Elasticsearch results

app/graph/mutations/claim_description_mutations.rb, app/graph/types/claim_description_type.rb, app/models/claim_description.rb, db/migrate/20220317210706_add_context_to_claim_descriptions.rb, db/migrate/20220318160448_remove_null_constraint_from_claim_description.rb, db/schema.rb, lib/sample_data.rb, test/models/claim_description_test.rb
* add a new `context` field to `claim_description` of type `text`
* make `description` and `context` both optional fields in `claim_description`
* Tests, including removing a test that checked for `description` to not be empty
=> CHECK-1587: context field in claim_descriptions

app/controllers/api/v1/graphql_controller.rb
This categorizes an `ActiveRecords::RecordNotUnique` as an error of type `CONFLICT`, so that on the client it will ultimately be rendered as "There was a database conflict." or similar.
=> CHECK-1651: New error mapping

app/models/bot/smooch.rb, app/models/concerns/smooch_messages.rb
Sometimes videos have their type mapped to "file" instead of "video".
=> Ticket CHECK-1618: Get the correct file type for videos searched in tipline bot v2

config/initializers/honeycomb.rb
With usage increasing we're now hitting daily burst protection limits again. Cut sample rate by half to ensure we stay under threshold.
=> Cut honeycomb sample rate by half again, as we are exceeding daily burst protection limits.

app/models/concerns/project_media_getters.rb, app/models/concerns/smooch_search.rb, app/resources/api/v2/feed_resource.rb, db/schema.rb, public/api-docs.json, test/controllers/feeds_controller_test.rb, test/models/project_media_test.rb
Requested changes for the feeds resource were:
* Remove attributes report_title and report_summary
* Add attributes claim_context, claim_tags and fact_check_published_on
* Add an "after" (date) filter, exposed in Swagger UI as well
* Rename a few other attributes
References: CHECK-1748.
=> Some changes as per product review of the feeds API feature.

app/models/bot/smooch.rb
After "Read now" is clicked, the newsletter needs to be sent in the correct language.
So, the right workflow needs to be picked up.
Reference: CHECK-1759
=> Fix language in which newsletter is sent

app/models/bot/smooch.rb
Funny race condition. The reported bug: when a report is a visual card, the counter for sent reports was
not incrementing and the report received confirmation was not displayed on the request card. There was a
3 seconds delay between sending the visual card and the text report. That delay means that if the received
confirmation was received in less than 3 seconds, the information was not stored. Deleting the "sleep 3"
fixes the problem, and it's not needed anymore because now it's either a visual card or a text report... it's
not possible to have both anymore.
Fixes CHECK-1764.
=> Fixing report received confirmation for visual cards

config/initializers/02_sidekiq.rb, production/Dockerfile
Debugging issues with @danielevalverde and we tracked it down to the new Sidekiq CloudWatch Metrics collection trying to initialize when running Travis integration tests. In addition, builds may fail if the AWS ENV vars are not set when trying to install gem `aws-sdk-cloudwatch 1.62.0` as it checks for these variables.
=> Fix travis initialization

app/models/bot/fetch.rb, app/models/concerns/smooch_search.rb, app/models/fact_check.rb, app/workers/report_designer_worker.rb, config/initializers/report_designer.rb, db/schema.rb, test/data/oembed-verification_status.html, test/models/fact_check_test.rb, test/models/project_media_test.rb, test/test_helper.rb
Details:
* Text report now has a published article URL
* Report and fact-check are in sync: if one is changed, the other is changed too, and vice-versa (one exception: published article URL is not overwritten by a visual card)
* Tipline bot v2 search: one message per each of the up to 3 results... visual card or text report (title, summary and link)
Reference: CHECK-1697.
=> Fact-checks and reports should be in sync

app/models/fact_check.rb, app/models/team.rb, app/workers/tipline_newsletter_worker.rb, test/models/team_test.rb, test/workers/tipline_newsletter_worker_test.rb
**Include default introduction when creating a report from a fact-check** 
When a fact-check is set, a report is created, if there isn't one yet. This report should inherit the default introduction settings from the workspace.
**Adding more logging to tipline newsletter delivery**
Adding more log messages to tipline newsletter delivery, so we have more information when debugging why some user didn't receive the newsletter.
**"All items" count should include suggestions but not confirmed matches**
In order to really reflect the items that are displayed by default under the "All Items" list, the counter should include suggestions but not confirmed matches.
=> Fixes for items count, report and newsletter.

app/models/concerns/smooch_newsletter.rb, test/models/bot/smooch_5_test.rb
The API now accepts any string with an explicit offset in the format `(+|-)hh:mm`.
All time zones provided clientside are guaranteed to work via the API -- for example, even though Ruby doesn't support PHT, the string that comes in will say `Pacific/Phillippines (GMT+08:00)`, which simply gets converted to `+08:00` so `DateTime` doesn't have to know anything about the 3-letter codes. This means we can have fewer unit tests. I now test for positive and negative offsets, and kept the tests for non-integer offsets, and offsets where the day changes.
CHECK-1139
=> Update newsletter cron conversion

app/models/bot/smooch.rb, app/models/concerns/smooch_search.rb, test/models/bot/smooch_6_test.rb
Currently, after search results are delivered by the tipline bot, the bot waits for 7 seconds before asking for feedback from the user on whether the results are relevant. But sometimes (for example, when the search results are report visual cards or contain external links, both of which need to be parsed by WhatsApp) it can happen that the feedback message is delivered before the actual search results. So, any hard-coded interval we put is not reliable. This change implements a different approach for that, explained below:
* When each search result is delivered, save the sent message ID in a Redis list, where the key contains the user ID
* Start a Sidekiq job that verifies each second, up to 30 attempts, if that list is empty
* When the user receives a search result, we receive a …
=> Ask for feedback on tipline search results only after all results are received

app/models/concerns/smooch_newsletter.rb
Previously we had separate date and time fields with that information, but sometimes they are not in sync because of timezone issue. So, now return a single field with both date and time in the correct timezone.
Fixes CHECK-1883.
=> Fixing the information about when it's the next time a newsletter will be sent

app/models/bot/smooch.rb, app/models/concerns/smooch_messages.rb, app/workers/tipline_newsletter_worker.rb
Set the platform when sending newsletters and reports, otherwise text-based menus will be rendered instead of buttons.
CHECK-1892.
=> Fix menus on reports and newsletters sent to users on non-WhatsApp platforms

app/models/bot/smooch.rb, test/models/bot/smooch_4_test.rb
This is mostly for legacy reasons, since today it's not possible, on the frontend side, to create both text report and visual card for the same item. But for some existing data, some items have both a text report and a visual card. Let's be sure that only one is sent for those cases.
Fixes CHECK-1897.
=> Send either a text report or an image report.

lib/check_search.rb, test/controllers/elastic_search_8_test.rb
When search for items by keyword, enable fuzzy matching. Right now with a Levenshtein Edit Distance of 1. For now, this is enabled for all keyword searches, maybe that should be a search options. More on that:
* https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#fuzziness
* https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html
Reference: CHECK-1903.
=> Fuzzy matching for keyword search

app/models/bot/smooch.rb, app/models/concerns/smooch_messages.rb, app/models/concerns/smooch_search.rb, test/models/bot/smooch_6_test.rb
For the new data reports to be generated, we need to differentiate some types of tipline requests. So this commit adds two new tipline request types:
* "irrelevant_search_result_requests"
* "timeout_search_requests"
Reference: CHECK-1810.
=> New tipline request types

app/graph/types/project_media_type.rb, app/models/concerns/project_media_cached_fields.rb, test/models/project_media_test.rb, test/test_helper.rb
Two new boolean fields are available for the `ProjectMedia` type on GraphQL API: `is_suggested` and `is_confirmed`. They will be true when an item is a suggested similar or confirmed similar to another item, respectively. Both fields are cached, so N + 1 queries problems are avoided when many items are requested at the same time.
Reference: CHECK-1613.
=> Expose on GraphQL API if an item is suggested or confirmed to another item

app/models/concerns/smooch_resources.rb
Currently the content of RSS feeds displayed in tipline bot resources is cached and updated by a regular Sidekiq job. But that approach is fragile and often those resources get stalled. The change here is:
* Automatically expire the cache every 15 minutes (same interval as the current Sidekiq job)
* Return the feed URL to the user if parsing fails
Reference: CHECK-1898.
=> More robust caching for RSS feeds on tipline bot resources

app/models/project.rb, app/models/team.rb, lib/tasks/migrate/20220602140010_update_medias_count_cache.rake, test/models/team_test.rb
Recently, "unconfirmed" items started to be displayed by default on lists. So the counters need to be updated accordingly.
Fixes CHECK-1946.
=> Fixing methods that count the number of items in a folder or workspace

app/models/concerns/smooch_team_bot_installation.rb, app/models/concerns/team_associations.rb, app/models/team.rb, app/models/team_task.rb, test/models/bot/alegre_2_test.rb
We're using Redis as a backend for Rails.cache. The `delete_matched` method uses Redis' `KEYS`, which has an O(n) complexity. It gets really slow in production because we have too many keys stored in Redis. So, we should avoid using that method in code that runs in foreground, otherwise things can get really slow. This commit replaces these use cases by individual `Rails.cache.delete` calls, which are O(1).
References:
* https://api.rubyonrails.org/classes/ActiveSupport/Cache/RedisCacheStore.html#method-i-delete_matched
* https://redis.io/commands/keys/
Related tickets: CHECK-1905, CHECK-1907 and CHECK-1922.
=> Avoid `Rails.cache.delete_matched` method in foreground code

app/models/bot/fetch.rb, app/models/fact_check.rb, test/models/bot/fetch_test.rb
Validate before saving that field values are under limits and truncate when importing through Fetch.
Reference: CHECK-1925.
=> Maximum length for fact-check fields

app/models/bot/fetch.rb, db/migrate/20220610222339_add_unique_index_for_fetch_external_id_field.rb, db/schema.rb, test/models/bot/fetch_test.rb
* Append the team ID when saving an "external_id" annotation field (this way they can be unique within teams)
* Add a unique PostgreSQL index for the "value" column of "external_id" annotation fields
* Adding automated tests for all the cases
* Skip permission check when creating imported reports
Before deployment, it's necessary to delete existing duplicate "external_id" annotation fields, otherwise the migration that adds the unique index will fail:
On Rails console: `ActiveRecord::Base.connection.execute("DELETE FROM dynamic_annotation_fields daf1 USING dynamic_annotation_fields daf2 WHERE daf1.field_name = 'external_id' AND daf2.field_name = 'external_id' AND daf1.value = daf2.value AND daf1.id < daf2.id")`
Fixes CHECK-1980.
=> Avoid duplicate Fetch import

app/models/bot/smooch.rb, app/models/concerns/smooch_language.rb, test/models/bot/smooch_5_test.rb
When a tipline user session has ended and the tipline user chooses an option from the main menu, the tipline bot was replying with the greetings instead of processing the menu option. This fix is to try to process a menu option even if the user is just starting a new session.
Fixes CHECK-1551.
=> Try to process tipline menu option instead of sending greetings on new sessions

app/models/bot/smooch.rb, test/models/version_test.rb
If two or more messages are sent at the same second, when the user session times out, more than one request would be created in Check. Changing to a more granular check avoids this situation.
Also fixing a flaky test.
Fixes CHECK-2022.
=> Fixing race condition on tipline bot when user query submission times out

app/models/bot/fetch.rb, app/models/fact_check.rb
Keep the truncation only for title and summary. We can't truncate the URL because a broken link won't take the user to the full fact-check.
Fixes CHECK-1985.
=> No more truncation for fact-check URL

app/graph/types/team_type.rb, test/controllers/graphql_controller_2_test.rb
This way, it's possible to retrieve a single team task by passing its database ID.
Reference: CHECK-2089.
=> Adding "team_task" GraphQL field to "TeamType"

app/models/concerns/smooch_search.rb, test/models/bot/smooch_5_test.rb
=> Return empty result set on tipline search if it's searching for a link with empty description

app/models/bot/smooch.rb
Edits `smooch.rb` to allow sending reports for unconfirmed items.
Fixes CHECK-1904
=> Remove need to confirm item for publishing report

app/graph/types/team_type.rb, app/models/workflow/concerns/team_concern.rb, test/controllers/graphql_controller_3_test.rb, test/controllers/graphql_controller_test.rb
Previously, this method could take two optional boolean arguments, which were both false by default. When true, each status would be returned with the number of (published) items with that status. But that is very costly, since that number of items is calculated on the fly. This refactoring turns those two arguments into strings, which are supposed to contain a status ID, this way, the counters are returned only for that requested status.
Reference: CHECK-2150.
=> Refactoring method that returns statuses from a workspace.

Dockerfile
In the Docker container on M1 Macs, I was running into an issue when
installing Nokogiri that a required library, glibc 2.29, was not
available. This prevented running check-api on my machine, though the image built successfully.
Nokogiri's recommended approach for addressing this is to force
using the Ruby platform gem. For our version of Bundler (<2.0), it
is only possible to do this at the bundler config level (vs gem
level, which is supported in Bundler >=2.3.18).
https://nokogiri.org/tutorials/installing_nokogiri.html#how-can-i-avoid-using-a-precompiled-native-gem
CHECK-2147
For folks I've tagged for review, I'd love thoughts on:
* If there's a way we could address this at the container level (like making sure glibc is available)
* Any concerns about using ruby platform gem / …
=> Avoid using Nokogiri precompiled native gem

app/models/bot/alegre.rb, app/models/concerns/alegre_similarity.rb, app/models/concerns/smooch_search.rb, app/resources/api/v2/feed_resource.rb, test/controllers/feeds_controller_test.rb, test/models/bot/alegre_test.rb, test/models/bot/smooch_5_test.rb, test/models/bot/smooch_6_test.rb
A set of fixes and improvements to the feeds API and tipline bot search. Details below:
**Cache search results**
It's expected that some search queries sent to the feed API or tipline bot are repeated. So, let's cache the search results. For now, hard-coded at 2 hours. Reference: CHECK-2167.
**Use vector models when searching across multiple workspaces**
Previously, when searching for items under a single workspace, vector models could be used if the workspace was configured to use them. But when searching for items under multiple workspaces, it just fell back to the default model. This change is to use all models configured for each workspace when searching across multiple workspaces. Reference: CHECK-2170.
**When there is no published fact-check for a submitted query URL, fallback to …
=> Feeds API: Fixes and improvements

app/models/team.rb
Previously, the workspace columns settings cache was cleared only for the languages supported by the workspace. But sometimes a user is browsing in a language that is not supported by the workspace. If that's the case, this user won't be able to save the settings or refresh the cache for the list view. The fix is to include also the languages supported by the application when clearing cache, since users can be browsing in any of those languages.
Fixes CHECK-2197.
=> When clearing workspace columns settings, all languages should be included

.gitlab-ci.yml, lib/tasks/data/similarity.rake, lib/tasks/data/similarityunc.rake, production/bin/start.sh, scripts/batch-entrypoint.sh
This change adds support for batch jobs via a specific batch entrypoint script. This method of execution avoids task rotation and resource limits present in the ECS check-api service.
=> Update batch entrypoint support with latest SSM driven configuration.

config/application.rb
Previously, configuration values lived in config/config.yml, but now they are stored in environment variables.
Fixes CHECK-2282.
=> Read configuration values from environment variables in config/application.rb

app/models/concerns/alegre_similarity.rb
The previous condition, 'type != text', was not enough because it didn't discard blank items.
Fixes CHECK-2271.
=> Do not try to send "blank" items to Alegre media similarity index.

app/models/bot/fetch.rb
When Fetch imports a report, it shouldn't set the report language to be the one of the claim review, because maybe the workspace doesn't support that language. Also, we're soon getting rid of the report language, and just keeping it for fact-checks. The fix here is to revert to how it was before, which is to use the workspace default language as the report language.
Fixes CHECK-2328.
=> Fixing imported report language

app/graph/types/query_type.rb
This commit adds a random argument to team graphql type to cheat weird relay caching. Some queries in SearchFieldXxx components were not trigerred, probably because of having a similar root to both QueryRenderers.
Type of change
☑︎ Bug fix (non-breaking change which fixes an issue)
How has this been tested?
I created a filter with fields "Assigned to" and "Folder is" and applied it to "All items" and verified that the page loads correctly without crashing.  
I haven't implemented any automated tests.
Fixes: CHECK-2331
=> CHECK-2331: Add random argument to team graphql type

app/graph/types/feed_type.rb, app/graph/types/request_type.rb, app/models/feed.rb, app/models/request.rb, db/migrate/20220825223906_add_request_id_and_media_id_to_requests.rb, db/migrate/20220828210303_add_fields_to_requests.rb, db/schema.rb, lib/sample_data.rb, test/controllers/feeds_controller_test.rb, test/controllers/graphql_controller_5_test.rb, test/models/request_test.rb
* Request has media: For each request to the Feed API, a Request object should be created and its media should be automatically extracted
* Request has a similar request: When a Request is created, if its media is similar to another media of a Request of the same Feed, they should be related (one level only)
Reference: CHECK-2253.
=> Feed API: Similar requests and media requests.

app/graph/types/query_type.rb, app/graph/types/request_type.rb, app/models/media.rb, app/models/request.rb, test/models/request_test.rb
* Fixing typo in field `last_submitted_at`
* Implementing a `medias` method for the `Request` model (already exposed in `RequestType` as a `connection`)
Reference: CHECK-2253.
=> Shared Feeds v1: Changes to GraphQL `RequestType`

app/graph/types/query_type.rb, app/graph/types/request_type.rb, app/models/request.rb, lib/check_basic_abilities.rb, test/controllers/graphql_controller_5_test.rb, test/models/request_test.rb
* Add a field `request` to `QueryType`, to be sure that we can get a request by its ID (permissions set accordingly)
* Add a `media_id` argument to `RequestType` connection `similar_requests`
* Group (clusterize) requests that mention the same URL
* Add a field `feed` to `RequestType`
Reference: CHECK-2253.
=> Changes to requests/feeds and related GraphQL APIs.

app/models/request.rb
Bugfix: When attaching a request to a similar request, be sure that the request is not attached to itself.
Fixes CHECK-2253.
=> Avoid circular relationship when attaching request to similar one

app/models/concerns/smooch_search.rb, lib/check_search.rb, test/models/bot/smooch_5_test.rb
When searching by keyword on a tipline or from a feed API request, the search results should be sorted by score.
Fixes CHECK-2357.
=> Sort keyword search results by score on tipline search and feed API.

app/models/concerns/smooch_search.rb, test/models/bot/smooch_5_test.rb
=> Strip all URLs from query when falling back to query from link search on tipline bot or feed API

app/models/bot/smooch.rb, test/models/bot/smooch_5_test.rb, test/models/bot/smooch_test.rb
This error was triggered by a URL that contained accents.
Fixes CHECK-2367.
=> Escape URLs before verifying if they are valid.

app/models/bot/smooch.rb, app/models/request.rb, lib/tasks/migrate/20220828210303_request_fields.rake, test/controllers/feeds_controller_test.rb
* Cluster requests related to the same media
* Validate that the `request_type` is valid
* Better way to look for existing text media, by ignoring case and removing trailing and leading spaces
* Added rake task to extract media for existing requests and to clusterize existing requests
Fixes CHECK-2253.
=> Fixing request clustering and validation.

app/models/concerns/smooch_search.rb, test/models/bot/smooch_5_test.rb
For media queries, the medias can be stored locally. Additional headers to access the media can be stored in the feed settings.
Reference: CHECK-2423.
=> Support media queries on feed API.

app/models/bot/fetch.rb, app/models/fact_check.rb
Now only fact-check summary has a limit. The summary is truncated (when importing from Fetch) but title and URL never are.
Reference: CHECK-2468.
=> No more limits for fact-check title and URL.

app/models/bot/fetch.rb, app/models/concerns/smooch_search.rb
* For imported reports, the status on visual cards should be localized to the workspace's default language (CHECK-2466)
* Prioritize text reports on search results (CHECK-2459)
=> A couple fixes for reports

app/models/concerns/has_file.rb
This is an easy win in terms of performance... it avoids N + 1 performance issues on various GraphQL queries and it's a value that never changes, so we can keep it cached forever essencially.
Hopefully fixes CHECK-2491.
=> Cache media file path

app/models/bot/alegre.rb, app/resources/api/v2/feed_resource.rb
Some of those calls to Alegre can take a long time. Under concurrency, some requests possibly won't get a database connection if some of them are locked by a request that is waiting for a response from Alegre. Currently using it only for feed requests.
=> Release database connection while calling Alegre during feed API request

app/models/concerns/project_media_creators.rb
This reverts commit 1f7f3803e5cd7b5a28af9e7fc361106fa8443777, since it was
causing the front end to display a confusing error to user and no longer redirecting.
=> Revert "Raise exception on failed save from Pender link"

app/graph/types/feed_type.rb, app/models/feed.rb, app/models/project_media_request.rb, app/models/request.rb, config/initializers/report_designer.rb, db/migrate/20221014033716_add_fact_checked_by_count_to_requests.rb, db/schema.rb, test/models/request_test.rb
* Store in a new `requests.fact_checked_by_count` database column the number of organizations that have a fact-check for that request
* Instead of considering all workspaces that are part of the feed, it now considers only the ones that have sharing enabled
* Only fact-checks that are actually part of the feed are included
* Sort requests by number of organizations that fact-checked them
* Also consider workspaces that returned fact-checks for keyword queries
Reference: CHECK-2500.
=> Refactoring "fact_checked_by" for feed requests.

app/models/concerns/project_media_creators.rb, test/models/concerns/project_media_creators_test.rb
Previously we were looking up by the normalized URL from Pender, and then re-sending that normalized URL to Pender if the lookup failed. This means that even though Pender could be (and was) returning deterministic reference URLs when given the same URL that we were actually asking it for different URLs in some cases. This was causing a bug where the Media could not be created successfully on our side sometimes, because there was already Media in the database that we didn't retrieve on the lookup before because of the URL changes.
=> Send the same URL to Pender when looking up or creating Link

app/models/concerns/smooch_turnio.rb
Among other things, that field is used to generate conversation statistics.
Fixes CHECK-2592.
=> Set originalMessageId when saving message received through tipline in self-hosted WABA

production/bin/create_configs.sh
This change checks for required configuration settings during QA and Live deployments, and exit with error if any are missing. This will halt deployment with an explanation of missing configurations, rather than continue with application errors.
=> If required configurations for QA or Live are missing, fail with error

Gemfile, Gemfile.lock, test/test_helper.rb
In order to get mocha to tear down stubs, it has to be loaded last. I think that previously we were importing it before some of our minitest libraries, and also weren't using the minitest-specific version of the gem, which meant that we lost the auto-teardown functionality.
Changing the version of mocha and the load order means we no longer need to manually tear down mocks as part of test setup and teardown. (See https://github.com/freerange/mocha#installation)
See related Pender commit: https://github.com/meedan/pender/pull/281/commits/eac701330e9259731a36b9f15337da3e3e383eb6
=> Configure mocha to automatically teardown stubs after test run

app/models/bot/fetch.rb, app/workers/fetch_worker.rb
Use a regular `FetchWorker` instead of executing a delayed class method. This way we can customize the interval between retries and thus avoid some database errors.
Fixes CHECK-2619.
=> Fetch Sidekiq job refactoring.

app/models/bot/alegre.rb, app/models/concerns/project_media_creators.rb, app/models/concerns/project_media_getters.rb
* Disable automatic similarity matching for items imported from shared feeds (because the cluster should be manually-formed by the items imported)
* When creating a new item related to another one, set the relationship type as "confirmed" instead of "default", which was deprecated a while ago
Reference: CHECK-2508.
=> Bulk-import medias from shared feed.

app/models/request.rb, test/models/request_test.rb
When clustering requests on feeds, use different models depending on length
=> CHECK-2701 - Add min_word parameter to text models for clustering feed requests

app/models/relationship.rb, test/models/relationship_test.rb
There is a similarity relationship between items A and B. A is the main. A has report, claim and fact-check. If B is pinned (so, the relationship between A and B is inverted and B becomes the new main item), then B should inherit the report, claim and fact-check from A.
Fixes CHECK-2753.
=> Inherit report when pinning a new item

db/migrate/20221122015259_remove_archive_is_annotation_type.rb, db/schema.rb
The rest of code was deleted in a previous commit.
=> Add migration to delete unused Annotation Type for Archive.is

app/models/bot/smooch.rb
There is a condition where a message is only sent to the tipline user on timeout if the user has any bundled messages not stored yet. But since bundled messages are stored before the message is sent, that condition will never be met. Fixing by changing the order of things... first, a message is sent on timeout, after that the bundled messages are stored.
Fixes CHECK-2747.
=> Fix: Send message to tipline user on timeout.

app/models/concerns/smooch_search.rb, test/models/bot/smooch_5_test.rb
When a query is only emoji, we should not run a fuzzy search
=> CHECK-2748 - no fuzzy search for emoji only query

app/models/request.rb, lib/tasks/data/reclusterize_requests.rake, test/models/request_test.rb
When looking for a feed request that is similar to another feed request, be sure that a circular relation doesn't happen: a feed request can't be similar to itself.
Fixes CHECK-2773.
=> Avoid circular dependency in feed request.

app/models/bot/smooch.rb, app/models/concerns/smooch_messages.rb, app/models/concerns/smooch_newsletter.rb, app/models/concerns/smooch_resend.rb, app/models/concerns/smooch_resources.rb, app/workers/tipline_newsletter_worker.rb, test/workers/tipline_newsletter_worker_test.rb
When the "main menu" is appended to a message, there is no preview for the URLs in that message. So, in order to have a preview rendered for URLs in final messages, the "main menu" is sent as a separate message. This applies for the following cases: resources, newsletters and reports.
Implementation-wise, that is pretty simple: in addition to the existing `send_final_message_to_user` there is now a new `send_final_messages_to_user`.
Reference: CHECK-2721.
=> Send "main menu" as a separate message on final messages

lib/check_open_telemetry_config.rb
Redis accounts for most of our events in Honeycomb, which we're often going over, but we don't find it very useful. This removes the instrumentation so that we no longer track that information.
=> Stop sending Redis information to Honeycomb

app/models/concerns/smooch_language.rb
This way it's possible to manually define a particular order for the languages.
Fixes: CHECK-2805.
=> Do not sort languages supported by a tipline.

app/models/request.rb, lib/tasks/data/reclusterize_requests.rake, test/models/request_test.rb
Update Request model to require parent (request_id) to have a lower id than the child. This shouldn't have any effect on on-going /realtime clustering. It is, however, necessary when reclustering a feed.
=> CHECK-2773: Recluster shared feed

app/models/bot/smooch.rb, app/models/concerns/smooch_resources.rb, app/models/concerns/smooch_strings.rb, config/tipline_strings.yml
* No more resource or RSS feed: Now just a regular message is sent
* This message can be customized per workflow
* If not customized, a default message is sent
Reference: CHECK-2747.
=> Refactoring what happens when a tipline conversation times out.

app/models/bot/smooch.rb, app/models/concerns/smooch_menus.rb, app/models/concerns/smooch_messages.rb, app/models/concerns/smooch_resources.rb, app/models/concerns/smooch_search.rb, app/models/concerns/smooch_strings.rb, config/tipline_strings.yml
* The method `get_string` is only for hard-coded tipline strings, downloaded from Transifex into a YML file
* The method `get_menu_string` was renamed to `get_custom_string` and returns either a custom string/translation stored in a tipline workflow (so, in the database, in the Smooch Bot installation settings) or a default string in English
Reference: CHECK-2747.
=> Refactoring/normalizing how strings are localized on the tipline.

app/models/bot/smooch.rb, test/models/bot/smooch_6_test.rb
=> Fixing timeout message when tipline is connected to both Smooch and self-hosted WABA

app/models/fact_check.rb
The default report introduction settings for a given language and workspace should be respected when a report is created or updated when a fact-check is saved.
Fixes: CHECK-2853.
=> Respect workspace report introduction settings when creating or updating report from saved fact-check

app/models/concerns/smooch_messages.rb, test/models/bot/smooch_5_test.rb, test/models/bot/smooch_6_test.rb
When a user finishes interacting with the tipline bot, all messages that were sent by the user during the interaction are bundled into a single one. In some cases, some messages can be duplicated, either by a race condition, duplicate bundling or just because the user sends twice. So, be sure to de-duplicate messages before bundling.
Fixes CHECK-2846.
=> Avoid duplicate user messages when bundling

config/environments/test.rb, lib/sample_data.rb, test/controllers/elastic_search_5_test.rb, test/controllers/graphql_controller_2_test.rb, test/controllers/graphql_controller_4_test.rb, test/controllers/graphql_controller_5_test.rb, test/controllers/graphql_controller_test.rb, test/models/ability_test.rb, test/models/annotation_test.rb, test/models/claim_description_test.rb, test/models/fact_check_test.rb, test/models/project_media_test.rb, test/models/relationship_test.rb, test/models/status_test.rb, test/models/tag_test.rb, test/models/tipline_subscription_test.rb, test/models/version_test.rb, test/test_helper.rb
Disable `PaperTrail` on tests, and enable it only for tests that really need it. The idea here is to try to make tests run faster. Reference: https://github.com/paper-trail-gem/paper_trail#7-testing.
=> Disable PaperTrail from tests

lib/check_statistics.rb, lib/tasks/data/statistics.rake, test/lib/tasks/statistics_test.rb, test/test_helper.rb
This PR simplifies our rake task for statistics generation, by:
1. Detecting what workspaces need to have statistics generated by looking which have historic tipline data, rather than passing in the workspace slugs. Data is then generated for each month (segmented by language and platform) since the first submitted tipline project media
2. Removing all tipline statistics (day and weekly data) that are not displayed within the application
3. Removing all feed statistics
For points 2 and 3, these statistics were being uploaded to S3 for manual processing for partners. We are going to move these into Metabase, so are removing them to simplify the rake task and instead retaining only the statistics that are added to the cache to be displayed in the web app
This also adds a simple sanity test …
=> Simplify statistics rake task to only generate tipline data

config/initializers/zz_open_telemetry.rb, lib/check_open_telemetry_config.rb, lib/check_statistics.rb, lib/tasks/data/statistics.rake, test/lib/check_open_telemetry_config_test.rb, test/lib/tasks/statistics_test.rb
Creates new spans around each time we run "get_statistics" for the statistics rake task, and also around each
of the different statistics we generate. The goal of this is for us to be able to troubleshoot slowness better on Honeycomb. This may generate a lot of spans on live, but is only run once per day.
Also passes the team ID around instead of slug in the rake task since we already have it available, and it will help to reduce the number of times we touch the database.
=> Add manual instrumentation to statistics rake task

README.md, config/initializers/zz_open_telemetry.rb, lib/check_open_telemetry_config.rb, test/lib/check_open_telemetry_config_test.rb
Previously we were only able to change the sampling configuration by changing config.yml. This makes forcing a send of data to Honeycomb on a per-job basis, like in a rake task, difficult. To address that, this PR allows for setting an environment variable CHECK_SKIP_HONEYCOMB_SAMPLING, named similarly to the env var we already use for skipping tracing (CHECK_SKIP_HONEYCOMB), to force sending collected traces to Honeycomb. Intended use is when we want specific tasks to be reliably sent to Honeycomb.
=> Allow disabling trace sampling via env var

app/models/concerns/team_associations.rb, app/models/monthly_team_statistic.rb, app/models/team.rb, config/initializers/zz_open_telemetry.rb, db/migrate/20230106220307_create_monthly_team_statistics.rb, db/schema.rb, lib/check_statistics.rb, lib/sample_data.rb, lib/tasks/data/statistics.rake, test/lib/tasks/lapis_error_codes_test.rb, test/lib/tasks/statistics_test.rb, test/models/monthly_team_statistics_test.rb, test/models/team_test.rb
Previously we were generating statistics and storing them to the Rails cache. The entries could be very large - one row per language, platform, and month since a tipline was enabled, for each workspace. We were also generating statistics for each month each time we ran it, which took a long time.
This PR moves toward saving the data more incrementally as a single-purpose ActiveRecord model, and determines which months to generate based on what months have missing or partial data.
From the frontend's perspective, this change should not change any behavior except for two small things:
* The ID returned with each row of the report is different (numeric ID from database instead of generated ID with date, platform, etc)
* Month is in format of `1. Jun 2020` instead of `1. 2020-06-01` (most …
=> Save generated statistics to Postgres instead of Rails cache

lib/tasks/data/statistics.rake
Accidentally was pinned to "current_time", which is only intended to make sure that all statistics are calculated until a consistent time. We need time deltas for logging, though.
CHECK-2892
=> Log current timestamp in statistics rake task

app/models/user.rb
The HTML structure had changed, which caused our regex to fail to capture the last modified date. This commit changes the regex to capture the current format when stripped of HTML (eg "Last modifiedJanuary 13, 2023") while also building in some hopefully helpful affordances for future - specifically, the ability to detect shortened month names (eg "Last modifiedJan 13, 2023") and two date years (which might be weird - eg "Last modified Jan 13, 23")
CHECK-2898
=> Update regex for detect last modified date for TOS and privacy policy

app/graph/mutations/graphql_crud_operations.rb
Exception should not be raised if the mutation was made using a valid API key.
Fixes CHECK-2762.
=> Fixing permission check for update mutations

lib/tasks/data/statistics.rake, test/lib/tasks/statistics_test.rb
In production data, some teams with inactive tiplines do not have languages configured. In these cases, we can safetly skip over them for statistics generation.
CHECK-2892
=> Prevent error when team has no languages configured

app/graph/types/root_level_type.rb, app/models/bot_user.rb, config/locales/en.yml, db/migrate/20230116233317_set_listed_bots.rb, db/schema.rb, public/relay.json, test/controllers/graphql_controller_2_test.rb
This is a new boolean attribute. "Listed" bots are the ones that are displayed to users so they can install in their workspaces.
Reference: CHECK-2902.
=> Adding "listed" attribute to bots

app/models/team.rb, test/models/team_test.rb
We may have a period of time between when we deploy the application and when we deploy the new batch statistics job that uses the Postgres database instead of the Rails cache. To make sure the data report pages still show some statistics, this commit introduces a fallback for the data report - if the Postgres data has been populated, use it. If not, look to the Rails cache and present the data how it was presented before the format update.
We can merge this safely even if we expect to update the batch job before the next deploy, which I think we should do to decouple the deploy processes.
If merged, this commit can be reverted after we have run the updated statistics batch job for the first time.
CV2-2565
=> Fallback to Rails cache for statistics

app/models/bot/smooch.rb, data/zh/languages.yml, lib/check_cldr.rb
This commit drops the usage of older smooch bot v1 messages that are saved in the workflow data in favor of the current way of getting localized strings for tiplines: either get_string or get_custom_string
References CV2-2602
=> Do not use v1 workflow messages

app/models/concerns/smooch_messages.rb, app/workers/tipline_newsletter_worker.rb
Increasing interval between sending newsletter content and sending message with "main menu".
Just be sure that the user has enough time to read the newsletter content and avoid the chances of the main menu being delivered first.
Fixes CHECK-2563.
=> Increasing interval between sending newsletter content and sending main menu.

lib/check_statistics.rb
We want to support smooch data both as hash and as string, since in production we were seeing both values and a hash was causing the script to error.
CV2-2565
=> Safe parse JSON in case team data has not been migrated to string

app/models/monthly_team_statistic.rb, app/models/team.rb, test/models/monthly_team_statistics_test.rb, test/models/team_test.rb
Previously we were retrieving the team name from the database each time we called .org on a MonthlyTeamStatistic, even though this would not change within the scope of a data report (because it's always for the same team). On teams with large datasets, this would significantly slow the GraphQL response.
Instead, this takes the approach of setting the org name at the team level, which we already have, and instead only has the MonthlyTeamStatistic present information it has available in its table, reducing number of queries to the database.
CV2-2565
=> Reduce database calls when compiling team data_report

app/models/concerns/smooch_messages.rb, test/models/bot/smooch_6_test.rb
The original issue here was: sometimes a newsletter delivery fails, to a user that hasn't interacted with the tipline in the last 24 hours. Not only a failure, but also a race condition. Anyway, when it happens, there will be no stored ID for the message that was sent with the "Read More" button. This way, when "Read More" is clicked, the application doesn't know that it is connected to a newsletter and thus simply handles it as a regular message. In order to try to avoid storing a request for that situation, ignore the following combination of conditions:
* Only one message
* That message is a reply to another message (so, a button or menu was clicked)
* It's of type "timeout"
* There was no "payload" (so it's not a button or menu from the tipline settings)
Fixes CHECK-2607.
=> Do not store a tipline request that is just a reaction to a button not related to any other action

app/models/concerns/smooch_search.rb, config/initializers/02_sidekiq.rb, test/models/bot/smooch_6_test.rb
In some cases, tipline users were not receiving the feedback prompt after a search ("Are these fact-checks answering your question?"). This can happen for various reasons, including some we can't control. So, it's better to be more robust on our side. This commit adds the following change: the feedback prompt is delivered after 20 seconds waiting for the confirmation that the user has received the search results.
Bonus: Disable Sidekiq INFO-level log messages on tests output.
Fixes CV2-2692.
=> More robust feedback prompt on tipline search

app/models/concerns/project_media_creators.rb, test/models/project_media_test.rb
Currently, the pattern for media items titles is `<media type>-<team slug>-<number of items of that type>`. The problem is that a collision can happen when items are deleted, because the number of items of that type can be repeated. This commit tries to avoid a name collision by replacing that count by the ID of the item.
Fixes CV2-2695.
=> Avoid name collision for media items titles.

app/models/concerns/smooch_menus.rb, app/models/concerns/smooch_messages.rb
Some customizable tipline strings were missing default values. Adding them here so it's aligned with the default strings that the frontend shows.
Fixes CV2-2689.
=> Adding some missing default tipline strings

app/models/project_media.rb
Per discussions I had with @caiosba, this seemed like the best way for now since this API call is only used by this one part of the app anyway.
=> Change default sort order of suggested similar relationships

lib/tasks/data/statistics.rake, test/lib/tasks/statistics_test.rb
Previously we were bailing out of statistics generation when the month index was less than the current date, which meant that, for example, if the first project media for a team was mid-month and we were at the beginning of the month then we wouldn't generate a new MonthlyTeamStatistic for that month. The user- facing impact of this is that some teams weren't having new stats generated for them despite it being a new month.
This changes the approach to determine when to stop generating statistics by comparing the current time to the start of the month being generated. This should protect us from generating future stats without accidentally skipping the current month.
CV2-2729
=> Bugfix: Generate monthly statistics for current month

app/graph/types/project_media_type.rb, app/graph/types/source_type.rb, app/workers/reindex_alegre_workspace.rb, db/migrate/20230216030351_add_unique_index_to_relationship_target_id.rb, db/schema.rb, lib/tasks/migrate/20230216030351_delete_duplicate_relationships.rake, test/models/relationship_2_test.rb
We had to have some database-level validation (e.g., a unique index) in order to avoid that an item is related to more than one. In some rare cases, just a model-level validation wouldn't be enough. For example, we've seen some cases where the same item was suggested to two different items. What happened there was a race condition (not likely to happen, but still), for example: looking for related videos happens in a background job and getting transcription happens in another background job. Both executed in parallel and finished at almost the same time and both found a similar item. So that item ended up being suggested to two different items: to one because it’s a similar video and to the other because the transcription matched a text field.
This PR adds a unique index to the …
=> Adding a unique index to `relationships.target_id` column.

Gemfile, Gemfile.lock, app/models/bot/smooch.rb, app/models/concerns/smooch_language.rb, app/models/concerns/smooch_messages.rb, app/models/concerns/smooch_resend.rb, app/models/concerns/team_associations.rb, app/models/tipline_message.rb, app/workers/smooch_tipline_message_worker.rb, app/workers/tipline_newsletter_worker.rb, db/migrate/20230207200055_create_tipline_messages.rb, db/schema.rb, lib/check_basic_abilities.rb, lib/check_search.rb, test/models/bot/smooch_2_test.rb, test/models/bot/smooch_7_test.rb, test/models/bot/smooch_test.rb, test/models/monthly_team_statistics_test.rb, test/models/tipline_message_test.rb, test/test_helper.rb, test/workers/smooch_tipline_message_worker_test.rb.rb
Specific questions I had noted inline as comments below, but all feedback and other questions welcome!
- Tested with a local Telegram tipline and my personal phone
- Was able to see a TiplineMessage created for each message delivered to my phone, with language ("en"), platform ("Telegram"), sent_at, uid, external_id, and payload all set as expected
- Event was present for messages associated with a newsletter or report creation / update
**Store messages to tipline in database - from user & when newsletter sent**
In order to move away from calculating conversations from the data stored
in annotations, we are beginning to save information in a new model, named
TiplineMessage. These are intended to be saved each time a message is sent
or received, and we are beginning to save them when a …
=> Save tipline messages when messages sent and received

app/models/concerns/smooch_menus.rb, app/models/concerns/smooch_team_bot_installation.rb, app/models/tipline_message.rb, app/workers/reindex_alegre_workspace.rb, app/workers/smooch_tipline_message_worker.rb, db/schema.rb, test/models/team_bot_installation_test.rb
**(1) Ensure that WhatsApp token can't be overwritten in tipline settings**
We had an issue with WhatsApp tokens in the past: since they are in the tipline settings page, users that had the tipline settings page already opened while the token was refreshed could overwrite the token with their settings by hitting “publish”. We worked around that on https://meedan.atlassian.net/browse/CV2-2482 : users would get an error when trying to save tipline settings if other changes were saved since they loaded the settings page. This is a way to avoid conflicts.
But it still happened with a workspace twice this week. I strongly suspect that some of their users still have the old Check version loaded in the browser and didn’t reload the page.
On our side, let’s be even safer and not even allow the …
=> A couple of tipline fixes: corrupted greeting image & WhatsApp token update

app/models/concerns/smooch_turnio.rb, test/models/concerns/smooch_turnio_test.rb
For the self-hosted WhatsApp API, we were seeing that in some cases the recipient_id is only returned in the message body. When this was the case, we previously were creating an incorrect UID (only the sending number, not the receiving number, which would not be unique for a given user).
This gives us more flexibility w/r/t payload structure. It also adds unit tests around the preprocess method so that we can more easily and directly test the translation of data in the future.
CV2-2647
=> Pull recipient id from message in payload from Turnio

app/models/concerns/smooch_turnio.rb, test/models/concerns/smooch_turnio_test.rb
We were setting this on unsucessful delivery but not successful delivery, and as a result messages from self-hosted WhatsApp lines were being registered as being from an unknown source.
This also adds some unit tests to reinforce the existing payload input and output expectations of the TurnIo preprocess step to make things more obvious and to support future refactoring, since there's a lot of duplication when we coerce the payload formats. This seems like it could be a good opportunity to break out a separate data model rather than coercing it into the Smooch format.
CV2-2647
=> Set platform on received TurnIo message

app/models/bot/smooch.rb, app/models/concerns/smooch_menus.rb, app/models/concerns/smooch_messages.rb
Previously, the installation was retrieved because on `smooch_app_id`, which self-hosted tiplines don't have. Switching to Smooch Bot installation ID, which all have.
Fixes CV2-2782.
=> Bugfix: Should get Smooch Bot installation ID for self-hosted tiplines.

.codeclimate.yml, app/models/concerns/project_media_creators.rb, app/models/fact_check.rb, app/models/project_media.rb, app/models/workflow/concerns/target_concern.rb
Also, better way to set status for items created through the GraphQL API (for example, if status is invalid, the item won't be created... and it's also possible to set the status and then publish a report).
Fixes: CV2-2807.
=> Set a report as "published" or not when creating an item with a fact-check through GraphQL API

app/models/bot/alegre.rb, app/models/concerns/alegre_similarity.rb, test/models/bot/alegre_3_test.rb
When multiple models return the same result, give both credit
=> CV2-2828 - Give multiple models credit

app/models/concerns/smooch_messages.rb, app/models/tipline_message.rb, db/migrate/20230224205948_add_legacy_smooch_data_to_tipline_message.rb, db/schema.rb, lib/tasks/migrate/20230224205948_add_legacy_smooch_data_to_tipline_message.rake, test/models/tipline_message_test.rb
This rake task intends to take the smooch data we have stored for annotations and translate them into the new TiplineMessage format, so that we can more easily calculate historic statistics data.
We iterate through a few types of saved data:
* Messages sent to users (via project media and team requests)
In this case, we are previously only storing one annotation for an entire lifecycle of a message, from receipt of initial message to submission of claim. This means that multiple of what we now consider TiplineMessages are represented by one Annotation and have been collapsed into one external_id, which in the new world will be unique. To get around this, we make the following modifications: 1) split up the message text by the text separator (a newline), 2) create two TiplineMessages for …
=> Add rake task to migrate smooch_data from annotations to TiplineMessage

db/migrate/20230309200728_remove_legacy_smooch_data_fields_from_tipline_message.rb
I wanted to delete the past data migrated, not the new data created.
This modifies a migration that has already been run on QA, so is mainly intended to prevent future data deletion locally and in other environments.
CV2-2647
=> Fix data deletion in migration task

app/models/bot/alegre.rb, test/models/bot/alegre_3_test.rb, test/models/bot/alegre_relationship_test.rb
https://meedan.atlassian.net/browse/CV2-2675
Alters the logic of how proposed similarity relationships are cached to deal with issues reported by users in which weak chains of similarity caused unrelated media to be suggested
- adds a test file that tries to enumerate the combinations of project media suggestions to cover the logc
- modifies the logic so that a suggestion to a suggestion will not be cached
- also implements the 'if a confirmed relationship is proposed to the child of a suggested relationship, break the (weaker) relationship with parent and form a new relationship cluster
=> [CV2-2675] Do not suggest to suggestions

app/models/monthly_team_statistic.rb, lib/check/tipline_message_statistics.rb, test/lib/tasks/check/tipline_message_stastics_test.rb, test/models/monthly_team_statistics_test.rb, test/models/team_test.rb
Uids are not guaranteed to be unique across teams, so we need to make sure that our cache key for calculating statistics includes the team_id in its key so that we don't accidentally impact cache keys for multiple teams.
CV2-2556
=> Add team_id to conversations calculation cache key

lib/check/tipline_message_statistics.rb, lib/tasks/data/statistics.rake, test/lib/tasks/check/tipline_message_stastics_test.rb, test/lib/tasks/statistics_test.rb
Previously we were storing 0 for months we were generating new conversations for. This made looking at data before the stated cutoff confusing, since it would show 0 instead of nil / "-". This makes it so that we don't even attempt to calculate conversations if something is before the date cutoff of April 1, when we're rolling this out, unless we specify to do so in the rake task.
CV2-2556
=> Only generate new conversations after date cutoff

test/models/bot/fetch_test.rb
While trying to fix a bug regarding some empty fact checks ([CV2-2842](https://meedan.atlassian.net/browse/CV2-2842?atlOrigin=eyJpIjoiODlkNWM4Y2I2ZGZmNDE5NTk0ZGEzMmJhMzg0ODU4YmIiLCJwIjoiaiJ9)), we wrote this test to check if the transaction is working. We have not solved the bug, but this is a good test to keep.
[CV2-2842]: https://meedan.atlassian.net/browse/CV2-2842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add rollback test to fetch test

README.md, test/test_helper.rb
This adds a more explicit way to skip generating test coverage and re-trying tests when running them locally, intended to be for running individual tests repeatedly. We previously were keying off of only the -n flag, which is used when running an individual test with ruby, but is a little awkward when using to run with `bin/rails`, which we're moving toward since it doesn't require manually specifying the environment.
To skip that output for individual tests, we can now run e.g.:
```
MINIMAL_TEST_RUN=true bin/rails test test/models/tipline_message_test.rb
or
bundle exec ruby -I"lib:test" test/path/to/specific_test.rb -n /.*KEYWORD.*/
```
=> Allow skipping test coverage report when running tests with bin/rails

app/models/bot/fetch.rb, test/models/bot/fetch_test.rb
=> When importing a fact-check from Fetch, fallback to `claimReviewed` if `headline` is blank

app/controllers/application_controller.rb
Can't reproduce this locally or in test, but it's happening in deployed envs. Likely because of autoloading differences? This should fix it.
CV2-2892
=> Fix NameError Api::V1::BaseApiController#ping

app/models/bot/smooch.rb, app/models/bot_user.rb, app/models/concerns/smooch_resend.rb, app/models/concerns/smooch_turnio.rb, app/models/concerns/smooch_zendesk.rb, app/models/request.rb
Previously we were sending whole bodies to Sentry, which triggered Sentry's sensitive data filters and prevented us from seeing some of the useful embedded data, like errors. This reduces the scope of what we're sending to Sentry to only things that will help us debug, and avoids sending identifiable information for users to the reporting service.
Lastly, it consolidates the custom exceptions relating to message sending to one (from three), since we don't expect to treat them differently. Instead, we just differentiate based on message.
CV2-2892
=> Consolidate message sending errors and limit data sent to Sentry

app/models/concerns/smooch_turnio.rb, app/models/concerns/smooch_zendesk.rb
Also makes the smooch data key consistent so that we can whitelist it in the Sentry data scrubbing.
CV2-2892
=> Don't send "to" to Sentry, since it may be the user's phone number

app/controllers/application_controller.rb, app/models/concerns/smooch_turnio.rb, app/models/concerns/smooch_zendesk.rb, lib/check_sentry.rb, test/controllers/base_api_controller_test.rb, test/lib/check_sentry_test.rb
Try to appease the default data scrubber gods
CV2-2892
Tested for final user error locally, but could not trigger Smooch or WhatsApp errors, so we'll have to see on QA.
=> Send more specific information to Sentry for message failure

app/models/monthly_team_statistic.rb, test/models/monthly_team_statistics_test.rb, test/models/team_test.rb
Partners are confused by the conversations column, since the data doesn't match what's in WhatsApp. As a result, we're moving it for now but still continuing to generate the data in the MonthlyTeamStastistic updated in the statistics rake task.
CV2-2969
=> Remove conversations column from data report, for now

app/models/relationship.rb, config/locales/en.yml, db/migrate/20230329123127_add_index_to_avoid_relationship_circular_dependency.rb, db/schema.rb, test/models/relationship_test.rb
* Adds a migration to delete current circular relationships and to add an index that avoids them
* Adds a unit test that reproduces the issue
* Adds a model validation to avoid that an item has a relationship with itself
Fixes CV2-2887.
=> Avoid circular relationships.

app/models/bot/smooch.rb, app/models/concerns/smooch_resend.rb, app/models/concerns/smooch_turnio.rb, app/models/concerns/smooch_zendesk.rb, test/models/bot/smooch_test.rb, test/models/concerns/smooch_turnio_test.rb, test/models/concerns/smooch_zendesk_test.rb
Currently we just send up three types of errors for message delivery, which makes it hard to tell which ones we can do something about and which ones we can't. This breaks the messages into there different types (Smooch, TurnIO, and "final", which might want to be one of those two) and adds a unique error message for the underlying error code. The latter should let us ignore ones in Sentry that we can do nothing about.
CV2-2975
=> Differentiate message delivery failure errors

.github/workflows/ci-push-image.yml
This creates a Github Actions workflow to build and push arm64 and amd64 images for all non-deploy branch (ie. develop and master) commits to our private repository. This will not be triggered by forks from external contributors.
Pushed images will be tagged with both git sha (ie. `873f96246cebf3196ac4a566bd5157d61c94df0f`) and branch name (innermost sub-branch after last `/`).
=> push images built by commit to ecr

production/Dockerfile
Previously we weren't installing bundler in the production Dockerfile, which caused a problem building the image when we upgraded to Ruby 2.7.7. This adds bundler back into the Dockerfile, configures Bundler similarly to how we configure it in the development Dockerfile, and also formats the dependency list (installed via apt-get) so that it's easier to compare against the development Dockerfile--and adds git, which we didn't have installed in the prod Dockerfile, but were seeing warnings about at deploy time.
CV2-2669
=> Install bundler in production Dockerfile

app/models/concerns/smooch_resend.rb, app/models/concerns/smooch_zendesk.rb, test/models/bot/smooch_7_test.rb
Placeholders in WhatsApp templates are mandatory. In order to be safe and guarantee message delivery (even if some placeholder is missing), let’s fallback to a default value when some placeholder value is not provided, this way we can guarantee that the message will be delivered.
Fixes CV2-3003.
=> Ensure that WhatsApp template placeholders are never blank.

Gemfile, Gemfile.lock, lib/check_statistics.rb, lib/tasks/data/statistics.rake, test/lib/tasks/statistics_test.rb
* In number_of_newsletters_sent: tries to reduce the number of database calls, so removes Team.find and uses team_id within queries instead. Also exits early if there is no team bot installation, or if the date range is before we implemented newsletters. This is to make the return more consistent across the two places we now use it
* Creates new rake task that we intend to run on demand, to regenerate a monthly team statistic for any that have been previously saved. In future we want to expand this rake task to support more stats, but for now it only accepts one argument: unique_newsletters_sent. The arguments here should correspondt to the database value on MonthlyTeamStatistic that it wants to regenerate.
* Also updates Mocha since I was troubleshooting - we'll see if that causes any …
=> Add task to regenerate newsletter statistics on demand

app/models/concerns/smooch_resend.rb
Fixes error `invalid_syntax` reported by Smooch (CV2-3078).
=> Do not attempt to send template message if template is blank

app/models/bot/alegre.rb, app/workers/tipline_newsletter_worker.rb
The fix is to reload the object before attempting to save.
Fixes CV2-3076.
=> Fixing error `ActiveRecord::StaleObjectError` reported by Sentry.

.codeclimate.yml, .rubocop.yml, Gemfile, Gemfile.lock
Trying to fix this error with Rubocop:
```
The `Lint/InvalidCharacterLiteral` cop has been removed since it was never being actually triggered.
(obsolete configuration found in .rubocop.yml, please update it)
Warning: unrecognized cop Lint/InvalidCharacterLiteral found in .rubocop.yml
Warning: unrecognized cop Layout/SpaceInsideBrackets found in .rubocop.yml
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/config.rb:510:in `check_target_ruby': Unknown Ruby version 2.7 found in `TargetRubyVersion` parameter (in .rubocop.yml). (RuboCop::ValidationError)
Supported versions: 2.1, 2.2, 2.3, 2.4, 2.5
from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/config.rb:313:in `validate'
from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/config.rb:201:in `check'
from …
```
=> Using a version of Rubocop that supports Ruby 2.7

app/graph/types/team_bot_installation_type.rb, app/models/concerns/smooch_team_bot_installation.rb, test/controllers/graphql_controller_7_test.rb
After the upgrade to Rails 6, we started to get consistent HTTP 409 errors coming from the web client when saving tipline settings, even when nothing has changed. After some debugging locally, I noticed it was due to two reasons:
* (1) An `after_save` callback that was re-saving the tipline bot installation but with the outdated lock version
* (2) The `lock_version` GraphQL field returned as a result of the mutation contained an outdated value as well
Respective fixes:
* (1) Reload the bot installation before re-saving
* (2) Reload the bot installation before returning the `lock_version` value
Both issues and respective fixes are kind of similar. I guess it has to do with some different way on how Rails 6 caches values during a lifecycle of a request.
Fixes CV2-3079.
=> Fixing consistent conflict error when saving tipline settings from web client after Rails 6 upgrade

config/environments/development.rb, config/initializers/03_sidekiq.rb
Previously we were using redis_store as our cache store, but it began causing problems because it is not compatible with cache versioning introduced by default in Rails 5.2. This store was provided by the redis-rails gem, wherease redis_cache_store was introduced in 5.2 as the out-of-the-box way to use redis as the Rails cache store, and does support cache versioning. So, we switch it. Configuration should be compatible.
We still use the redis-rails gem directly in other places, so we keep it as a dependency.
CV2-2669
=> Use redis_cache_store, which is built into Rails

config/application.rb, config/config.yml.example, config/environments/production.rb, config/environments/test.rb, production/bin/create_configs.sh
Previously we were loading a Base64 encoded string of a previous production.rb for Live and QA configuration in deployed environments, meaning what we had committed to config/environments/production.rb was being ignored.
This commit updates our committed production.rb with what was currently on QA / live, and refactors shared config to application.rb and extracts an environment variable for differing config across live & QA.
Lastly, it removes the step in our deployment where we try to create the production.rb file from SSM. Instead, it will use what's in repo.
CV2-3055
=> Update production.rb for use in deployed environments

config/initializers/new_framework_defaults_6_1.rb
We don't expect these to have a noticeable impact, but enabling them will allow us to move to using Rails 6.1 defaults as a whole in the future.
CV2-2669
=> Enable the rollback-able Rails 6.1 defaults

db/seeds.rb
**Making  it more resilient**
1. make the `seed.rb` file less dependent on Pender
- if for some reason Pender isn't up and running we still want the seed file to run
- **how:** we added `exception handling` to `Link.create!`
- if there is an issue during Link creation:
- everything will be created except Link Medias
- a warning will be printed to the user, letting them know Links were not created due to probably a Pender error
2. if there is another failure we don't want to keep inconsistent data
- **how:** we wrapped everything in a transaction
- if something fails (except for Link creation), everything is rolled back
3. we want to be able to run the `seed.rb` file more than once
- we had an issue running it multiple times because the url for `Link.create!` needs to be unique
- **how:** …
=> cv2-3060: make seed.rb file more resilient

app/models/dynamic_annotation/annotation_type.rb, app/models/link.rb, db/schema.rb, test/models/dynamic_annotation/annotation_type_test.rb, test/models/media_test.rb
(1) Validate if an annotation type if available by using `Object.const_defined?` instead of trying to `constantize` and `rescue NameError`
(2) Fallback to an empty string if there is no picture for a Pender structure
=> Fixing a couple of relevant Rubocop issues related to suppressed exceptions

docker-background.sh, production/bin/start_background.sh
We no longer need this and the file it references was removed in a previous commit, but I missed these lines.
=> Remove references to non-existent file server file

app/models/request.rb
Check file exists before open the file to avoid trigger an error `No such file or directory`
=> CV2-3086: check file exists

app/models/concerns/smooch_language.rb, app/models/concerns/smooch_search.rb
Replace `language = self.cached_user_language(uid)` with a method `self.get_user_language(uid, {}, nil, team_id)` which verify that cached value exists in team language otherwise return the default team language as sometimes the cached value deleted from team languages
=> CV2-3056: get user language based on supported language

lib/check_statistics.rb, lib/tasks/data/statistics.rake, test/lib/tasks/statistics_test.rb
We were trying to multiply by nil when the number of newsletters is nil, which was causing an error. Nil is somewhat meaningful, since it indicates that a team has not had a newsletter (vs having a newsletter but not sending it), so we want to preserve that behavior of displaying nil / - in some cases and zero in others.
CV2-3117
=> Protect against nil number of newsletters & subscribers

app/models/bot/alegre.rb
add constant for new OpenAI ada model
specify the ada model as a valid relationship model type
The goal is to add a new vector model for text similarity to Alegre, Check-API, and Check-Web. All repos have a CV2-3002 branch.
References: CV2-3002
=> CV2-3002: Add support for OpenAI ada embeddings

app/models/relationship.rb, test/models/relationship_test.rb
User `ActiveRecord::Base.connection.quote_string` for metadata json field instead of multiple use inside metadata array
=> CV2-2910: fix SyntaxError related to version metadata

app/graph/types/team_bot_installation_type.rb, app/models/tipline_newsletter.rb
- Don't schedule a newsletter to the past
- Don't try to parse an empty RSS feed URL
=> Do not schedule a newsletter to the past and do not try to parse an empty RSS feed URL

app/models/concerns/relationship_bulk.rb, test/models/relationship_test.rb
For `Relationship.bulk_destroy` there is a method that delete item cached fields `delete_cached_field` to enforce  create cached field with a new values 
I added all fields that related to `model: Relationship`
=> CV2-3142: handle delete cached fields for relationship-bulk_destroy

config/config.yml.example, lib/url_rewriter.rb, test/lib/url_rewriter_test.rb
Sometimes, the host that we use to display shortened URLs is different from what the backend actually processed (for example, when redirection rules are applied at upstream level).
Reference: CV2-2751.
=> Use a different host for displaying shortened URLs.

lib/url_rewriter.rb, test/lib/url_rewriter_test.rb
Prepend https:// to URLs if missing when adding UTM code and shortening.
=> Prepend https:// to URLs if missing when adding UTM code and shortening

Gemfile.lock
Updated rails-i18n reference to include "bn" locale date format fix done in our fork. Tested manually on my local dev env.
A couple of patch updates sneaked in when I did bundle install but should be irrelevant
:)
Fixes CV2-3183
=> Update rails-i18n revision on Gemfile.lock

lib/url_rewriter.rb, test/lib/url_rewriter_test.rb
When it fails to generate a shortened URL, fallback to the long URL. Includes a unit test to reproduce the exact same issue reported by Sentry.
Fixes CV2-3218.
=> Fallback to long URL if shortening fails

app/models/tipline_newsletter.rb, config/locales/en.yml, test/models/tipline_newsletter_test.rb
Adds a validation to the `TiplineNewsletter` model to be sure that a static newsletter can't be scheduled for the past. Includes a unit test and also fixes an unrelated error message copy.
Fixes: CV2-3212.
=> Make sure that a static newsletter can't be scheduled for the past.

Gemfile.lock
Run `bundle install`  to updated Gemfile.lock with latest changes and fix deployment error
```
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
```
=> CV2-2723: update Gemfile.lock

app/models/concerns/smooch_resend.rb, app/models/tipline_newsletter.rb
This way, formatting won't be messed up, like bold, for example.
Fixes CV2-3230.
=> Remove leading and trailing spaces from WhatsApp template placeholders.

lib/tasks/migrate/20230608215010_migrate_tipline_subscriptions.rake
The format of user IDs for Cloud API is `<tipline phone number>:<user phone number>`, only digits for both. For Smooch, the user ID is a random string. So the rationale for the conversion is:
* The input for the rake task is the workspace slug and the workspace tipline phone number
* For each Smooch subscription, find the Smooch user annotation from the `smooch_user_id` annotation field and from there get the user phone number from the `smooch_user_data` annotation field
* Replace the old UID by the new UID
* Output everything so a log of the execution can be saved
* Skip failures but log them
Reference: CV2-3211.
=> Adding a rake task to convert tipline subscriptions from Smooch to Cloud API

app/graph/mutations/team_mutations.rb, app/graph/types/team_type.rb, app/models/concerns/smooch_language.rb, app/models/team.rb, public/relay.json, test/models/team_test.rb
This adds a field get_language_detection to the graphql Team type and and language_detection field to the mutation and a setter to the Team model.
And changes logic in smooch_languages.rb to only have Alegre autodetect message if this new setting is enabled.
=> New get_language_detection field

config/routes.rb
This must be controled by a different layer, for example, DNS, load balancer, etc.
Reference: DEVOPS-417.
* Locally: Should be able to access just fine
* Production: There should be an authorization layer in front
=> Deleting access control to Sidekiq UI from the application side.

app/lib/check_permissions.rb, app/models/feed.rb, app/models/feed_team.rb, test/models/ability_test.rb, test/models/team_2_test.rb
* When there is no list associated with the shared feed, return an empty hash (`{}`) instead of null (`nil`)
* Expose feed permissions to the client, so UI components can be hidden/displayed accordingly
Reference: CV2-3209.
Automated tests should cover all changes here.
=> Minor changes for shared feed fact-checks view

app/models/feed.rb, test/models/feed_test.rb
Only require license to be present if feed is published.
Fixes: CV2-3193.
A unit test was implemented for that.
=> Allow feed licenses to be blank if feed is not published.

app/controllers/api/v1/graphql_controller.rb, config/initializers/02_sentry.rb
We were sending validation errors to Sentry, e.g: 'Project can't be blank'. We don't need to send those to Sentry, only to the client.
References: [cv2-3077](https://meedan.atlassian.net/browse/CV2-3077?atlOrigin=eyJpIjoiMzQ0MzVlZjhjNWZkNDJlYzg0ZDRmYzY2Y2JkMTU0YzIiLCJwIjoiaiJ9)
No, since we don't send errors from the development environment. I'll test this on QA.
=> cv2-3077: Validation errors should not be sent to Sentry, only to the client

app/resources/api/v2/feed_resource.rb, test/controllers/feeds_controller_test.rb
In the current Feed API, the scope of the search are all teams that belong to the feed whose `feed_id` is passed as a parameter to the endpoint. This commit adds another behavior: if `feed_id` is not present, use the current API key team as the scope for the search.
Reference: CV2-2814.
I implemented a unit test for this new supported case.
The previous use case (search based on `feed_id`) should still work the same way as before.
=> In the Feed API, search for published reports under the current API key team if `feed_id` parameter is not passed

app/resources/api/v2/feed_resource.rb
It should be an object, not an ID.
Fixes: CV2-2814.
Current tests should cover this.
=> Fixing how `Team.current` is set for feed API requests.

.rubocop.yml, app/models/bot/smooch.rb, app/models/concerns/smooch_resend.rb, app/models/concerns/smooch_turnio.rb, app/models/concerns/smooch_zendesk.rb, app/models/tipline_newsletter.rb, app/workers/tipline_newsletter_worker.rb, test/models/bot/smooch_3_test.rb, test/workers/tipline_newsletter_worker_test.rb
This branch implements a bunch of small improvements and fixes for tiplines, specially for the newsletter feature.
**Output more clear error message in log when newsletter can't be sent to a subscriber** (CV2-3372)
Make sure that all tipline providers (Smooch, On-Prem and CAPI) return a response object with attributes `code` and `body` for the `send_message_to_user` method. In the tipline newsletter delivery job, log successful deliveries and failed deliveries according to the `response.code`.
**When sending a newsletter, be sure that RSS content is not re-fetched for each subscriber** (CV2-3371)
"Cache" newsletter articles in memory, so, for the same `TiplineNewsletter` object loaded in memory, the method `articles` won't re-fetch static articles or articles from an RSS feed after the …
=> Tipline improvements and fixes

app/models/bot/tagger.rb
Currently Tagger bot only considers the title of a ProjectMedia. It should also consider the ProjectMedia’s description (only if different from the title) as well as the Claim description if present
References: CV2-3332
No additional automated tests, but all code is covered by existing tests. I've manually tested and verified the code is working as intended.
I copied the `pm.send(field) if !pm.nil? && pm.respond_to?(field)` pattern from https://github.com/meedan/check-api/blob/5ae2abffc4f954d4d4ed69d52c4ed0590f7f103c/app/models/concerns/alegre_similarity.rb#L96 , but I'm not actually 100% certain of how the `send` and `respond_to` methods work. I'd appreciate an extra check and any insights :pray:
=> CV2-3332 - Have TaggerBot consider multiple text fields for an item

pull_request_template.md
PRs should only include the ticket number and not include the links to our jira board, since it's not publicly accessible.
=> Remove ticket link from pull_request_template.md

docker-compose.yml
Update to use Postgres 12, the scope of this was to make sure the application works well locally in development mode and that tests pass in Travis and in the Check Web integration tests.
References: cv2-3307, cv2-3308
To make sure the application works locally I ran the seeds file, and went through the interface to see if everything was created and working correctly. I also ran the integration tests on check-web (successfully), following the instructions  in the confluence article (_How to run cross-application integration tests in CI on demand_).
_Not sure if this is important to pay attention during code-review, but I think it's important to add_
- Since we are upgrading between major versions (11 to 12) we have to either migrate the data to a new volume or delete the old volume. …
=> 3307 - Make sure api works with PostgreSQL 12

config/tipline_strings.yml
Fixing Telugu string interpreted as markdown by WhatsApp Cloud API.
=> Ticket CV2-3389: Fixing Telugu string interpreted as markdown by WhatsApp Cloud API

app/models/bot_user.rb
The response can be binary or contain invalid characters. It's enough if we log the response code.
Fixes CV2-3085.
I was not able to reproduce the original issue.
=> Do not log the response from external bot endpoint since it can be invalid

app/models/bot/alegre.rb, app/models/concerns/smooch_search.rb, app/models/concerns/team_rules.rb, test/models/bot/alegre_2_test.rb
Per CV2-2872 we have an issue where Chinese and Japanese sentences are counted as only one word simply because they are not space-separated. 
This ticket counts two Chinese characters as one word and 4-Japanese kana as one word. This is simple and let's us continue using regular expressions in Ruby without having to do anything more in-depth.
References: CV2-2872
Additional tests added
N/A
[CV2-2872]: https://meedan.atlassian.net/browse/CV2-2872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CV2-2872 - count Chinese and Japanese words better

app/models/monthly_team_statistic.rb, app/models/team.rb, db/migrate/20230711211928_add_newsletters_delivered_to_monthly_team_statistic.rb, db/schema.rb, lib/check_statistics.rb
Calculate the number of newsletters that were actually received by end users. So, if a newsletter is sent twice in a month, and the first one is received 2 of the 3 subscribers and the second is received by one of the 3 subscribers, who also received the first one, this means 3 newsletter deliveries.
Reference: CV2-3026.
Existing statistics tests should cover it.
=> Calculate number of newsletters actually delivered

app/models/tipline_newsletter.rb, test/models/tipline_newsletter_test.rb
It should be always possible to pause a newsletter. So, the validation to see if the scheduled time is in the past should only happen when publishing a newsletter (e.g., changing `enabled` from `false` to `true`).
Fixes CV2-3382.
An existing unit test was refactored to handle these two different situations.
=> Do not allow newsletter to be scheduled for the past - but only when publishing

app/models/bot/smooch.rb, app/models/concerns/smooch_zendesk.rb, app/workers/tipline_newsletter_worker.rb, test/models/bot/smooch_4_test.rb, test/models/bot/smooch_6_test.rb
Just be sure that we can extract the ID of a message that is sent through Smooch.
References: CV2-3298.
Existing tests should cover it.
=> Get ID of message sent through Smooch

app/models/concerns/smooch_menus.rb
Smooch supports [Reply Buttons (aka quick replies)](https://docs.smooch.io/guide/line/#capabilities) for LINE. Let's use them!
References: CV2-3396
Need help on how to test this!
- Etc.
=> CV2-3396: LINE supports Reply Buttons. Use them

app/models/concerns/project_media_private.rb
Apply a default rate limit for item creation even when the API key doesn't define it.
References: CV2-3395.
Existing tests should cover it.
Is 60 a good default value? It means 1 item created per second.
=> Default rate limit for API keys

app/models/concerns/smooch_capi.rb
Fix Sentry issue `TypeError: no implicit conversion of String into Integer` related to dig method
`dig` method triggered this error for the cases like this `{a:  []}.dig(:a, :b)` so I rescue the dig and return empty string
References: CV2-3276
- Etc.
=> CV2-3276: fix Sentry issue

app/models/bot/smooch.rb, test/models/bot/smooch_6_test.rb
If a tipline user is banned, do not even try to process their message.
Reference: CV2-3455.
An automated test was implemented.
=> Do not reply to banned tipline user.

.codeclimate.yml, .rubocop.yml, app/controllers/api/v1/webhooks_controller.rb, app/models/bot/smooch.rb, app/models/bot_user.rb, app/models/concerns/smooch_capi.rb, test/controllers/webhooks_controller_test.rb, test/models/bot_user_2_test.rb
First, allow core bots to ignore requests. By default, it's false, so no requests are ignored.
For WhatsApp Cloud API, ignore events of type "read" and "sent", since we just react to "delivered".
Reference: CV2-3453.
I added a functional test for this case.
=> Ignore some events from WhatsApp Cloud API which are not relevant.

Dockerfile, config/locales/ar.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fil.yml, config/locales/fr.yml, config/locales/id.yml, config/locales/pt.yml, config/locales/ro.yml, config/locales/ru.yml, config/locales/sw.yml, lib/tasks/transifex.rake
This commits make Dockerfile install the new Transifex CLI client that supports their current API and includes translation files freshly downloaded with it and deprecate rake tasks previously used a transifex gem to connect with Transifex.
References: CV2-3319
Downloaded and Uploaded strings with new cli client from within the container
The formatting on yml files changed due to the new client, but the result should be the same anyway.
=> CV2-3319: Install tx cli and updates strings downloaded with new client

lib/tasks/migrate/20230608215010_migrate_tipline_subscriptions.rake
Fallback to Smooch API when can't get phone number from local database when migrating from Smooch to CAPI.
Also:
* Skip subscriptions that were already migrated
* Skip subscriptions that are not from WhatsApp
Reference: CV2-3400.
I executed the rake task manually locally, where I have a Smooch tipline.
=> Fallback to Smooch API when can't get phone number from local database

app/models/bot/alegre.rb, test/models/bot/alegre_2_test.rb
We started using `get_number_of_words` in a new location and do not properly handle `nil` input that is possible there:
https://github.com/meedan/check-api/pull/1561/files#r1268906901
I've added a unit test to test for `nil` input to the function and fixed the function to return zero words for nil input. 
References: CV2-3476
Implemented new unit test and verified the test failed. Then fixed the issue and verified the new test passed. 
Who knew that `.to_s` was defined for the `nil` class in Ruby?!  Thanks for the pointer, @caiosba
=> CV2-3476 test for nil input to get_number_of_words

app/workers/tipline_newsletter_worker.rb
(1) Log total number of subscribers, not only the ones messaged successfully... this is just to make debugging easier.
(2) Cache delivery information for 7 days instead of 24 hours... this means that if the subscriber receives the newsletter 7 days after the delivery, we will know.
Just tested manually. But existing automated tests should cover.
=> A couple of small fixes for newsletters delivery.

app/models/tipline_newsletter.rb, test/models/concerns/smooch_capi_test.rb, test/models/tipline_newsletter_test.rb
Should shorten URLs in newsletter introduction only if the workspace setting on.
Fixes CV2-3502.
=> Should shorten URLs in newsletter introduction only if the workspace setting on

app/models/concerns/smooch_zendesk.rb, test/models/concerns/smooch_zendesk_test.rb
In the method used to send a message to a tipline user on Smooch we return a custom object when the message is blank, since it's not valid. But that message must follow the same format as a response from Smooch API. So, the `body` must return an object, not a string.
Reproduced in a unit test, included in this PR, which passed after the fix.
Fixes: CV2-3516.
TDD. I included a unit test.
=> The "body" of a response of an API call to Smooch with an empty message should be an object, not a string

lib/tasks/migrate/20230725053637_add_unmatched_to_project_medias.rake
Add a rake task to migrate existing data to `unmatched` field.
1. Got detach items from versions table
2. Got re-matched items in step 1 and exclude them from final ids
3. Update final ids using PG & ES queries  
References: CV2-3454
- Etc.
=> CV2-3454: add rake task to migrate existing data

lib/check_search.rb, test/controllers/graphql_controller_2_test.rb
Set `recent_added` as a default search in all cases.
References: CV2-3536
- Etc.
=> CV2-3536: set recent_added as default sort in all cases

app/models/project.rb, config/locales/en.yml, lib/sample_data.rb, test/models/project_test.rb
Adding a validation to be sure that a default folder/project can't be deleted.
Fixes CV2-3554.
I added a unit test for this case.
=> Make sure that a default folder (project) can't be deleted.

app/models/bot/smooch.rb
Output the `body` of the HTTP request response instead of the object. It helps with debugging.
Reference: CV2-3484.
I tried locally and it works. Since this is related to logging, automated tests don't help much. Existing tests should still pass.
=> Better logging for reports sent.

lib/tasks/migrate/20230727094535_remove_add_item_slack_notification.rake, lib/tasks/migrate/20230730055732_migrate_from_folders_to_lists.rake
Rake task to migrate folders to list through the following steps:
1. Create a workspace tag with the {title} of the original folder.
2. Tag items related to project with tag in step 1 using bulk import
3. Delete cached field `tags_as_sentence` to enforce creation on first hit
4. Update ES with new item tags using bulk operation
5. Update tags count related to created tag in step 1
6. Create a list with the {title} of the original folder and set the filter of the list to ‘tag is {title}’
After run the migration go to a workspace and check that each folder has a list with same name and tags filter.
- File FFFF, line LL: This refactoring does this and this. Is …
=> CV2-3287: add rake task to migrate folders to list

app/models/bot/smooch.rb
Do not crash when sending report if tipline `send_message_to_user` returns `null`, which is a valid scenario. For example, for the WhatsApp Cloud API, it can return `null` if text is blank (for a text message) or if the account ID can't be validated from the destination user UID. So, this commit is to just be safe for that case. The information will be in the log anyway (the failing line is a logging line).
Fixes: CV2-3576.
=> Do not crash when sending report if tipline `send_message_to_user` returns `null`.

lib/tasks/migrate/20230730055732_migrate_from_folders_to_lists.rake
Limit folder migration to teams with activity in the last year.
References: CV2-3287
I run the new query against live DB to make sure that I collect right teams.
=> CV2-3287: run migration against teams with activity in the last year

app/models/relationship.rb, lib/tasks/migrate/20230725053637_add_unmatched_to_project_medias.rake, test/controllers/elastic_search_10_test.rb, test/models/project_media_test.rb, test/models/relationship_test.rb
Update the `unmatched` field for both source and target items in relationships.
also updated rake task to fetch both items
References: CV2-3454
=> CV2-3454: handle unmatched for both source and target item

app/models/monthly_team_statistic.rb, db/migrate/20230809160826_add_whatsapp_conversations_to_monthly_team_statistic.rb, db/schema.rb, lib/check_statistics.rb, test/lib/check_statistics_test.rb
* This pull request adds a new data point for the statistics that are collected for the tipline: WhatsApp conversations
* This data point is collected using WhatsApp Insights API, so it's available only for WhatsApp tiplines, specifically, the ones that use the WhatsApp Cloud API
* For other tiplines, this data point should return null
* This data point is not available per-language, so the value should be the same for all languages
* This data point is cached, so it doesn't require multiple API calls when collecting this value per language, since this value is the same as per bullet point above
Reference: CV2-2903.
Unit tests were added.
=> New data point for tipline statistics: WhatsApp conversations.

app/graph/types/feed_team_type.rb
Our settings attributes rely on hitting a Method Missing exception to create the getter method - e.g. get_requests_filters for requests_filters. As a result, we can't use the method: helper on GraphQL classes, because they raise an error before the method is programmatically created.
We can get around this by explicitly defining a resolve method and calling the getter method on the object by name.
I also did a search to make sure that we weren't using the method attribute to access getters in the rest of the code base. We weren't.
References:CV2-3597
I haven't tested this or tried it locally - I don't have a local setup with shared feeds, wasn't sure of a good test, and am out of hours for the week but wanted to get this in quickly. I'm sorry!
n/a
=> Make resolve method explicit for settings attributes

app/models/annotations/dynamic.rb, app/models/concerns/smooch_search.rb, app/models/dynamic_annotation/field.rb, app/models/project_media.rb, app/repositories/media_search.rb, db/migrate/20230809103545_add_mapping_for_request_and_report_language.rb, db/migrate/20230809103545_add_mapping_for_request_language.rb, lib/check_search.rb, lib/tasks/data/project_media.rake, lib/tasks/migrate/20220214055345_add_mapping_for_report_fields.rake, lib/tasks/migrate/20230730055732_migrate_from_folders_to_lists.rake, test/controllers/elastic_search_10_test.rb, test/controllers/graphql_controller_7_test.rb
- Add ES mapping for request language.
- Allow user to filter by request language
- Rename ES methods by remove `build_search_` prefix  (i.e change `build_search_keyword_conditions` to `keyword_conditions`)
- Add ES mapping for report language
References:  CV2-2256
=> CV2-2256 more options for search language filter in check

app/lib/check_cached_fields.rb, app/models/concerns/project_media_cached_fields.rb, test/models/project_media_6_test.rb
Previously, all cached fields had the same expiration date, controlled by a global configuration key. This commit allows cached fields to define a custom expiration date by setting a `expires_in` key... when not defined, the global configuration is used.
This commit also uses this feature for the `ProjectMedia` `tags_as_sentence` cached field, by definiting a longer expiration date for it, since it's one of the most expensive fields.
Reference: CV2-3563.
I implemented a unit test for it.
We can set longer expiration dates for other fields later.
- [x ] I have performed a self-review of my own code
=> Allow cached fields to have a custom expiration date.

app/helpers/search_helper.rb, test/controllers/graphql_controller_3_test.rb
Add a new option `more than` for date range filter
References: CV2-3397
Go to list page and select date range filter then you can find a new option `more than`.
=> Cv2 3397 add option more than in date range

app/models/bot/alegre.rb, test/models/bot/alegre_2_test.rb
We do not introduce new settings. Rather we simply allow the existing settings alegre_model_in_use and text_similarity_model to be string or array
No change in behavior here. Rather previous backend work assumed that when we introduced multiple models on the front end we would have new variables `alegre_models_in_use` and `text_similarity_models` (note the "s" on each). Instead the actual front-end work simply reuses `text_similarity_model` and `alegre_model_in_use` that already exist. Therefore there is no need for the additional variables. I'm removing those and updating tests.
References: CV2-3438
Please …
=> CV2-3438: No models settings. Aligning this backend with the front-end work

app/graph/types/project_media_type.rb, app/models/concerns/project_media_getters.rb, lib/relay.idl, public/relay.json, test/models/project_media_5_test.rb
Add a new field `media_slug` to `ProjectMediaType` to get the original title for tipline items so it'll return empty strings for other items.
References: CV2-3469
=> CV2-3469: add media_slug field to ProjectMediaType

config/tipline_strings.yml
Just pushing vietnamese translations for tipline strings.
References: CV2-3565
This is not new functionality so I tested manually on the rails console:
```
irb(main):014:0> Bot::Smooch.get_string('privacy_statement', 'vi')
=> "Lời Cam Kết Bảo Mật"
```
Nothing really, unless you're fluent in vietnamese! :smile:
=> Add vietnamese translations for hardcoded bot strings

app/models/tipline_newsletter.rb, test/models/tipline_newsletter_test.rb
There are two lines of code that were not converted during the Ruby 3 upgrade because they were not covered by the tests. This commit adds tests to them and fixes them as well.
Fixes CV2-3617.
TDD. I added unit tests before the fix.
- [] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
=> Fixing two lines of code for Ruby 3.

lib/tasks/data/export_workspace_data.rake
This is an internal request, so, more details are in the ticket CV2-3600.
I executed the rake task locally for a couple of workspaces and the CSVs were generated as expected.
=> Adding a rake task to export workspace data filtering by status.

app/workers/tipline_newsletter_worker.rb
Don't pause the newsletter automatically when new content from RSS feed can't be loaded.
Reference: CV2-3370.
Existing tests should cover.
=> Don't pause the newsletter automatically when new content from RSS feed can't be loaded

config/initializers/field_validators.rb, test/models/dynamic_annotation/field_test.rb
Strip spaces from URLs when validating URL annotation field.
Fixes: CV2-3612.
TDD. I implemented a unit test.
=> Strip spaces from URLs when validating URL annotation field.

app/lib/smooch_nlu.rb, app/models/bot/smooch.rb, test/lib/smooch_nlu_test.rb
This branch makes a few improvements / tweaks to the NLU prototype.
1. It does not do an Alegre look up if options is nil. This occurs on the first message of a conversation, for example. In the future, we might want to consider all menu options across all workflows/languages, but the current fix simply doesn't return any option
2. It looks at all the Alegre results and chooses the menu option that has the highest scoring match and exists
This is a bug fix (otherwise we had issues where the top result was a menu option that didn't exist)  In the future we should consider a disambiguation menu for close options but for now I think this approach could work ok.
3. Log user intents in all cases, even when NLU is not enabled or options is nil
4. Add a method list_keywords to be used on the …
=> CV2-3650: Improve NLU option selection

config/environments/test.rb, config/initializers/active_record_extensions.rb, test/models/version_test.rb
This was reported by Sentry. I was able to reproduce in a unit test. The solution is to replace the manual adding of single quotes by calling `ActiveRecord::Base.connection.quote`.
Fixes: CV2-2910.
TDD. I added a unit test that was able to reproduce the exact same error as Sentry.
Can it have impact in other bulk-insert version operations? In order to be sure, I added a commit to enable PaperTrail for all tests (this commit is not going to be merged).
=> Fixing PostgreSQL syntax error when bulk-importing versions with quotes

app/lib/check_cached_fields.rb, lib/tasks/data/project_media.rake
- Refactor re-index nested field rake task to collect data using one query instead of iterate using single object.
so we collect either `comments`, `tags` or `requests` using one query to reduce the execution time
- Send object id to background job to update cached field instead of sending the whole object
References: CV2-2256
re-run `bundle exec rails check:project_media:sync_es_nested_field['field:requests']` locally against live db and done in minutes instead of days 
- Etc.
=> CV2-2256 refactor re-index nested field rake task

app/models/tipline_newsletter.rb, test/controllers/graphql_controller_9_test.rb, test/models/tipline_newsletter_test.rb
Skip some validation when newsletter.enabled is 0.
References: CV2-3177
=> CV2-3177: skip validation when newsletter enabled is false

app/graph/types/saved_search_type.rb, app/models/saved_search.rb, lib/relay.idl, public/relay.json, test/models/saved_search_test.rb
* Adding a method `items_count` to `SavedSearch` that returns the number of items in a list
* Essentially, it runs an ElasticSearch query that returns the number of items that match the filters defined by the `SavedSearch` instance
* Exposed in GraphQL as field `items_count` for `SavedSearchType`
Reference: CV2-3419.
Added a unit test for the new method.
=> Count number of items in a list.

app/lib/check_elastic_search.rb, app/models/concerns/project_media_cached_fields.rb, app/models/project_media.rb, app/repositories/media_search.rb, db/migrate/20230906054844_add_mapping_for_fact_check_published_on_field.rb, lib/check_search.rb, test/controllers/elastic_search_9_test.rb
1. Allow user to sort by fact-check published_at date.
References: CV2-3664
1. Go to workspace settings=> columns
2. Show Fact-check published at column
3. Go to list page and try to sort by Fact-check published at column
=> CV2-3664 allow column fact check published at to be sortable

app/models/bot/smooch.rb, test/models/bot/smooch_4_test.rb
Normalize tipline text before saving and query existing PG with trim and lower methods .
References: CV2-3623
implemented automated tests for different cases.
=> CV2-3623: normalize tipline text before saving

lib/url_rewriter.rb, test/lib/url_rewriter_test.rb
When URLs have unescaped Arabic characters, they are not extracted correctly. This happens not only with the library we use (`twitter-text`), but also with Ruby's `uri` library and `postrank-uri` gem:
```
irb(main):009:0> PostRank::URI.extract('https://fatabyyano.net/هذا-المقطع-ليس-لاشتباكات-حديثة-بين-الج/')
=> ["https://fatabyyano.net/"]
irb(main):010:0> URI.extract('https://fatabyyano.net/هذا-المقطع-ليس-لاشتباكات-حديثة-بين-الج/')
=> ["https://fatabyyano.net/"]
irb(main):011:0> Twitter::TwitterText::Extractor.extract_urls('https://fatabyyano.net/هذا-المقطع-ليس-لاشتباكات-حديثة-بين-الج/')
=> ["https://fatabyyano.net/"]
```
So, the fix here is to first escape URLs that contain Arabic characters before sending them to the URL extraction method when shortening URLs.
Fixes CV2-3690.
TDD. I …
=> Fixing URL shortening for URLs with Arabic characters.

lib/check_search.rb, test/models/saved_search_test.rb
I noticed it happening on live only for duplicated workspaces. When a list has a team task filter that doesn't have a valid ID, an exception would happen. I was able to reproduce that exception in a unit test.
The fix was to discard the team task filter if the ID is blank.
Fixes CV2-3742.
TDD. I was able to implement a unit test that reproduced the issue.
=> Do not crash when calculating number of items in a list that has an invalid team task filter

app/models/bot/fetch.rb, lib/tasks/data/fetch.rake
Adds a language parameter to `import_claim_reviews`, and passes that along to fetch, which already supports it.
References: 3589
I've tested the fetch side of this, and this update is simply a passthrough to allow for using that functionality.
Nothing particularly exciting here.
=> CV2-3589 add language as a parameter for import_claim_reviews

app/models/bot_user.rb
Just fixing a syntax error.
Fixes CV2-3626.
I was able to reproduce in Rails console but not in a test.
=> Fixing how Sentry is notified when an external bot can't be called.

app/models/annotations/dynamic.rb, test/controllers/graphql_controller_3_test.rb, test/models/media_test.rb
PostgreSQL doesn't support null characters in a JSON column, so these characters need to be removed before storing.
Fixes CV2-3582.
TDD. I added a unit test for this case.
=> Fixing "PG::UntranslatableCharacter" error when storing some Pender data annotations

app/models/concerns/smooch_team_bot_installation.rb, db/migrate/20230914152816_mark_tipline_bot_as_default.rb, db/schema.rb, test/test_helper.rb
* Set `default` as `true` for the Smooch Bot, this way it's installed automatically for all new workspaces
* Bump to v2 automatically when Smooch Bot is installed
Refences: CV2-833 and CV2-3558.
Existing tests should pass. When running the application, this can be tested this way:
* Create a new workspace
* Go to the "Tipline" tab: It should be installed and display the v2 settings UI
=> Automatically install tipline in v2 when workspace is created.

app/models/team.rb, app/models/tipline_newsletter.rb, app/models/tipline_resource.rb, app/workers/tipline_newsletter_worker.rb, test/workers/tipline_newsletter_worker_test.rb
Only WhatsApp requires template messages. The fix here is to use the regular message type when sending newsletters to non-WhatsApp subscribers.
Fixes CV2.3646.
I added a unit test for this case.
Nothing in particular. I renamed a constant for clarity and also removed two lines of code not related to this fix but not required anymore.
=> Fixing: Media headers should work for non-WhatsApp tiplines.

app/models/workflow/concerns/dynamic_annotation_field_concern.rb, test/models/dynamic_annotation/field_test.rb
Ignore status changing permission check if previous value is not a string. Fixes CV2-3764.
TDD. I was able to reproduce the bug in a unit test.
=> Ignore status changing permission check if previous value is not a string

app/graph/types/query_type.rb
This is temporarily needed in order to bypass Relay compat cache. Shouldn't be needed once the client is completely migrated to Relay modern.
Fixes CV2-3775.
Existing tests should cover this change.
=> Use "random" argument passed to GraphQL team query.

.gitlab-ci.yml, production/bin/run_command.sh, production/bin/run_migration.sh
This change eliminates references to the deprecated GITHUB_TOKEN variable in ECS task definitions.
References: DEVOPS-466
I tested a QA deployment from this branch to verify startup behavior. This included migration tasks.
=> Feature/devops 466 remove GitHub token

app/graph/mutations/tipline_message_mutations.rb, app/graph/types/dynamic_annotation_field_type.rb, app/models/concerns/smooch_messages.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_10_test.rb
For now the only use case is to allow custom messages to be sent in reply to previous user requests. So, this PR changes the `sendTiplineMessage` mutation... instead of requiring `uid`, `timestamp` and `language`, it just requires the ID of the request (`smooch` annotation).
References: CV2-3643 and CV2-3677.
There are two automated tests that were updated.
=> Changing `sendTiplineMessage` mutation so that it requires only one argument besides the message

.travis.yml, test/test_helper.rb
When running locally we might not want the tests to retry, to do this
we would need to comment out the retry line. We want to make this easier
on the developer
Converting the env variable to an integer because ENV[] on ruby returns a string
https://ruby-doc.org/core-3.0.0/ENV.html
Set TEST_RETRY_COUNT to 3 on Travis because we were using the default
before (which is 3)
https://www.rubydoc.info/gems/minitest-retry/
References: 3718
Changed a test to make it fail.
Ran tests locally without setting TEST_RETRY_COUNT, test failed and didn't retry.
Set the env var inside the container (export TEST_RETRY_COUNT=3) and ran the tests again, it retried 3 times.
=> 3718 – Update how we retry tests

app/models/bot/smooch.rb, app/models/tipline_message.rb, app/workers/smooch_tipline_message_worker.rb, test/models/tipline_message_test.rb
Silently ignore duplicate errors when saving tipline messages. We don't need to raise an exception for a legit validation error. A duplication error happens when a tipline message has the same ID and state.
I implemented a unit test for this.
- x ] My changes generate no new warnings
=> Silently ignore duplicate errors when saving tipline messages

app/models/concerns/smooch_resources.rb
Smooch doesn't support video. So we need to convert the type from "video" to "file" before calling the Smooch API.
Fixes CV2-3797.
Since this touches an external service (the Smooch API), automated tests wouldn't help much here. So I tried it locally and works fine.
=> Fixing video/audio tipline resources for tiplines hosted in Smooch.

app/models/bot/smooch.rb, config/config.yml.example, test/models/bot/smooch_6_test.rb
When a tipline user sends a long text message or a file, jump right away into the "are you ready to submit" state.
Reference: CV2-2326.
I added two new unit tests for this feature.
=> Tipline submission shortcuts

app/models/bot/smooch.rb, config/config.yml.example, test/models/bot/smooch_6_test.rb
Changing configuration key name and default value for tipline submission shortcut
Reference: CV2-2326.
=> Changing configuration key name and default value for tipline submission shortcut

app/graph/types/team_type.rb, test/controllers/graphql_controller_9_test.rb
Paginate tipline message .
References: CV2-3776
Implemented automated tests to query tipline messages using pagination .
=> CV2-3776: paginate tipline messages

app/models/blocked_tipline_user.rb, app/models/bot/smooch.rb, app/models/concerns/smooch_blocking.rb, app/models/concerns/smooch_capi.rb, db/migrate/20231002202443_create_blocked_tipline_users.rb, db/schema.rb, lib/sample_data.rb, test/models/blocked_tipline_user_test.rb, test/models/concerns/smooch_capi_test.rb
If WhatsApp Cloud API reports an error of type "pair rate limit hit" when we try to send a message to a WhatsApp user, block that user automatically, so we don't need to answer them again.
It helps with SPAM and abuse.
Reference: CV2-3489.
I added a unit test for this feature.
=> Block WhatsApp user if WhatsApp API reports a "pair rate limit hit" error

lib/url_rewriter.rb, test/lib/url_rewriter_test.rb
We have to check if the URL itself contains Arabic characters, not only the full text where the URL is in.
Fixes: CV2-3814.
TDD. I added a unit test that was able to reproduce the issue. The test passed after the fix was implemented.
=> Fixing URL shortening for Arabic URLs.

app/models/bot/smooch.rb, app/models/concerns/smooch_messages.rb, test/controllers/graphql_controller_10_test.rb, test/controllers/graphql_controller_3_test.rb, test/models/bot/smooch_4_test.rb, test/models/bot/smooch_6_test.rb
In that case, the request should still be saved, but associated with the workspace, not with a text media.
Fixes CV2-3784.
I implemented two new unit tests for this.
=> Do not submit as unconfirmed media a text with just a few words.

app/graph/mutations/graphql_crud_operations.rb, test/controllers/graphql_controller_4_test.rb
Include `updated_objects` in `bulkProjectMediaMarkRead` return fields
References: CV2-2897
Added a unit test.
- Etc.
=> CV2-2897: fix return updated_objects for bulk read action

app/models/concerns/tipline_content_image.rb, config/config.yml.example, public/tipline-content-template.html
Previously, some tipline resources and newsletters header images would be cropped unless they had some specific aspect ratio. This PR fixes this, by always resizing the images while keeping aspect ratio and never cropping them.
Fixes: CV2-3356.
I'm open for better alternatives to the one I implemented.
=> Don't crop header images for tipline resources and newsletters.

app/graph/mutations/graphql_crud_operations.rb
Raise error when trying to save a null object through GraphQL update mutation.
Reference: CV2-3826.
=> Raise error when trying to save a null object through GraphQL update mutation

app/models/bot/smooch.rb, app/models/concerns/smooch_menus.rb, app/models/concerns/smooch_search.rb, test/models/bot/smooch_6_test.rb
For WhatsApp tiplines, instead of asking for feedback for all the results, ask for feedback individually by appending a thumbs-up button to each result. The timeout case is also individual as part of this change.
Existing automated tests should still pass for non-WhatsApp tiplines, since nothing changed there. New automated tests were implemented for the new cases.
=> Individual feedback for tipline search results on WhatsApp

app/graph/types/project_media_type.rb, app/models/concerns/project_media_cached_fields.rb, app/models/concerns/smooch_search.rb, app/repositories/media_search.rb, db/migrate/20231008074526_add_mapping_for_tipline_search_results_fields.rb, db/schema.rb, lib/relay.idl, public/relay.json, test/models/bot/smooch_7_test.rb
- Store number of tipline requests (positive_tipline_search_results_count & tipline_search_results_count)
- Expose cached field to graphql ProjectMediaType
References: CV2-3779
- Etc.
=> CV2-3779: add tipline requests cached fields

app/models/concerns/smooch_search.rb
Limit tipline search fields and use the following fields:
- title
- description
- fact_check_title
- fact_check_summary
- extracted_text
- url
- claim_description_content
Sort results by recent activity
References: CV2-3785
Make sure that existing tests passed.
=> CV2-3785: limit tipline search fields and sort by recent activity

lib/tasks/migrate/20231003085827_unpublish_items_without_fact_check.rake
Add  two rake tasks:
1. `check:migrate:export_published_items_without_fact_check`: export published items without fact-check to CSV file
2. `check:migrate:set_fact_check_for_published_items`: create fact-check using report data for published items
References: CV2-3771
Tested both rake tasks locally using a live DB dump.
1. `check:migrate:export_published_items_without_fact_check`:  Done in 19 minutes.
2. `check:migrate:set_fact_check_for_published_items`: Done in 36 minutes.  for a workspace contains **2586 items**
=> CV2-3771: export published items without fact check to CSV file and copy reports to fact check

app/graph/types/team_type.rb, app/graph/types/tipline_message_type.rb, app/models/bot/smooch.rb, app/models/concerns/smooch_menus.rb, app/models/concerns/smooch_messages.rb, app/models/concerns/smooch_resources.rb, app/models/concerns/smooch_search.rb, app/models/tipline_message.rb, app/models/tipline_newsletter.rb, app/workers/tipline_newsletter_worker.rb, lib/relay.idl, public/relay.json, test/models/tipline_message_test.rb
* Set `event` for tipline messages that are sent
* Return media URL for tipline messages on GraphQL API
* Sort tipline messages by `sent_at` instead of ID  (sometimes messages in the history were out of order… this is because the sorting on the backend was by ID, but the messages are created in background, so the ID wouldn't guarantee the order)
Reference: CV2-3853.
I added one new unit test, for `media_url`. Other changes should be covered by existing tests.
=> A few fixes/changes for `TiplineMessages` API

app/models/concerns/smooch_messages.rb, app/models/tipline_message.rb, test/models/bot/smooch_test.rb
* Return `media_url` for Smooch WhatsApp template
* Set tipline messages with event `status_change`
Reference: CV2-3853.
Existing tests should still work.
=> A couple of small fixes for the conversation history.

app/models/tipline_message.rb, config/config.yml.example, test/models/tipline_message_test.rb
"X" is defined by a configuration key but has a default value.
Reference: CV2-3860.
I added a unit test for different cases.
=> Block tipline users when they send more than X messages in 24 hours.

app/graph/mutations/tipline_messages_pagination.rb, app/graph/types/query_type.rb, app/graph/types/team_type.rb, app/graph/types/tipline_message_type.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_9_test.rb
Currently to get the cursor we should retrieve all messages and the cursor is the index of the item not item ID so I implement a custom pagination to override current behavior for cursor to use item id instead of index of the item so I can retrieve a cursor for a specific message
so I did the following:
- Add a cursor to TiplineMessageType so you can query a cursor for specific message
- Override `cursor_for` method in a custom class
- Override  `load_nodes` method in a custom class
References: CV2-3776
- File FFFF, …
=> CV2-3776: implement a custom pagination for TiplineMessageType

lib/tasks/migrate/202306040000_add_tagger_bot_user.rake
There is a rake task to add the Tagger bot. I updated the bot name and description in that rake task and also changed it so it updates the bot if it already exists.
Reference: CV2-3877.
Manually (it's a rake task). Run the rake task and it should either create the bot or update the bot.
=> Update tagger bot name and description and make the rake task idempotent

app/models/feed.rb, test/models/feed_test.rb
Otherwise, we get a violation when deleting the feed.
Reference: CV2-3801.
@danielevalverde tested this :)
I added a unit test too.
=> Delete `FeedTeam`'s when deleting a `Feed`.

app/models/bot/smooch.rb, app/models/concerns/smooch_messages.rb, app/models/relationship.rb, db/migrate/20231023002756_update_relationship_target_id_index.rb, db/schema.rb, test/models/bot/smooch_6_test.rb, test/models/relationship_2_test.rb, test/models/relationship_test.rb
Previously: When users received tipline search results and voted on them as relevant or chose not to vote, a request was generated and linked to the items returned in the search results. No new media or items were created.
Now: When users receive tipline search results and cast votes on them as relevant or abstain from voting, a request is generated and associated with newly created media and items. These new items are linked to the search results through suggestion relationships, unless identical media already exist, in which case the previous behavior remains unchanged.
Additionally:
- To prevent redundancy, refrain from sending reports to users when their suggestions are accepted, as they have already received the report through the search results.
- When confirming a match, delete any …
=> Change how tipline search result feedback is stored

app/controllers/concerns/facebook_authentication.rb, app/models/concerns/smooch_menus.rb, app/models/concerns/smooch_resources.rb
Mostly for Instagram. Just increasing one second before sending the main menu after greetings and resources. Also adding one more permission required by Instagram.
Fixes CV2-3727.
To be tested on QA, because it requires a real connection to a Instagram profile.
=> Trying to avoid menu being sent before resources and greeting.

app/graph/types/feed_type.rb, app/graph/types/query_type.rb, app/graph/types/team_type.rb, app/models/ability.rb, lib/relay.idl, public/relay.json, test/models/ability_test.rb
- Adding `feed_teams` connection to `Feed`
- Adding `feed_team` (get by database ID) to the root query type
- Allow feed owner to delete a `FeedTeam`
Reference: CV2-3900.
Automated tests.
=> Exposing new fields on GraphQL API for shared feeds invitations

app/lib/smooch_nlu.rb, app/lib/smooch_nlu_menus.rb, app/models/bot/smooch.rb, app/models/concerns/tipline_resource_nlu.rb, config/config.yml.example, config/tipline_strings.yml, test/lib/smooch_nlu_test.rb, test/models/bot/smooch_6_test.rb
If NLU identifies that two options are very similar, present both to the user and let them choose.
Reference: CV2-3710.
Automated tests.
=> Tipline: NLU disambiguation.

db/seeds.rb
This is the first part of ticket 3884.
We were creating claim items with 1 request and other types of items with 0. We want to change that, we want to:
- create enough requests so that we trigger pagination (creating 15 does that)
- keep generating some items with 1 request (we want some variation)
- add requests to different types of items (claims, links, audio, image and video)
References: 3884
By running the seeds script inside the container either adding to a user or creating a new one.
=> 3884 – Improve seeds script: create more Tipline requests

app/models/concerns/team_duplication.rb, test/models/team_test.rb
Set the default language when duplicate existing workspace.
References: CV2-3940
- Etc.
=> CV2-3940: fix default language for duplicated team

app/mailers/feed_invitation_mailer.rb
Just changing the slug for the shared feed invitation url in the mailer to match the work done in https://github.com/meedan/check-web/pull/1730
=> Changing the shared feed invitation email url to match check-web

app/graph/types/query_type.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_12_test.rb
A couple of updates for the GraphQL root query fields `feed_team` and `feed_invitation`:
* `feed_team`: Adding the ability to query by `feedId` and `teamSlug` in addition to `id`
* `feed_invitation`: Adding the ability to query by `feedId` (and then the current logged in user email is assumed) in addition to `id`
Reference: CV2-3801.
Automated tests were implemented for all cases.
=> A couple of updates for the GraphQL feed API

app/models/concerns/smooch_messages.rb, lib/check_statistics.rb, test/lib/check_statistics_test.rb
- Graceful error when cannot send message to tipline user
- Fixing how number of tipline newsletters delivered are calculated
References: CV2-3904 and CV2-3948.
TDD. I added a unit test.
=> A couple of bug fixes

db/seeds.rb
We are now creating a feed with published items (randomized verified and false items).
Important: It can take a bit of time for the items to appear in the published list and on the feed (and even when they appear, the count on the published list stays at 0)
References: 3384
Ran seed script, created and added to user.
1. When verifying and publishing fact checks we get a lot of logs, I couldn't figure out how to pause logging for the seed file.
2. I decided to create everything with channel: Whatsapp, instead of duplicating everything
I will update the documentation to include:
1. running with elasticsearch_log set to 0, so it doesn't output the logs
a. `elasticsearch_log=0 bundle exec rake db:seed`
3. Things might take sometime to update in the UI, but if there are any issues with the …
=> 3884 – Improve seeds: create feed

db/seeds.rb
We now add an item of each media type with multiple medias – which means it has many confirmed relationships. We do this so the center column on the item page has a good size list to check functionality against. 
As per Brian’s [request](https://github.com/meedan/check-api/pull/1722#issuecomment-1798729043)
References: 3993
Ran the seeds script to create and add data.
=> 3993 – Improvements for Check API seed script: Add an item with multiple medias

app/graph/types/feed_type.rb, app/lib/check_permissions.rb, app/models/ability.rb, test/models/ability_test.rb, test/models/team_2_test.rb
- Expose `FeedTeam` and `FeedInvitation` permissions
- Invalidate team permissions cache
- Do not return feed invitations to users that are not admins in the feed creator organization
Reference: CV2-4027.
Automated tests.
=> Small changes to feed permissions

app/mailers/feed_invitation_mailer.rb, app/models/bot/keep.rb, app/models/feed_invitation.rb, test/mailers/feed_invitation_mailer_test.rb, test/models/bot/keep_test.rb
Do not crash if link metadata contains invalid JSON when parsing Keep request.
References: CV2-3966.
TDD. I added a unit test that reproduced the bug.
=> Do not crash if link metadata contains invalid JSON when parsing Keep request

app/models/feed_team.rb, test/models/feed_team_test.rb
When a user leaves a feed, any previous feed invitation they received for that feed should be deleted.
This way, they can be invited again in the future.
Fixes: CV2-3802.
I added a unit test for this case.
=> When a user leaves a feed, any previous feed invitation they received for that feed should be deleted.

app/models/ability.rb, app/models/feed_invitation.rb, lib/check_basic_abilities.rb
If a user declines a feed invitation, they can be invited again.
In practice, this means really deleting the invitation from the database when it's rejected.
Fixes CV2-3802.
Existing unit tests will be fixed to cover this.
=> If a user declines a feed invitation, they can be invited again.

app/graph/mutations/tipline_messages_pagination.rb, app/graph/types/team_type.rb, app/graph/types/tipline_message_type.rb, test/controllers/graphql_controller_9_test.rb, test/models/feed_invitation_test.rb
Until conversation history pagination is implemented in Check Web, Check API must return the latest messages. This PR is for that. Once pagination is implemented in Check Web, this PR should be reverted.
References: CV2-3776 and CV2-3703.
=> Reverting conversation history sort order until pagination is implemented on the frontend side

app/lib/smooch_nlu.rb, app/models/bot/alegre.rb, app/models/concerns/alegre_similarity.rb, app/models/concerns/alegre_v2.rb, app/models/request.rb, app/workers/reindex_alegre_workspace.rb, spec/pacts/check_api-alegre.json, test/contract/alegre_contract_test.rb, test/controllers/elastic_search_9_test.rb, test/controllers/feeds_controller_test.rb, test/controllers/graphql_controller_8_test.rb, test/controllers/reports_controller_test.rb, test/lib/smooch_nlu_test.rb, test/models/bot/alegre_2_test.rb, test/models/bot/alegre_3_test.rb, test/models/bot/alegre_test.rb, test/models/bot/alegre_v2_test.rb, test/models/bot/smooch_6_test.rb, test/models/request_test.rb, test/workers/reindex_alegre_workspace_test.rb
This work introduces the beginning of a rewrite of the check-api/alegre integration. We do this by using the sync endpoint on alegre, which does an entire store/search loop using presto within a single query. We will continue that pattern through all other modalities, so this ticket is important in conceptually considering the structure of the new code, which, once all modalities are covered, will replace the existing monolith of code that is the check-api/alegre integration.
References: 3828
I've added what I believe are complete, well documented, and representative unit tests for the entire new set of code. I think that its passing 100% right now, but will make sure if its not!
This code will eventually replace the entire check-api/alegre integration. This should be scrutinized and we …
=> CV2-3828 First pass on check api integration updates for audio on alegre

app/models/concerns/smooch_messages.rb, app/models/concerns/smooch_search.rb
This PR fixes two things:
* A Sentry error that was raised when a report is null
* A race condition that happens when saving media related to tipline search results
Reference: CV2-4063.
=> Fixing Sentry error and avoiding race condition.

app/models/concerns/smooch_search.rb, app/resources/api/v2/report_resource.rb, lib/check_search.rb
I missed a few paths when changing everything to POST-only - this is a small tweak to accommodate.
References: 4069
I believe this shouldn't change any tests, since all previous tests worked fine and we deployed off that, but will fix if it comes up!
Triple check I got the rest of these?
=> CV2-4069 fix a few broken paths that are now mistakenly trying to add items rather than search for them

app/models/bot/smooch.rb, test/models/bot/smooch_2_test.rb
Expand the current condition so that reports are not sent for relationships saved by not only by Smooch Bot, but also by Alegre Bot. The rationale is that medias are created only through tipline requests, so they already received search results and gave feedback, so they don't need to receive additional reports.
Fixes CV2-4068.
A fixed a test that broke because of this change.
=> Do not send a report to a tipline user for relationships created by Alegre Bot

app/models/feed.rb, test/models/feed_test.rb
Should not allow feed to be deleted if it still has collaborators.
Fixes CV2-3952.
Unit tests.
=> Should not allow feed to be deleted if it still has collaborators.

app/graph/mutations/project_media_mutations.rb, app/graph/types/project_media_type.rb, app/models/concerns/project_media_cached_fields.rb, app/models/concerns/project_media_getters.rb, app/models/project_media.rb, db/migrate/20231210015830_add_custom_title_fields_to_project_media.rb, db/schema.rb, lib/relay.idl, public/relay.json, test/models/project_media_6_test.rb
Items (`ProjectMedia`'s) can now have custom titles. Summary of changes:
- Added fields `custom_title` and `title_field` to the `ProjectMedia` model (new columns for the `project_medias` table in PostgreSQL)
- Expose these fields in GraphQL API for `ProjectMedia` mutations and type
- Changed the logic of the item `get_title` methodIf there is a value for title_field, use that field for the title
- Updated the events that trigger an update for the `title` cached field
Reference: CV2-3983.
Automated tests were implemented for all these new features.
=> Item custom title feature

app/models/bot/alegre.rb, app/models/concerns/alegre_v2.rb, test/contract/alegre_contract_test.rb, test/controllers/elastic_search_9_test.rb, test/models/bot/alegre_2_test.rb, test/models/bot/alegre_v2_test.rb
Updates check api / alegre integration to use the sync endpoint in lieu of the old / sunsetting on-alegre fingerprinting, and instead route through presto
References: 4044
Most of the work should just be adding test coverage for different states of image uploads - the code itself should be a one liner.
=> Add initial tests for image via sync endpoint

app/models/concerns/project_media_getters.rb, app/models/project_media.rb, test/models/project_media_6_test.rb
Exposing `team_avatar` in item's `feed_columns_values` method.
Reference: CV2-3989.
I added a unit test to be sure that we won't fall into a N + 1 queries problem.
=> Exposing `team_avatar` in item's `feed_columns_values` method.

app/graph/types/project_media_type.rb, lib/relay.idl, public/relay.json
Exposing new GraphQL field `suggestions_count` in `ProjectMediaType`.
Reference: CV2-3988.
The underlying method is already unit-tested.
=> Exposing new GraphQL field `suggestions_count` in `ProjectMediaType`.

db/seeds.rb
We are improving feed invitation and inviting a new user who is part of 2 different workspaces to a shared feed.
The new user's workspaces are both empty.
References: 3995, 3884
By running the seed's script.
- Once this is merged, I'll update the confluence page.
- I split the big data hash we had with everything into smaller groups (2 hashes and 1 array): data_users, data_items and data_imported_fact_checks. I thought this made it easier to reason with.
=> 3995 – Invite a new user to a shared feed

app/graph/mutations/project_media_mutations.rb, app/models/project_media.rb, lib/relay.idl, public/relay.json
When an item is replaced by another one (for example, when accepting a suggestion to an imported item, which has no media), in some cases we don't want a report to be sent since the tipline users may have already received those through search results. This PR adds a `skip_send_report` argument to the `ProjectMediaReplace` mutation, which is `false` by default (so, same as current behavior) but that when `true` doesn't send a report.
Reference: CV2-4132.
Existing tests should cover this. The default behavior is the same.
=> Exposing a new argument `skip_send_report` for the mutation `ProjectMediaReplace`

.gitlab-ci.yml
replaces image used in ci with gitlab-provided aws-base image and updates aws ecr command to reflect syntax used in new awscli version. fixes gitlab issue around installing awscli v1
=> use gitlab-provided aws base image for ci build steps

db/seeds.rb
`is_admin` means the user is a super admin. Which we don’t want.
We removed `is_admin` attributes from the seed script.
References: 4151, 4122 ([PR #1781](https://github.com/meedan/check-web/pull/1781#issuecomment-1867805893))
Ran the seeds.
=> 4151 – Remove is_admin from user creation in seeds script

app/models/concerns/project_association.rb
While working on the "edit title" feature (see referenced ticket for details), I noticed that the `title` was not updated in ElasticSearch when a `ProjectMedia` was updated. This PR fixes this. Only `title_index` was being updated.
Reference: CV2-3986.
Manually, using the edit title feature:
- Type a custom title for an item
- Search by that custom title
- You should find the item
=> Bugfix: Title should be updated in ElasticSearch when item is updated

app/models/annotations/task.rb, test/controllers/graphql_controller_7_test.rb, test/models/project_media_test.rb
The latest refactoring surfaced some uncovered lines. This PR adds a test for part of the code that was left untested and also deletes code that is not needed anymore.
All tests should pass and the code should be 100% covered.
=> Reviewing uncovered lines

app/models/concerns/project_media_cached_fields.rb, app/models/concerns/project_media_getters.rb, test/models/project_media_6_test.rb
If an item has the title field set to claim title or fact-check title and one of those is deleted, then in order to avoid that the title gets blank, the title field is set to "custom_title" and the value is set to the previous title value.
Reference: CV2-3986.
This is a very edge case so I didn't add a specific test for it. I'm mostly concerned about keeping the previous behavior, so existing tests should pass.
=> Fallback to custom title with previous value if item title gets blank.

app/graph/mutations/feed_mutations.rb, app/graph/types/feed_type.rb, app/models/feed.rb, db/migrate/20240107223820_add_data_points_to_feeds.rb, db/schema.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_12_test.rb, test/models/feed_test.rb
* Adding a new column/field `data_points` to the `Feed` model, which is an array of integers, empty by default
* Validate that it contains allowed values
* Expose `data_points` on GraphQL API, for feed type and create mutation
* Automated tests added
References: CV2-4034 and CV2-3923.
Unit and functional tests added for all features here.
=> Adding a `data_points` field to `Feed` and exposing it on GraphQL API

app/models/bot/alegre.rb, app/models/concerns/alegre_similarity.rb, app/models/concerns/alegre_v2.rb, app/models/concerns/smooch_search.rb, app/resources/api/v2/report_resource.rb, lib/check_search.rb, test/models/bot/alegre_2_test.rb, test/models/bot/smooch_6_test.rb, test/models/bot/smooch_7_test.rb
Tipline image search, and actually other places of the code, were still hitting a deprecated path of Alegre API, `:type/similarity/search`, while (AFAIU) it should be `/similarity/sync/:type` (for audio and image, only). This PR fixes it by creating a `get_items_with_similar_media_v2` method that hits the new endpoint for image and audio and the old endpoint for video and text. This is not the ideal and I also noticed another problem, but I added a couple of `#FIXME`'s to the code to handle that later.
Reference: CV2-4044.
Existing tests should cover this, they broke as expected and I fixed them.
I added a couple of `FIXME`'s to the code, please check them.
=> Fixing Alegre path for tipline image search.

app/models/monthly_team_statistic.rb, db/migrate/20240114024701_add_whats_app_user_and_business_conversations_to_monthly_team_statistic.rb, db/schema.rb, lib/check_statistics.rb, test/lib/check_statistics_test.rb
Collecting two new data points for workspace tipline statistics: "WhatsApp Service Conversations" and "WhatsApp Business Conversations".
Reference: CV2-4121.
A unit test was implemented.
=> Collecting two new data points for workspace tipline statistics

config/initializers/report_designer.rb
Use item status instead of report status label in the introduction when sending a report.
Fixes: CV2-4180
Existing tests should cover this. This is an edge case.
=> Use item status instead of report status label in the introduction when sending a report

app/models/concerns/alegre_v2.rb, test/models/bot/alegre_v2_test.rb
In `Bot::Alegre.get_similar_items(pm)` (i.e. the original similarity matching function in alegre), we run a conditional check of `!Bot::Alegre.should_get_similar_items_of_type?('master', pm.team_id) || !Bot::Alegre.should_get_similar_items_of_type?(type, pm.team_id)` - this effectively checks the team to ensure that similarity searching is enabled at all, and specifically, similarity searching for that media modality is enabled. In the massive simplification/refactor, we lost that condition for V2. Adding that back in at the point of search, which should be all that's needed to get Alegre back to spec.
References: CV2-4223
Strange that we didn't have a unit test for this - I will be writing one for this test case, but I want to see test results for just the change itself with no …
=> CV2-4223 readd condition for checking if we should even search for the type

Gemfile, Gemfile.lock, app/models/user.rb, config/application.rb, config/config.yml.example, config/environments/development.rb, config/environments/test.rb, config/initializers/devise.rb, config/initializers/rack_attack.rb, db/migrate/20240115101312_add_lockable_to_devise.rb, db/schema.rb, test/controllers/sessions_controller_test.rb, test/lib/check_rack_attack_test.rb
Add rate limiting to login requests using rack-attack. As a starting point, we are setting a limit of 5 request per minute to /api/users/sign_in.
Tested by confirming that:
- Repeated calls to /api/users/sign_in will result in a `429: Too many requests` error. This can be validated using both the check web application or an api client. . The default limit is 10 requests per minute.
- Repeated calls to /api/graphql will result in a `429` error as well. The default limit is 100 requests per minute.
=> Add rate limiting to login requests

app/models/bot/smooch.rb
The tipline bot should react to the Smooch trigger that happens when a connected Instagram account is mentioned in a story. This is required in order for the Facebook app to be approved.
Fixes: CV2-3727.
Manually. When a public Instagram account mentions in a story an Instagram account that is connected to a Check tipline, the tipline bot should respond.
=> React to the Smooch trigger related to story mention.

test/controllers/sessions_controller_test.rb
There is a failing test in SessionsController where travel_to is behaving differently in CI vs dev. This PR contains a fix for it.
In https://github.com/meedan/check-api/pull/1777, a new test was introduced in SessionsControllerTest, but it is bugging out in CI.
Verified that the test passes successfully.
Run: `rails test test/controllers/sessions_controller_test.rb:88`
=> Fix failing test in SessionsControllerTest

app/lib/smooch_nlu.rb, app/lib/smooch_nlu_menus.rb, app/models/bot/smooch.rb, app/models/concerns/tipline_resource_nlu.rb, config/config.yml.example, test/lib/smooch_nlu_test.rb, test/models/bot/smooch_8_test.rb, test/models/bot_user_2_test.rb
**Description**
As part of the ongoing development of the Natural Language Understanding (NLU) feature, it has been identified that the current implementation of the text similarity service lacks robust handling of concurrent requests. The absence of efficient concurrency management may lead to degraded performance and potential service disruptions when multiple requests are made simultaneously.
**Issue**
The primary issue is the lack of a concurrency control mechanism, resulting in potential race conditions and suboptimal response times during peak usage periods. It is imperative to enhance the system's capability to handle concurrent requests seamlessly to ensure a smooth and responsive user experience.
**Objective**
The goal of this ticket is to implement rate limits as a concurrent …
=> NLU Rate Limits

config/initializers/devise.rb
Currently, we are using an unlock strategy of `:both`, which allows both time based unlocking and email based unlocking. This leads to an email being sent to the user when their account is locked, which us currently not intended.
Confirmed that all tests are passing
Ensure that locking and unlocking of user accounts works as expected.
=> Change devise unlock strategy from `:both` to `:time`

test/controllers/sessions_controller_test.rb
Confirming triggers the DeviseMailer.invitation_instructions job, which isn't intended, and leads to failed jobs such as
https://app.travis-ci.com/github/meedan/check-api/jobs/617009352#L2868
- Etc.
=> Don't confirm user when testing account lockout

app/models/concerns/alegre_v2.rb, test/models/bot/alegre_v2_test.rb, test/models/fact_check_test.rb, test/models/project_media_2_test.rb
When running via smooch, every once in a while, a request from Check-API to Alegre fails. There is every indication that this is some sort of intermittent, non-serious issue. When trying to reproduce them, even at large scales with lots of attempts to recreate the issue, Alegre responds correctly consistently. When looking at Alegre and Presto, neither show any indication that there is an issue. The response itself doesn't seem to be loud or fundamentally broken. For the time being, we're introducing a retry - and if that fails, we'll be much more confident that something more fundamental is happening that requires a deeper dive.
References: CV2-4233
I've added a direct test that should yield a proper null output after retrying multiple times, and ran a local script with side-effecting …
=> CV2-4233 add retry looper for alegre requests that intermittently fail

app/models/bot/alegre.rb, app/models/concerns/relationship_bulk.rb, app/models/relationship.rb, lib/tasks/check_clusters.rake, test/models/bot/alegre_2_test.rb, test/models/cluster_test.rb, test/models/relationship_test.rb
For FactsFirstPH, elections project we run in the Philippines in early 2022, we implemented the very first version of shared feeds and global clusters. Part of that logic included adding new items to clusters automatically. We’re changing this logic, so before proceeding with the new logic, it’s important to get rid of the previous one.
References: CV2-4173
Confirmed that all tests pass locally.
Confirm that all removed methods are no longer needed.
=> Delete the `set_cluster` method definition and calls from Alegre Bot

app/models/concerns/smooch_blocking.rb
When trying to unblock a tipline user, don't crash if there is no related instance in the `blocked_tipline_users` table.
=> Better error handling for `unblock_user` method

config/initializers/devise.rb
Due to https://github.com/devise-two-factor/devise-two-factor/issues/28, devise doubles the count stored in the failed_attempts column when 2FA is enabled.
In this PR we are doubling the value set in devise_maximum_attempts in CheckConfig, so that devise always doubles it, at least until the issue referred to above is fixed
Due to this, user's will no longer get a warning before the last login attempt, so we are increasing the default number of attempts before an account is locked to 5.
Confirmed that the user's account will always be locked after 5(default value) tries.
=> Double devise failed attempts

app/graph/relay_on_rails_schema.rb, test/controllers/graphql_controller_12_test.rb
GraphQL query introspection allows users to browse all graphql endpoints along with their descriptions.
Since this is considered to be a security risk, here we are disabling that access.
References: CV2-4171
While on `develop` (or any other branch that doesn't have this fix), run the following query in GraphiQL (Can be accessed via `http://localhost:3000/graphiql`):
```graphql
{
__schema {
types {
name
description
}
}
}
```
This should return a list of all available queries and their descriptions. 
---
When you switch to this branch, the same query should result in an error.
=> Disable GraphQL Query Introspection

app/models/concerns/smooch_messages.rb, app/models/relationship.rb, test/models/bot/smooch_6_test.rb
Stop manually-creating suggestions between the item created from the user request and search results.
REFERENCES: CV2-4206
Ensure that all tests and checks are passing.
=> Stop storing search results as suggestions

app/models/concerns/smooch_search.rb, config/initializers/report_designer.rb
Messenger changed the way it formats messages... now it breaks a single long message into smaller messages, so for long fact-checks, messages can be delivered out of order, which is super weird (like, a title in one message, the link in another message, etc.). This commit changes how tipline search results are delivered for Facebook Messenger: no fact-check summary, only title and URL.
Fixes CV2-4287.
The change should affect ONLY Facebook Messenger.
=> Only deliver fact-check title and URL for Facebook Messenger tipline search results

lib/check_search.rb
If a workspace has the option to send fact-checks only in the same language as the request, the feed query is currently throwing an error.
References: CV2-4291
- Etc.
=> Don't apply fact-check language filter for feed queries

app/models/tipline_request.rb, db/migrate/20231122054128_create_tipline_requests.rb, lib/tasks/migrate/20231122054128_migrate_tipline_requests.rake
Expose the code for TiplineRequest migration so we can proceed with migration before live deployment.
PR contains:
- The database migration
- Rake task `check:migrate:migrate_tipline_requests`
- Empty TiplineRequest model:
Also I updated the rake task to accept pre-defined keyword for slug(i.e `rails check:migrate:migrate_tipline_requests['slug:custom_slugs`]) by this way the rake task will allow user to type team slugs using terminal.
References: CV2-2648
Tested locally against live DB using specific team.
- Etc.
=> CV2-2648: migrate tipline requests

db/migrate/20240228203459_setval_for_tipline_requests.rb, db/migrate/20240228203460_setval_for_tipline_requests.rb, db/schema.rb, lib/tasks/check_khousheh.rake, lib/tasks/migrate/20231122054128_migrate_tipline_requests.rake
This PR implements the final version of the feed clusters rake task.
Reference: CV2-4172.
Executed locally.
=> Feed clusters: Rake task completion and refactoring.

lib/check_statistics.rb
Add the workspace name to the error message so we can better handle it in Sentry (for example, archive the ones that are expected to fail).
Fixes CV2-4281.
By executing the rake task `rake check:data:statistics`.
=> Better Sentry error for WhatsApp Insights API exception in statistics job

app/models/concerns/team_rules.rb, lib/tasks/migrate/20231122054128_migrate_tipline_requests.rake
- Add rake task to remove old tipline requests (annotation of type smooch).
- Fix sentry issue
References: CV2-4351, CV2-4352
Locally against live DB .
- Etc.
=> Delete old tipline request and fix sentry issue

db/schema.rb, db/seeds.rb
We are going to start working on a feature to filter the tipline request:
- Filter by items that received positive feedback
- Filter by items that received negative feedback
When creating the seeds we were not adding the **negative feedback** (`irrelevant_search_result_requests`). Before we were adding only: `default_requests`, `timeout_search_requests` and `relevant_search_result_requests`. So this PR changes that.
References: 4309
By running the seeds script and checking if the requests type were added.
- To make it more likely that we will get `relevant_search_result_requests` and `irrelevant_search_result_requests`, I added them a few more times to the array in `smooch_request_type`.
- The negative feedback is **not** displayed in the UI.
- If a request report has been received. That …
=> Add negative feedback to tipline's smooch request type

app/models/concerns/smooch_search.rb
Replace item by parent when sending tipline keyword search results.
Fixes CV2-4071.
=> Replace item by parent when sending tipline keyword search results.

app/models/bot/fetch.rb, app/models/fact_check.rb
This method was causing an issue and is not needed anymore.
We can simply substitute it by `fc.publish_report = true`
When trying to import some Fact Checks, using the `FetchBot`,
with language set to `pt_BR`, the language was still being set as `en`.
That was happening because inside `import_claim_review` after it runs
`set_claim_and_fact_check`, it was running `create_report`.
https://github.com/meedan/check-api/blob/4a44ab093fbae68e25114c4cef0af537daec9f2b/app/models/bot/fetch.rb#L187-L199
Inside `create_report` it was setting the language to the workspace’s
default language. So, we might want to add a language as `pt_BR`,
but if the default language of the workspace is `en`, that gets overwritten.
https://github.com/meedan/check-api/blob/4a44ab093fbae68e25114c4cef0af537daec9f2b/app/mod …
=> 4380 – Remove create_report method from the FetchBot

config/tipline_strings.yml
Adding Mongolian as a supported language for tiplines. I followed Meedan's documentation "How to localize (l10n) in Check" in order to do this.
Reference: CV2-4394.
Manually: Configured a tipline in Mongolian and tested the bot in that language.
=> Adding Mongolian as a supported language for tiplines.

db/seeds.rb
We updated how we create the clusters in the seeds script, so it will:
- add all the cluster values (some were missing from the prior version)
- add the real values (some were random values, now only channel is random)
References: 4346
By running the script to create all the data, and then running it to add data to an user.
- Currently all the cluster's items are from the same team. We decide to finish this first version first, and update it to add the other team's items to the cluster on a next ticket/PR.
_* I ran the script twice, so that is why User A has 4 feeds instead of 2._
=> 4346 – Seeds script: create cluster data with real values

config/initializers/plugins.rb
Load `ClusterTeam` class when the application starts. It just happens in production environment. Fixes an error reported by Sentry on QA.
References: SENTRY event ID 41a7e7cf09924d9dbcf0f31b90f370b0.
Opening a cluster page in Check Web should not return an error 400 from the backend.
=> Load `ClusterTeam` class when the application starts

app/models/concerns/smooch_blocking.rb, db/schema.rb, test/models/bot/smooch_2_test.rb, test/models/bot/smooch_3_test.rb, test/models/bot/smooch_6_test.rb
When a user is banned and their submissions are still being consumed by other users, we will now automatically apply content warning screens to their ProjectMedia.
References: CV2-3582
- Confirmed that banned users' content will be marked as 'Spam'
Ban a user and confirm that all of their project media will be flagged as 'Spam'
=> Apply content warning screens for banned users

db/seeds.rb
**Issues**
1. All of the clusters only had one team: because we were iterating and creating the clusters per team.
2. Only from the cluster creator team: because we where inviting the other teams, but not accepting. When we would check if a team was part of the feed, only the cluster creator (`team a`) was returned. 
**How this was fixed**
I had to fix issue 2 first. I added a method `accept_invitation(feed, team)`. This way we can accept it on the script as needed, so we are still able to test the invitation acceptance process. Currently `team c` accepts the invitation to `feed 2` (our feed with clusters). 
To fix issue 1: instead of iterating per team project medias, I’m removing the teams that aren’t part of the feed, adding all the project medias to a `feed_projects_medias` array. …
=> 4406 – Seeds: Add multilpe teams' items to clusters

app/graph/types/saved_search_type.rb
Modify the code to include a check for any FeedTeams associated with the same saved_search_id. This change ensures that the list is considered part of a shared feed when either a Feed or a FeedTeam is linked to the saved_search_id
Checked that the param is correctly being set to true and ran the integration tests on check-web: https://app.travis-ci.com/github/meedan/check-web/builds/269722027
Reference: CV2-4413
=> add condition to verify if list is shared on a feed

app/graph/types/claim_description_type.rb, lib/cluster_team.rb, lib/relay.idl, lib/tasks/check_khousheh.rake, public/relay.json, test/controllers/graphql_controller_5_test.rb
A couple of fixes for some shared feed attributes computation:
(1) Only requests created before the cluster was created should be included
(2) Only published fact-checks should be included
Fixes: CV2-4177.
=> A couple of fixes for some shared feed attributes computation

lib/cluster_team.rb
Calculate the number of requests and media created until the time the cluster was created instead of using cached fields. That should be fine since feeds should never contain too many teams anyway.
Fixes: CV2-4177.
Performance shouldn't be affected since a cluster will never contain more than 5 or 10 teams.
=> Fixing how media and requests are counted for each workspace in a feed cluster

app/graph/types/feed_team_type.rb, app/graph/types/feed_type.rb, app/models/feed.rb, app/models/feed_team.rb, lib/relay.idl, public/relay.json, test/models/feed_team_test.rb, test/models/feed_test.rb
This PR adds a new field `saved_search_was` to the GraphQL types `FeedType` and `FeedTeamType`. When the list (saved search) is updated for a given `Feed` or `FeedTeam`, this new field returns the previous object. This allows the frontend to update the Relay store for the previous and new lists.
References: CV2-4413.
Unit tests added.
=> Expose in GraphQL API the previous feed list 

db/migrate/20240304160338_add_last_received_terms_email_at_to_users.rb
Maybe the "default" value in this migration is making it take longer for big databases.
=> Removing the "default" from the migration just to see if this is the problem

app/models/concerns/project_media_cached_fields.rb, app/repositories/media_search.rb, lib/check_search.rb, test/controllers/elastic_search_10_test.rb, test/controllers/graphql_controller_2_test.rb, test/models/bot/smooch_7_test.rb
Here, we are adding the ability to filter items by tipline search result feedback (negative and positive). This will
allow `CheckSearch` to be called with `:positive_tipline_search_results_count` and `:negative_tipline_search_results_count` as search fields with  numeric range filter.
References: https://meedan.atlassian.net/browse/CV2-4309
1: Added tests in `test/controllers/elastic_search_10_test.rb:483` to simulate and validate this search.
2: Directly calling GraphQL with the positive and negative filters, for example:
```
query {
search(query: "{\"negative_tipline_search_results_count\":{\"min\":1, \"max\":2}}" {
number_of_results
}
}
```
- File FFFF, line LL: This refactoring does this …
=> Filter items by Tipline search result feedback

Gemfile.lock, app/graph/types/team_type.rb, config/application.rb, test/controllers/graphql_controller_8_test.rb, test/controllers/graphql_controller_test.rb
This way, API clients can know how we format (and can even use) the placeholder values for the report introduction.
Reference: CV2-4424.
Existing tests should cover this. But in GraphiQL:
I didn't include `status` since it's per item.
=> Return placeholder values for report introduction settings in GraphQL `TeamType.get_report` field

app/models/concerns/alegre_similarity.rb, app/models/concerns/alegre_v2.rb, test/models/bot/alegre_3_test.rb
Once we merged video changes, some lines started showing as uncovered. Upon initial review, some of those lines were obviously no longer in use and should just be removed (https://github.com/meedan/check-api/blob/662f023463a05b37120547d38d6eb2043304d9c3/app/models/concerns/alegre_similarity.rb#L289-L299 and https://github.com/meedan/check-api/blob/662f023463a05b37120547d38d6eb2043304d9c3/app/models/concerns/alegre_v2.rb#L442-L443) - also some weird dangling function declared in a test nonsensically. It shouldn't be there, so lets see if something breaks if its removed... Also add another test for array based contexts and leave that line in as that could still theoretically be a valid case.
References: CV2-4529
Added another test for the only uncovered line, otherwise I'm removing code. …
=> CV2-4529 initial review on missing / uncovered lines

lib/tasks/data/statistics.rake, test/lib/tasks/statistics_test.rb
Update the statistics rake task to include media imported by all bot users, not just tipline data.
References: CV2-3405
Steps to test:
- Create a bot in a workspace
- Create some ProjectMedia using that bot via the api
- When you run the statistics rake job (`bundle exec rake check:data:statistics`), if you navigate to the workspace and go to `settings/data` you should see statistics for media from all bot users
- Confirm that the generated statistics are what we expect
- We do not update existing stats, so in case you want to re-generate statistics for a specific month, you have to delete them from the database first.
=> CV2-3405 - Update statistics rake task to factor all bot users

app/models/concerns/alegre_webhooks.rb, test/models/bot/alegre_v2_test.rb
Responses from a "canned" response from Alegre to Check API are slightly different such that Check API can't affirmatively confirm that its a valid webhook data package. This fixes it by adding another hook for identifying doc_id in the webhook, adding a new check to confirm if its a callback (this is temporary and will be deleted when the text work is done), and adds a test to check for this type of case
Identified in the wild and tested each side of this in the respective REPLs. Should be an exact match for that case.
Nothing in particular
=> CV2-4126 deal with canned responses being slightly different formats

.github/workflows/gitlab-mirror.yml
The correct URL for GitLab sync is https://gitlab.com/meedan/check-api.git/.
=> Fix GitLab target URL.

app/models/team_task.rb, app/workers/team_task_worker.rb, test/controllers/graphql_controller_9_test.rb, test/models/team_task_test.rb
Apply re-order for team annotations to item annotations.
References: CV2-4508
- Etc.
=> CV2-4508: apply team task order to item tasks

app/models/concerns/alegre_webhooks.rb, test/controllers/webhooks_controller_test.rb
New theory is that all webhooks are getting accidentally consumed including ones where its just reporting back that we stored an object. Forcing responses to only be consumed when explicitly flagged as such.
- Etc.
=> CV2-4126 add more explicit flagging to avoid sending stray callback params into callback consumption function

app/models/team_task.rb, test/models/team_task_test.rb
Adding new team task should reflect on unconfirmed items.
References: CV2-4508
- Etc.
=> CV2-4508: include unconfirmed items when add new team task

app/models/concerns/alegre_webhooks.rb, test/controllers/webhooks_controller_test.rb
Puts alegre webhook in line with other webhooks to use the body rather than params as the accessor for data
We're seeing very weird results that makes us believe that the params coming in from `request.params` get altered in potentially erratic ways - and we are definitely losing variables in params somehow. This is a fix to make Alegre canonical with other webhooks, but also potentially resolve that problem.
N/A
=> CV2-4126 alter webhook to use body instead of params

app/models/concerns/alegre_webhooks.rb
Some weirdness around potentially confused origins of raised sentry errors - flagging them explicitly as a sanity check during extended QA issues.
Not tested yet - pushing for better instrumentation on existing tests
NA
=> CV2-4126 flag origin of sentry error explicitly

app/controllers/api/v1/admin_controller.rb
When there is an error on Facebook Messenger integration, we don't have enough visibility on the error. The point of this PR is to just log the Facebook response to Sentry.
References: CV2-4559
=> Log Messenger integration response from Facebook

lib/tasks/migrate/20240505063600_fix_project_media_tasks.rake
Add a rake task to fix item annotations order and add missing annotations to unconfirmed items
References: CV2-4555
Verify rake task against local database
- Etc.
=> CV2-4555: Fix item annotations order and add missing annotations for existing items

app/models/concerns/smooch_menus.rb
For WhatsApp tiplines that have more than 10 menu options and more than one language, a "Languages" option is displayed in the menu. That option is always localized to the current tipline language. If users select the wrong language, it can be hard for them to find the "Languages" option again. This commit fixes it by adding two labels for the "Languages" option: one in the current language and another one in the default workspace language (if they are different).
Reference: CV2-4554.
- Configure a WhatsApp tipline with more than one language and more than 10 menu options in total
- Send a message to the tipline and open the main menu
- If the current language is different from the default one, you should see the "Languages" option in two languages:
=> Language option in tipline menu can be both in English and regional languages

app/models/feed.rb
It should exclude unselected workspaces, instead of returning clusters with all other selected workspaces.
Fixes CV2-4601.
Automated tests should be updated to cover this.
=> Inverting the logic of the feed workspace filter for clusters

app/models/assignment.rb, lib/tasks/data/project_media.rake
Fix sentry issue and add sleep to recalculate cached field rake task.
References: CV2-4604
- Etc.
=> CV2-4604: fix sentry issue

app/models/bot/alegre.rb, app/models/concerns/alegre_v2.rb, test/controllers/reports_controller_test.rb, test/models/bot/alegre_v2_test.rb
With the latest 4126 changes we observed that there were many many cases where we hit the timeout in alegre's cached response logic - I think its because we don't differentiate between getting *nothing* from alegre versus getting an affirmative *no results* from alegre. Tested locally with temporary log files and this is confirmed to solve for that difference!
References: CV2-4126 and CV2-4597
Tested locally - may need to tweak existing unit tests, tbd
None come to mind!
=> CV2-4597 rework how cached responses are returned to re-differentiate between empty responses and non-responses

app/models/fact_check.rb, test/models/fact_check_test.rb
Don't pause reports automatically when a fact-check is updated.
Update the report status when a fact-check is updated only if:
- There is no status set
- The API call explicitly sends a publish_report parameter
Fixes CV2-4620.
TDD. I implemented a test that reproduces the issue.
=> Don't pause reports automatically when a fact-check is updated.

app/models/cluster.rb, config/locales/en.yml
Show list of existing media URLs in validation message when trying to import media from feed that already exist in the workspace.
Fixes: CV2-4631.
This needs to be properly tested using the frontend.
=> Show list of existing media URLs in validation message when trying to import media from feed that already exist in the workspace.

app/models/cluster.rb, config/locales/en.yml
When trying to import media from a shared feed that already exist in the target workspace, return the existing item URLs in the error message as Markdown, so they can be better displayed on the frontend.
Reference: CV2-4631.
On the frontend side (Check Web branch with same name as this):
=> Shared feed import validation message: Format URLs using Markdown

app/models/concerns/smooch_messages.rb, test/models/bot/smooch_4_test.rb, test/models/bot/smooch_6_test.rb, test/models/bot/smooch_test.rb
Save tipline message inside `ApplicationRecord.transaction` to make sure that item and tipline request were created.
References: CV2-4593
- Etc.
=> CV2-4593: use ApplicationRecord.transaction to save message

app/graph/mutations/explainer_mutations.rb, app/graph/types/explainer_type.rb, app/graph/types/team_type.rb, app/models/explainer.rb, db/schema.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_12_test.rb, test/models/explainer_test.rb
In order to list explainers on the frontend side, some changes were needed on the backend.
- Title should not be mandatory at the API level but at the model level (and description as well)
- Store tags in the `Explainer` model and keep them in sync with `TagText` instances
- Adding filters, counter, sorting and pagination to the `TeamType.articles` connection
Reference: CV2-4500.
Automated tests updated and added for 100% coverage.
=> Explainers data model and API updates

test/integration/omniauth_integration_test.rb
Since we added rate limiting for login requests, we need to flush redis before the tests run.
Ran the test repeatedly to confirm it is not flaky
=> Fix flaky test in OmniauthIntegrationTest

app/models/bot/smooch.rb
Otherwise, an exception can prevent the report from being sent.
Fixes: CV2-4656.
This fix should be covered by existing tests.
=> Do not raise exception if child item can't inherit status from parent item

app/models/concerns/smooch_messages.rb, app/workers/smooch_worker.rb, test/models/bot/smooch_3_test.rb, test/models/bot/smooch_4_test.rb, test/models/bot/smooch_6_test.rb, test/models/bot/smooch_7_test.rb
- Simplify SmoochWorker job to accept id instead of object.
- Check existing TiplineRequest with `smooch_message_id` before creating new one.
References: CV2-4666
Verified locally and waiting existing tests to pass via Travis.
- Etc.
=> CV2-4666: Sentry issue

app/models/bot/alegre.rb, app/models/concerns/alegre_v2.rb
Flip logic for notifying of timed out response - currently we are logging all *not* timed-out results, we need the opposite.
References: CV2-4713
Identified and tested in REPL during live triaging of this ticket
NA
=> CV2-4713 flip notification logic

app/models/concerns/alegre_v2.rb, test/models/bot/alegre_v2_test.rb
Fairly straightforward explanation as above - workspaces can disable similarity across all modalities or be selective in disabling a modality. When, for a given `project_media`, the similarity functionality is disabled, we don't send a request to Alegre to fingerprint the item, yet we wait for a response, which appears to be the source of 100% of the `AlegreTimeout` errors. This should solve them by doing a bit of DRY'ing and refactoring to have a way of checking that in all the stages of the fingerprinting / searching process.
References: CV2-4713
Tested in REPL against live cases when debugging / identifying the issue, added a few tests for this as well
Just review refactoring - should be straightforward!
=> CV2-4713 dont wait for results when checking a disabled modality for a given workspace

app/models/concerns/alegre_v2.rb, config/config.yml.example
Simple bump from one minute to two minutes for timeout errors in waiting on alegre responses.
References: CV2-4741
Not tested yet - should be straightforward
NA
=> CV2-4741 increase timeout from one to two minutes

app/models/concerns/relationship_bulk.rb, test/controllers/graphql_controller_12_test.rb
When bulk-accepting a suggestion, the callback that sends a report is not called. This PR fixes it.
Fixes CV2-4758.
TDD. A functional test was added for this case.
=> Send report when bulk-accepting suggestion.

config/application.rb, config/tipline_strings.yml
Adding italian translations and enabling locale on application.rb
References: CV2-4736
Tested on rails console:
irb(main):016:0> I18n.l(Time.now, locale: 'it', format: :long)
`=> "19 giugno 2024 17:02"`
irb(main):017:0> Bot::Smooch.get_string('privacy_and_purpose', 'it')
`=> "Privacy e scopo\n\nBenvenuto al suggerimento di %{team} %{channel}.\n\nPuoi utilizzare questo numero per inviare la tua richiesta di verifica.\n\nI tuoi dati sono al sicuro. Prendiamo sul serio la nostra responsabilità di salvaguardare le tue informazioni personali e di mantenere %{channel} privato e sicuro; non condivideremo, venderemo o utilizzeremo le tue informazioni di identificazione personale (PII) se non per fornire e migliorare questo servizio.\n\nPer rilevare la disinformazione virale il prima possibile in …
=> Add italian translations and enable locale

app/models/concerns/alegre_v2.rb, app/models/concerns/smooch_capi.rb, app/models/concerns/smooch_search.rb, test/controllers/elastic_search_9_test.rb, test/models/bot/alegre_2_test.rb, test/models/bot/alegre_3_test.rb, test/models/bot/alegre_v2_test.rb
On Presto, oftentimes we unnecessarily fingerprint the same item several times. With this change, we will plumb a `content_hash` key along through Check-API to Alegre to Presto, so that Presto can use the key to do an internal lookup against a Redis server to see if we have a recently fingerprinted item with that ID and just return it directly.
References: CV2-4719
No tests yet - expanding the data package will very likely cause many test errors, so this first change is to just highlight/record them.
Nothing significant at the Check-API stage, probably.
=> CV2-4719 add unique identifier as doc_id at check-api level

app/models/concerns/smooch_resend.rb, test/models/bot/smooch_4_test.rb
On a Facebook Messenger tipline, if the newsletter is sent to a user who hasn't interacted with the tipline in the last 24 hours, the message is not sent unless it contains a tag (it's like templates for WhatsApp). This commit adds support to that.
Fixes: CV2-4787.
Tested locally and received the newsletter, but I also added a unit test for this case.
=> Implementing support to re-sending Facebook Messenger newsletters after 24-hours window

app/models/concerns/smooch_search.rb
After CV2-4287 we only send titles and URLs on Facebook Messenger. When the URL is empty, however, this results in a poor user experience. In the case of reports that have a description but do not have a URL we should send the title and description.
References: CV2-4846
Tested logic separate from application, but have not tested in the code base as I am not running a Messenger Tipline locally.
=> Include the body in a report when the URL is blank

Dockerfile
This changes fixes some discrepancies between the legacy GitLab CI deploys using the old `production/Dockerfile` and the new unified Dockerfile setup. Required for batch jobs in Terraform.
References: CV2-4399
Syntax was verified, however, confirmation of fix will require building in GHA to verify.
=> Add missing scripts and configuration to GHA image builds for batch

app/models/concerns/smooch_messages.rb
Remove the text on the buttons, such as 'Submit' and Add more. from request body.
This issue appears only for CAPI integration so I limit the media files to messages that contain mediaUrl
References: CV2-4696
- Etc.
=> CV2-4696: make sure the mediaUrl exists for media files

app/graph/types/project_media_type.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_12_test.rb
Adding a new field to `ProjectMediaType` on the GraphQL API: `articles_count`. It returns the total number of articles (explainers plus fact-check) for a given item.
Reference: CV2-4889.
Adapted an existing functional test to request this field.
=> Ticket CV2-4889: Expose number of articles for an item in GraphQL

lib/rss_feed.rb
Parse RSS feeds that return objects instead of strings.
Fixes CV2-4906.
=> Parse RSS feeds that return objects instead of strings.

lib/tasks/migrate/20240715013839_add_team_id_to_claim_description.rake
Set ClaimDescription.team_id based on ClaimDescription.project_media_id .
References: CV2-4879
Run rake task locally against live DB backup.
- Etc.
=> CV2-4879: add rake task to set team_id for ClaimDescription

db/seeds.rb
This creates both standalone claim descriptions and standalone claim descriptions with fact checks. Though only the second is visible in the UI. We also:
- verify the fact checks with a random status ('undetermined', 'not_applicable', 'in_progress', 'verified' or 'false')
- add a link to half of the standalone fact checks
References: 4880
Created new users and added to an existing user.
I also had to update how we were verifying and publishing the fact-checks that are related to a project media. It was breaking since now we can have `claim_descriptions` with `nil` `project_media_id`.
https://github.com/meedan/check-api/blob/fc59e8166c56827520431f450699d29421be1665/db/seeds.rb#L333
=> 4880 – Seeds Script: Create standalone claim descriptions and fact-checks

.github/workflows/ci-tests.yaml
Adding the new workflow for ci-tests to github actions
References: https://meedan.atlassian.net/browse/CV2-4793
The pipeline was previously set to run on push to the feature branch as shown here https://github.com/meedan/check-api/actions/runs/9892849970
- Etc.
=> add ci-test-workflow

app/models/bot/smooch.rb, app/models/concerns/smooch_messages.rb, test/models/bot/smooch_3_test.rb
Create a relationship between media items and long caption.
References: CV2-4754
- Etc.
=> CV2-4754: force relation between media and long caption

lib/tasks/migrate/20240725173311_migrate_claims_without_fact_checks.rake
Migrate claims without fact-checks.
References: CV2-4918
Run rake task against live DB dump locally.
- Etc.
=> CV2-4918: migrate claims without fact-checks

app/lib/tipline_search_result.rb, app/models/concerns/smooch_search.rb, app/models/explainer.rb, config/initializers/report_designer.rb, test/models/bot/smooch_4_test.rb, test/models/bot/smooch_6_test.rb, test/models/bot/smooch_7_test.rb, test/models/explainer_test.rb
Explainers can match incoming user queries to the tipline and be returned as search results, like fact-checks. This feature has two main parts: indexing and retrieving. Steps below:
**Refactoring**
**Indexing**
**Retrieving**
Reference: CV2-4664.
Automated tests implemented for new features. Things to test manually:
=> Tipline search by explainers

app/graph/types/source_type.rb, app/graph/types/user_type.rb, app/models/user.rb, config/config.yml.example, test/controllers/graphql_controller_12_test.rb
To provide a better “single voice” CS experience we need to limit the visibility of specific Meedan teammates in Item histories for workspaces. As teammates come and go, and different people need to step in and provide support the individual who performed an action in a workspace from the Meedan side is irrelevant to the partner.
- If a user is a `super admin` and not a member of the workspace
- show their `name` and `profile_picture` as Meedan
- If a user is a s`super admin` and a member of the workspace
- show their `name` and `profile_picture` as their own
In the graphql layer, in the `user_type`, I added methods  `name` and `profile_picture` that check whether a user is `super_admin` and a member of the workspace and send both accordingly.
References: 4703
I added two tests:
1. `rails …
=> 4703: Update @meedan people involvement in item history

.github/workflows/ci-tests.yml
We've been having sporadic failures of CI tests. Based on other discussions, try a fix for the docker compose commands used in CI workflow.
This change will need to be merged to `master` to apply to future workflows.
=> Test syntax fix for docker compose commands.

app/graph/types/claim_description_type.rb, app/models/claim_description.rb, lib/relay.idl, public/relay.json, test/models/claim_description_test.rb
Use case: we may need to update the project media information in the Relay store when it's removed from a claim.
Reference: CV2-5000.
I added an automated test.
=> Return the previous project media for claim description

app/models/annotations/tag.rb, test/controllers/graphql_controller_12_test.rb, test/models/tag_test.rb
When trying to create an imported fact-check that had a tag with a trailing space it would fail (`text has already been taken`).
We have a normalization step but that runs `before_validation` on `TagText`.
So when we are checking if the tag exists in line 92 from `tag.rb`, the tag has not been normalized. This means:
- We look for 'tag', it is not there. We create it.
- We look for ' tag', it is not there. We try to create it, it gets normalized, so it becomes 'tag'. Then we fail to create it,
because it already exists.
Adding the strip when comparing tags fixes this, but I'm not sure if it is the best solution.
References: 5010
- I added one big test that replicated the issue we saw: `rails test test/controllers/graphql_controller_12_test.rb:613`
- And added one model test: `rails test …
=> 5010 – Fix tag with trailing space error

app/graph/types/me_type.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_10_test.rb
This new field is not cached, like `number_of_teams`, and can take a `status` argument, this way, it's consistent to be used along with the field `team_users`.
Fixes CV2-4938.
Updated a unit test to cover this case.
=> Adding a `team_users_count` field to GraphQL `MeType`.

db/migrate/20240813155311_allow_empty_project_media_id_for_clusters.rb, db/schema.rb
Reverting migration until empty clusterization center issue is actually resolved.
Reference: CV2-4869.
This should be tested by running the clusterization rake task successfully on QA.
=> Reverting migration until empty clusterization center issue is actually resolved

app/graph/types/me_type.rb, app/graph/types/user_type.rb, app/models/concerns/project_media_creators.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_11_test.rb, test/controllers/graphql_controller_12_test.rb
This information is only needed for the current user, so, it should be under `MeType`, not `UserType`.
References: CV2-4938 and CV2-4704.
Automated tests were updated to reflect this change.
=> Moving `accessible_teams` from `UserType` to `MeType`.

app/models/concerns/project_media_associations.rb, test/models/explainer_test.rb
Fixes an issue reported by Sentry.
Fixes: CV2-5099.
TDD.
=> Delete `ExplainerItem` when `ProjectMedia` is destroyed.

config/initializers/report_designer.rb
Update report should reflect on FactCheck so I disabled the version for FactCheck to keep history for report change only.
References: CV2-5051
Re-run implemented automated tests.
- Etc.
=> CV2-5051: disable version for FactCheck when update report

app/models/concerns/alegre_v2.rb, app/models/concerns/article.rb, app/models/concerns/project_media_getters.rb, app/models/explainer.rb, test/models/bot/smooch_6_test.rb, test/models/bot/smooch_7_test.rb, test/models/explainer_test.rb
Moving other side-effecting article storage to vectorize in presto
References: CV2-5082
Not yet tested - changing code first to determine effect of changes then work through necessary changes from there - testing will need to just ensure that articles do in fact get indexed if you send these commands to alegre from check-api
None in particular!
=> Cv2 5082 article indexing to presto

app/models/concerns/smooch_resend.rb, app/workers/tipline_newsletter_worker.rb
Fixes CV2-5127.
When a tipline is running both CAPI and Smooch, the `get_installation` method will set the provider to `CAPI`. When sending a newsletter, it's necessary to adjust the provider to `ZENDESK` for people who subscribed to the Smooch newsletter, not the CAPI newsletter.
=> Adjust Smooch Bot provider when tipline is running both CAPI and Smooch.

app/models/bot/smooch.rb, test/models/bot/smooch_6_test.rb, test/models/bot/smooch_test.rb
Since #1676 , we have treated messages with media or more than `min_number_of_words_for_tipline_submit_shortcut` specially and allowed them to directly enter the submission state to search for fact-checks. 
This PR has any message with a URL exhibit the same behavior. That is, "abc http://example.com" should directly enter the submission state even though it is shorter than `min_number_of_words_for_tipline_submit_shortcut` having only two words.
References: CV2-5148
Wrote unit tests and actually ran them locally now.
N/A
=> CV2-5148: include URLs as shortcuts triggering submission

app/models/team.rb, test/models/team_2_test.rb
Search for fact-checks by multiple keywords regardless the order.
Fixes: CV2-5129.
Unit test added.
May not work for all languages.
=> Search for fact-checks by multiple keywords regardless the order.

app/models/bot/smooch.rb, test/models/bot/smooch_test.rb
URI.regexp.match... only matched fully-qualified urls (i.e., urls need to include http://, https://, or another protocol) . I knew this at the time I did #2011 , but I didn't realize until testing that this was inconsistent with how WhatsApp handles URLs.
The changes in this PR use Twitter::TwitterText::Extractor.extract_urls, which recognizes urls without the protocol. This is consistent with how WhatsApp and more in line with user expectations.
References: CV2-5148
Added a unit test for this specific case
N/A
=> CV2-5148: Use more inclusive detection of URLs in message text

app/models/team.rb, test/models/team_2_test.rb
Now searching for fact-checks can also match the claim fields "description" and "context".
Fixes: CV2-5194.
I added a unit test.
=> Searching for fact-checks should match claim fields too.

lib/tasks/check_khousheh.rake
This is to restore the behavior of before we pushed the changes for not including blank items by default.
Fixes CV2-5158.
I executed the `CheckSearch` query on live and it returned more items for clusterization.
=> Include blank media when iterating through items for clusterization.

app/models/request.rb, test/models/request_test.rb
More work moving low level alegre calls over to presto-based alegre calls
References: CV2-5080
Not tested yet - follows previous patterns we've solved for, so shouldn't be excessively difficult!
Nothing in particular.
=> Cv2 5080 request model to presto

app/models/bot/fetch.rb
While I was testing backlog imports locally, I noticed that the tags were being created, but not added to the fact check.
This happened because we associate them with the project media (here:check-api/app/models/bot/fetch.rb ) and not the fact-check itself, and those are now separate things. Meaning, we need to add them to the fact-check itself.
References: 5227
By importing fact-checks using our script and FetchBot.
- Etc.
=> Update imported fact-check tag creation

.codeclimate.yml, lib/check_search.rb, test/lib/list_export_test.rb
The current export limit for media lists is 10.000 because this is the maximum size of a result window in ElasticSearch. The solution is to paginate the results.
Fixes: CV2-5205.
This is just a refactoring, the existing test should cover it.
=> Be able to export a full list of media clusters.

app/lib/check_permissions.rb
Update the cache key for permissions in order to force a refresh/rebuild.
References: CV2-5153.
Once deployed, we should see the same behavior across all environments.
=> Update cache key for permissions.

app/models/concerns/alegre_v2.rb, app/workers/reindex_alegre_workspace.rb, test/workers/reindex_alegre_workspace_test.rb
Moves our reindexer task over to presto - annoyingly we use bulk for this but have to dip down to singular document updates for now, since we don't have a bulk endpoint yet for presto.
References: CV2-5084
Tested the new plumbing with a test workspace on QA server, otherwise should flow with existing setup just fine
None in particular, low risk change.
=> Cv2 5084 Update Reindexing to use async presto endpoint

app/models/concerns/project_media_associations.rb, test/models/project_media_test.rb
Now that it’s possible to have claims/fact-checks not associated with an item, we should not delete them when the associated item is deleted. They should become standalone articles.
Fixes: CV2-5283.
There should be an automated test for this (I'm still going to add, checking first if any existing test will fail).
=> Make claim/fact-check standalone when associated item is deleted

app/graph/types/tipline_request_type.rb, app/models/tipline_request.rb, lib/relay.idl, public/relay.json, test/models/tipline_request_test.rb
This PR adds a new data point for tipline requests, which is the first time they are responded. "Responded" means: when the tipline request received the first fact-check/report from Check. For search queries that returned results, the time is the same as the request time itself.
Steps:
Automated tests added for all new code in order to keep 100% code coverage.
=> New data point for tipline requests: When they were first responded

app/lib/smooch_nlu.rb, app/models/bot/alegre.rb, app/models/concerns/alegre_similarity.rb, app/workers/reindex_alegre_workspace.rb, test/models/bot/alegre_test.rb, test/models/bot/fetch_2_test.rb, test/models/bot/fetch_test.rb, test/models/bot/smooch_7_test.rb
Switches check-api to use presto-based indexing and querying for main branch of alegre work. 
References: CV2-5081
Full QA to come after epic branch piecewise work is completed - this ticket needs unit test satisfaction for the time being
`app/models/bot/alegre.rb:158` - @caiosba is this looking correct to you? Do we just index title and description in the main branch of logic or is this missing something?
=> CV2-5081 switch text to presto-based querying

app/models/concerns/project_media_creators.rb, app/resources/api/v2/feed_resource.rb, config/locales/en.yml, test/models/project_media_test.rb
This PR fixes a bug with `ProjectMedia.set_original_claim` attribute for video URLs that contained arguments, for example: https://test.xyz/video.mp4?foo=bar. The item wouldn't be created, since the extension validation would fail.
The fix is to use `File.extname` over the URL path only, not the full URL, since the former strips the arguments, while the latter contains them.
Fixes: CV2-5232.
TDD. I was able to reproduce the bug in a unit test contained in this PR. The test passed once the fix was implemented.
At some point, we may get rid of `File.extname` altogether and instead rely on the content-type response header in order to extract the extension.
=> Make `ProjectMedia.set_original_claim` work as expected for a video URL with arguments

app/graph/mutations/explainer_mutations.rb, app/graph/mutations/fact_check_mutations.rb, app/graph/types/explainer_type.rb, app/graph/types/fact_check_type.rb, app/graph/types/team_type.rb, app/models/claim_description.rb, app/models/concerns/article.rb, app/models/explainer.rb, app/models/explainer_item.rb, app/models/fact_check.rb, app/models/team.rb, config/locales/en.yml, db/migrate/20240913210101_add_trashed_to_articles.rb, db/schema.rb, lib/relay.idl, lib/sample_data.rb, public/relay.json, test/models/claim_description_test.rb, test/models/explainer_item_test.rb, test/models/explainer_test.rb, test/models/fact_check_test.rb, test/models/team_test.rb
Allow articles (explainers and fact-checks) to be sent to / restored from the trash.
Steps:
Reference: CV2-5068.
Automated tests in order to keep 100% code coverage.
=> Articles "trash" feature

app/lib/generic_worker_helpers.rb, app/models/concerns/project_media_creators.rb, app/models/project_media.rb, app/workers/generic_worker.rb, config/initializers/class_extensions.rb, lib/sample_data.rb, test/lib/generic_worker_helpers_test.rb, test/models/project_media_8_test.rb, test/models/tag_test.rb, test/workers/generic_worker_test.rb
While working on  `API/Zapier Error: The app did not respond in-time. It may or may not have completed successfully` we thought tags creation could be causing the slow response.
We couldn’t pinpoint it as the cause, but it’s still a good performance improvement and should help improve the response time. So we are moving forward with it.
Sidekiq’s `delayed extensions` were deprecated in version 5 and removed in 7. So we are taking this opportunity to create a `GenericJob`, and eventually substitute the instances of `.delay`/`.delay_for` we have.
References: 5120, 4959
`rails test test/models/tag_test.rb:288`
`rails test test/workers/generic_worker_test.rb`
- File FFFF, line LL: This …
=> 5120 – Create Tags in the background

config/config.yml.example, config/initializers/devise.rb, config/initializers/rack_attack.rb, test/lib/check_rack_attack_test.rb
Improve IP blocking after unsuccessful logins
- Only add IPs to the track list on unsuccessful login
- On successful login, remove IP completely from tracklist
We have also moved code related to authentication blocking to devise.rb
References: CV2-4866
Tested using the script below. When the credentials are correct, you should be able to log in repeatedly more than 100 times.
When using incorrect credentials, your IP should get blocked after 100 attempts.
```bash
#!/bin/bash
for i in {1..110}
do
curl -X POST 127.0.0.1:3000/api/users/sign_in \
-H "Content-Type: application/json" \
-d '{"api_user": {"email": "email@example.com", "password": "PASSWORD", "otp_attempt": ""}}'
echo "Attempt $i"
done
```
If your IP gets blocked, access the rails console and run the script below. This will …
=> Improve IP blocking after unsuccessful logins

app/models/api_key.rb, app/models/concerns/user_private.rb, app/models/user.rb, test/models/api_key_test.rb
Allow deletion of API keys even if the key's user has been used to create media.
References: CV2-5096
Tested in the UI using these steps:
1. Create an Api Key
2. Use the token to create project media
3. Confirm that the Api Key can be deleted
=> Allow deletion of api keys with media

app/models/concerns/tipline_content_multimedia.rb, app/models/concerns/tipline_content_video.rb, config/config.yml.example, test/models/tipline_newsletter_test.rb
We need one maximum size for the Check upload and another one that is actually the maximum size supported by WhatsApp. This separation is needed because we need to convert the uploaded video to H.264, which is the codec support by WhatsApp. So we need a safe margin for that.
Fixes: CV2-5326.
Unit test updated.
=> Need to split the maximum size for tipline content video files.

app/workers/generic_worker.rb
Pretty straight forward. Sets the maximum retry count to 3.
We want to add custom retry logic, but that works differently between Sidekiq 5 and 6.
So we think it is better to focus later on the Sidekiq upgrade, and until there, worker instances can handle their exceptions instead of relying on the generic worker for that.
References: 5120, https://github.com/meedan/check-api/pull/2005
- Etc.
=> Set sidekiq_options retry to 3 for the GenericWorker

lib/tasks/check_khousheh.rake
Reference: CV2-5331.
Automated tests implemented.
=> A couple of improvements for shared feeds

app/models/annotations/tag.rb, app/models/concerns/project_media_creators.rb, app/models/concerns/tag_helpers.rb, app/models/fact_check.rb, app/models/project_media.rb, test/controllers/graphql_controller_12_test.rb, test/lib/generic_worker_helpers_test.rb, test/models/fact_check_test.rb, test/models/project_media_8_test.rb, test/models/tag_test.rb, test/workers/generic_worker_test.rb
While looking into a tags issue I noticed a few things:
- when we made a request with duplicate tags:
- we got an error, so the job was retried 
- the tag was added twice to the FactCheck
- the tag is added once to the ProjectMedia
- when we made a request with a tag with a `#`
- we got an error, so the job was retried
- there seem to have been two errors related to this:
- ActiveRecord::RecordInvalid: Tag already exists
- ActiveRecord::RecordInvalid: Text has already been taken 
- the tag with the `#` is added to the FactCheck 
- the tag is not added to the ProjectMedia
- There are a few things happening at the same time:
- Creation of a `ProjectMedia` with tags 
- Creation of a `FactCheck` with tags
- Tags are an `Object` from the `Tag` Class for `ProjectMedia`, but are a simple array …
=> 5120 – Dont create duplicate tags and clean up `#`

app/lib/check_cached_fields.rb, app/models/concerns/project_association.rb, app/models/concerns/project_media_cached_fields.rb, app/workers/elastic_search_worker.rb, test/controllers/elastic_search_test.rb, test/controllers/graphql_controller_3_test.rb, test/models/bot/fetch_2_test.rb, test/models/project_media_3_test.rb, test/models/project_media_6_test.rb
=> CV2-5005: Sentry issue related to ES

.gitlab-ci.yml
This fixes a prior attempt to update setuptools for deployments. Since check-api is using a different container, the version pin must also adjust.
Tested with a branch deployment into QA.
=> Fix setuptools version pin for check-api builds

app/models/bot/smooch.rb, app/models/relationship.rb
Based on CV2-5324 there is a method to check Relationship exists before creating a new one but may the failure related to other validation so I use a `save` instead of `save!` to avoid raising error
References: CV2-5391
- Etc.
=> CV2-5391: use save instead of save! to avoid raising error

app/models/claim_description.rb, test/models/fact_check_test.rb
Reset item status to default one when claim/fact-check is detached.
Fixes CV2-4502.
Automated tests added for two cases: workspace with core statuses and workspace with custom statuses.
=> Reset item status to default one when claim/fact-check is detached.

app/models/annotations/dynamic.rb
=> CV2-5418: Fix sentry issue

lib/tasks/check_khousheh.rake
There was a change introduced in CV2-5331 that normalized how the `last_request_date` field for a shared feed cluster is calculated. But there is an issue: if the cluster doesn't have any request, no value is set. The fix needed here is to be sure that there is an initial value, which can be the same date as the last item that joined the cluster, when this item has no requests.
Fixes: CV2-5446.
Tested by executing the Khousheh rake task.
=> Setting initial value for `last_request_date` for feed clusters.

app/models/concerns/smooch_blocking.rb
Set the annotator to "Smooch Bot" so that the bot user is displayed in the content warning cover when a user is blocked.
Reference: CV2-5142
=> set the annotator to be the “Smooch Bot”

app/models/relationship.rb, test/models/relationship_test.rb
Sentry issue: Handle the database validation `ActiveRecord::RecordNotUnique`.
Added a unit test to cover rescue case but I could not reproduce the race condition using `Thread.new`
References: CV2-5419
=> CV2-5419: rescue ActiveRecord::RecordNotUnique for relationship save

app/models/relationship.rb, test/models/bot/smooch_2_test.rb
Set the confirmed fields (confirmed_at & confirmed_by) before creation in case relationship type is confirmed which allow child to inherit parent status
References: CV2-5451
implemented automated tests.
=> CV2-5451: set confirmed fields for relationship

db/migrate/20241009192811_add_constraint_relationship_source_and_target_must_be_different.rb, db/schema.rb, test/models/relationship_test.rb
We already had an Active Record validation for that, but it was bypassed for straight updates or race conditions. This PR makes it more robust by adding a database constraint.
Fixes: CV2-5437.
TDD. I added a unit test that reproduces the issue.
=> Make sure that an item can't be related to itself.

app/models/bot/alegre.rb
Report bad relationship structure only if relationship is not nil.
Fixes: CV2-5454 and an issue reported by Sentry.
Maybe the relationship should not even be nil in the first place. But that's a different issue - `Relationship.create_unless_exists` _can_ return nil.
=> Report bad relationship structure only if relationship is not nil.

app/models/relationship.rb, db/schema.rb, lib/sample_data.rb, test/models/relationship_test.rb
When a confirmed relationship is created, if there is any suggestion between the same two items, the suggestion should be delete. We had logic in two different places for that. This PR keeps this logic in only one place (the relationship model), so I removed the logic from the `create_unless_exists` method, which now also takes the relationship type into account. This way we have the logic in only one place, and having this logic as a `before_create` that contains a transaction means that the `destroy` of the suggestion will be rolled back by PostgreSQL if the `create` fails.
Fixes: CV2-5436.
I added a couple of new unit tests, and made sure that the existing tests for `create_unless_exists` still work.
=> Revert rejecting suggestion if relationship creation fails.

app/models/team_task.rb, app/workers/team_task_worker.rb
Add a logic to  TeamTaskWorker based on update_at date to skip the background job if there is a more recent one.
References:  CV2-5434
=> CV2-5434: Review TeamTaskWorker performance

app/workers/generic_worker.rb
This change tries to avoid a single case reported by Sentry: A race condition situation where the related object was still not fully persisted in the database when the job executed. Setting a longer retry interval which should avoid this case.
Fixes: CV2-5459.
This should already be tested by Sidekiq itself.
=> Setting retry interval for GenericWorker.

app/models/concerns/smooch_zendesk.rb
Adding a log line for the outgoing Smooch requests. This can help debugging some issues.
Reference: CV2-5378.
I confirmed in the logs that the new log line appears for outgoing requests to Smooch API.
=> Adding a log line for outgoing Smooch requests.

app/models/bot/smooch.rb, app/models/relationship.rb
I noticed a regression introduced by CV2-5451 that we overlooked. We shouldn't set `confirmed_by` and `confirmed_at` for all relationships, but really keep setting them only for when a relationship created as a suggestion is confirmed... this is the purpose of these two fields. Instead, the logic for inhering the status from the parent item and sending a report is that should have been fixed. This is what this PR does. So:
- Child item should always inherit status from parent item for confirmed relationships, regardless if they are created as confirmed matches or a suggestion that is confirmed... also, should be the same logic if the relationship is created by a bot or by a human
- But when a child item matches a parent item, we should NOT send a report if the user already received a …
=> Do not send report if search results were already received.

app/lib/check_cached_fields.rb, app/lib/check_elastic_search.rb
- Set ElasticSearch’s retry_on_conflict: 0 (so we can rely only on the Sidekiq retry, which retrieves latest value)
- Pass class and ID instead of the full object
References: CV2-5348
=> CV2-5348: refactor ES cached field calling and remove retry_on_conflict

app/models/concerns/smooch_messages.rb, test/models/bot/smooch_3_test.rb
For the tipline messages that contain both Link and Text we should handle the following cases.
References: CV2-5190
=> CV2-5190: Create a Link and Claim from tipline message that contain both link and long text

app/lib/check_cached_fields.rb, app/models/concerns/smooch_messages.rb, test/models/bot/smooch_3_test.rb
- Use `.remove` method to delete the link for message text.
References: CV2-5190
=> CV2-5190: use remove instead of chomp

app/models/link.rb, config/config.yml.example, test/models/media_test.rb
Set a max length (2000) validation for media URL.
References: CV2-5300
=> CV2-5300: set a max length validation for media URL

app/models/bot/smooch.rb, test/models/project_media_8_test.rb
Sentry reported a N+1 query issue so I added a unit test to reproduce N+1 query then apply the fix and re-run same unit test
References: CV2-5348
=> CV2-5348: Fix N+1 query

app/models/bot/fetch.rb, test/models/bot/fetch_test.rb
While trying to run a fact check import Jessie noted that the fact checks weren't imported as published.
I looked at some older imports and seems to have been the case for a while even though we set `fc.publish_report = true` in the FetchBot.
We were updating the published value for `Dynamic` but weren't for `FactCheck`. We hadn't  implemented that as part of the big articles work.
So we just need to make sure both are updated as published when importing through the FetchBot.
References: 5390, 5514
`rails test test/models/bot/fetch_test.rb:257`
- Etc.
=> 5514 – Import fact-check as published report

app/models/bot/smooch.rb, app/models/concerns/smooch_messages.rb, config/config.yml.example, test/models/bot/smooch_3_test.rb, test/models/bot/smooch_6_test.rb
Define a new parameter to for a min  numbers of words to extract media from tipline request.
References: CV2-5511
=> CV2-5511 Define number of words to extract media from tipline request

app/models/concerns/smooch_messages.rb, test/models/bot/smooch_3_test.rb
Automatically associate a caption as a text media with the image media.
References: CV2-5250
=> CV2-5250: Associate a caption as a text media with the media item

app/models/concerns/smooch_search.rb, app/resources/api/v2/feed_resource.rb, test/controllers/feeds_controller_test.rb
- Introduced `skip_cache` parameter to Feed API, allowing requests to bypass the similarity search cache when set to `true`.
- Updated `search_for_similar_published_fact_checks` in `SmoochSearch` to support cached and non-cached search logic.
- Added `search_for_similar_published_fact_checks_no_cache` method to perform non-cached similarity searches.
- Modified `FeedResource` to handle and pass the `skip_cache` parameter.
References: CV2-2400
Ensured all existing tests are still passing
Check if anything was missed
=> Add skip_cache parameter to bypass similarity search cache in Feed API

app/graph/types/team_type.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_11_test.rb
This new field allows partners to use the API to export tipline requests for a given time interval. For now, limiting to one month for performance reasons.
Reference: CV2-5238.
Automated tests added.
=> Adding a new GraphQL field `tipline_requests` to `TeamType`.

lib/check_search.rb
For some report_design annotations the `last_published` date not exits so fallback to `updated_at` for the annotation
References: CV2-5301
=> CV2-5301: fallback to update_at date in case last_published not exist

app/models/relationship.rb, test/models/relationship_test.rb
Move all Explainers from the target to the source  when user match two items or pin another item.
References: CV2-5532
=> CV2-5532: Move all Explainers from the target to the source

.codeclimate.yml, .rubocop.yml, app/graph/types/team_statistics_type.rb, app/graph/types/team_type.rb, app/models/bot/alegre.rb, app/models/tipline_request.rb, db/migrate/20241015223059_add_index_to_created_at_for_articles.rb, db/schema.rb, lib/check_data_points.rb, lib/relay.idl, lib/team_statistics.rb, public/relay.json, test/controllers/graphql_controller_11_test.rb, test/lib/team_statistics_test.rb
GraphQL API responsible for returning the workspace statistics for the data dashboard. Steps:
References: CV2-5389, CV2-4111.
Automated tests implemented for all methods. Make sure that all fields filter by team, date and optionally language and platform (for tiplines).
=> Data dashboard GraphQL API

app/models/concerns/smooch_messages.rb
Case 1: Link + Message Text - Instead of concatenating the URL and the text to be the same content of both tipline requests, let’s separate this:
- The request associated with the link media contains only the link
- The request associated with the text media contains only the text
Case 2: Media + Caption - We should apply the same solution for media + caption:
- The request associated with the media contains only the media
- The request associated with the caption contains only the text
References: CV2-5529
- Etc.
=> CV2-5529: de-duplicate requests for matched items

app/models/concerns/smooch_messages.rb
Make the request for the caption item (confirmed item for media type) to be caption text instead of link.
References: CV2-5529
=> CV2-5529: Fix requests for caption item(confirmed item for media item)

app/models/relationship.rb, test/models/relationship_2_test.rb, test/models/relationship_test.rb
When moving an item to be similar to another one, delete the ones that are already related to the new target.
References: CV2-5224
=> CV2-5224: Delete duplicate relationships when exporting an item to another one

app/lib/check_cached_fields.rb, app/models/concerns/project_media_cached_fields.rb
For the updated cached field use object ID instead of sending the whole object.
References: CV2-5601
=> CV2-5601 use object id for update cached field

config/locales/en.yml, lib/team_statistics.rb, test/lib/team_statistics_test.rb
This way, the API client can manipulate it better, for example, translate to another language or get the color associated with it.
Reference: CV2-5389.
Automated test updated to cover these changes.
=> Team statistics by rating should return the rating ID, not the label.

app/models/bot/smooch.rb, app/models/tipline_resource.rb
Adding emojis and also showing the date/hours information.
Reference: CV2-5456.
This is a prototype feature. It's behind a feature flag.
=> Updating the format of the tipline message for the Civic API integration.

app/models/bot/alegre.rb, test/models/bot/alegre_test.rb
Better log when and why a relationship is downgraded from a confirmed match to a suggestion. When downgrading for an "old" match, use `last_seen`, not `created_at`
References: CV2-5558
- Etc.
=> CV2-5558: Downgrade based on last_seen, not created_at; add better logging

lib/check_search.rb, test/controllers/elastic_search_5_test.rb, test/controllers/graphql_controller_2_test.rb
Simplify and get rid of the show_parent? logic so search all items and either show parent or secondary items based on `show_similar` option
i.e show_similar = false then show parent items only otherwise show secondary items
References: CV2-5608
=> CV2-5608: remove show_parent? method

test/lib/check_config_test.rb, test/models/bot/smooch_6_test.rb, test/models/bot/smooch_7_test.rb
Add missing tests to back test coverage to 100%.
References: CV2-5621
=> CV2-5621: Add missing tests

app/graph/types/team_type.rb, test/controllers/graphql_controller_11_test.rb
Make sure that only super-admins can access the `TeamType.statistics` field.
Reference: CV2-5401.
I implemented an automated test for this.
=> Feature flag for data dashboard

lib/check_search.rb, test/controllers/elastic_search_5_test.rb, test/controllers/graphql_controller_2_test.rb
Search for similar items only if `show_similar` flag is explicitly passed
Fixes: CV2-5608.
Automated tests updated.
Please make sure you agree with this approach.
=> Search for similar items only if `show_similar` flag is explicitly passed

app/models/relationship.rb, test/models/relationship_2_test.rb
* Previously: We have items A and B. B has a published report. If we try to add B as similar to A it's going to fail because B has a published report.
* Now: Move the fact-check from B to A if A doesn't have a fact-check. Remain failing if A already has a fact-check.
Reference: CV2-5652.
An extensive automated test was implemented for this.
=> Move claim/fact-check/report from child to parent when creating relationship if child has a published report but the parent doesn't

app/models/claim_description.rb, test/models/fact_check_test.rb
Previously, we were already changing the report status to "paused" when a fact-check was removed from item. This PR does one more thing: also resets all text fields related to the report, in order to avoid similarity matches that shouldn't happen.
Reference: CV2-5630.
TDD. I implemented a new unit test for this case. The test failed before the fix.
=> Reset report text fields when fact-check is removed from item.

lib/team_statistics.rb
It should be the article ID, not the media cluster ID.
Fixes: CV2-4111.
=> Fixing the ID returned by statistics field "top articles sent".

lib/check_search.rb, test/lib/check_search_test.rb, test/lib/tasks/statistics_test.rb, test/lib/team_statistics_test.rb
Issue: Search input containing special characters (e.g., %, &, /) was causing inconsistent matches.
Fix: Added preprocessing step to remove special characters from the input query using Ruby’s `gsub`. This keeps letters, numbers, and spaces intact, enhancing match accuracy across multiple languages.
Reference: CV2-5672.
I added a couple of unit tests for this case.
It should work for non-Latin languages like Japanese and Arabic as well.
=> Improve search matching by stripping special characters from input

app/models/concerns/project_media_cached_fields.rb, test/models/fact_check_test.rb
Make sure that the `fact_check_*` cached fields for a `ProjectMedia` are refreshed when a fact-check is detached from that item.
Fixes: CV2-5600.
TDD. I was able to reproduce the issue in a unit test that passed after the fix.
=> Update item cached fields when detaching fact-check.

app/models/cluster.rb, app/models/relationship.rb, db/migrate/20241123001206_add_unique_index_to_relationships_table.rb, db/migrate/20241123135242_add_trigger_to_relationships_table.rb, db/schema.rb, lib/tasks/migrate/20230216030351_delete_duplicate_relationships.rake, test/models/bot/smooch_3_test.rb, test/models/relationship_2_test.rb, test/models/relationship_test.rb
Make sure that items can belong to maximum one media cluster. Steps:
Reference: CV2-5653.
Unit tests implemented.
=> Make sure that items belong to only one media cluster

app/graph/types/team_type.rb, app/graph/types/tipline_search_result_type.rb, app/lib/tipline_search_result.rb, app/models/explainer.rb, app/models/fact_check.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_11_test.rb
Add a bot_query field to TeamType which will send queries to the backend simulating tipline bot queries.
Initially, this is returning the most recent Explainers/FactChecks as TiplineSearchResults, but eventually it will be hooked to the actual bot implementation.
References: CV2-5702
- Confirmed that the most recent explainers/fact checks
=> Bot Preview: Initial backend implementation

app/models/concerns/smooch_search.rb
Make sure that tipline searches can match items with media type "blank".
Fixes: CV2-5526.
Manually. Searching by keyword for a blank media item in my local tipline.
=> Make sure that tipline searches can match items with media type "blank".

app/models/relationship.rb, lib/tasks/migrate/20220224213611_fix_parent_id_for_suggested_items.rake, lib/tasks/migrate/20230725053637_add_unmatched_to_project_medias.rake, test/models/relationship_test.rb
Update `parent_id` field in ES for source and target items after user pin a project media item .
References: CV2-5717
=> CV2-5717: update es parent_id after pin another item

app/models/concerns/smooch_resend.rb, test/models/bot/smooch_6_test.rb
To help reduce the number of spam reports and avoid reduction in quality scores we should allow users to unsubscribe from a newsletter when delivered. As far as Check API is concerned, this means supporting WhatsApp newsletter templates that have an "unsubscribe" button.
References: CV2-5252.
Steps:
=> Support WhatsApp newsletter templates with an "unsubscribe" button

app/models/concerns/smooch_resend.rb
When a tipline user is interacting with the bot in a certain language but clicks on the "Unsubscribe" button from a newsletter, the affected subscription should be the one related to the newsletter language, not the current language.
So, the first here is to use the language stored in the delivered message reference, not the current language, which is still used as a fallback.
Fixes: CV2-5252.
=> "Unsubscribe" the user from the newsletter language, not the current language

app/models/bot/alegre.rb, app/models/explainer.rb, test/models/explainer_test.rb
Use workspace similarity settings for explainers instead of hard-coded 
References: CV2-5617
=> CV2-5617: use workspace similarity settings for explainers

app/controllers/test_controller.rb, config/routes.rb, test/controllers/test_controller_test.rb
- Create_imported_standalone_fact_check method in TestController to create a standalone and published fact check and associate it with a team.
- Updated `routes.rb` to include the new endpoint for fact checks.
- Added tests for the create_imported_standalone_fact_check
Reference: CV2-5737
- tested with unit tests for the new method
=> Add Helper Method to Create and Publish Standalone Fact Checks for Check Web Testing

app/models/project_media.rb, test/models/project_media_7_test.rb
When handling existing media to determine whether the imported fact-check will be added to or appended to the existing media, there was a scenario where the media already contained a fact-check in the same language being imported. In that scenario, nil was being returned. This PR fixes the issue by ensuring that a new object is returned in such cases, allowing the validations to handle whether the object is persisted or fails.
Fixes: CV2-5804.
TDD. I added a unit test that was able to reproduce the issue.
=> Ensure that null is not returned as the item when creating an imported fact-check with original media in the GraphQL API.

app/models/bot/alegre.rb
We have a minor, persistent Sentry error where we are sending null items from Check API to Alegre (and eventually Presto) to match them for similarity. This ticket skips those cases, as it ought to, to stop unnecessary work and stop the minor error stream.
References: CV2-5789
I added a PR and deployed for Presto to get more instrumentation with regards to the origin of null vectorization requests. They came through as vanilla requests for encoding against `original_title` and `original_description` fields as we do in these lines. This is likely the predominant candidate for where this happens. I tried to look for a more "unified" approach but couldn't quite come up with some generic preflight check that didn't end up just adding more complexity than was warranted.
Any other candidates? …
=> CV2-5789 dont send null values out to presto from check-api

lib/check_search.rb, test/lib/check_search_test.rb
Similarly to CV2-5672. Adding single quote (`'`) to the list of characters to keep when normalizing query for keyword search.
Fixes: CV2-5808.
Unit test added.
=> Keep single quote when normalizing query for keyword search.

app/models/explainer.rb
Utilize fact-check sorting based on the search model and score to standardize the sorting for FactCheck and Explainer.
References: CV2-5779
=> CV2-5779: Use the same sort for FactCheck and explainer

app/models/explainer.rb, lib/check_data_points.rb, lib/tasks/migrate/20241216215050_set_language_for_explainers.rake, lib/team_statistics.rb, test/lib/team_statistics_test.rb, test/models/explainer_test.rb
Some fixes and changes for the data dashboard backend:
Existing tests were updated to cover the changes.
=> Fixes and changes for the data dashboard backend

app/graph/types/team_type.rb, test/controllers/graphql_controller_11_test.rb
Removes the feature flag from the data dashboard GraphQL field.
This reverts commit ca41cdcf52fd41a91c2d1b827dc9f4c20781fadd.
Reference: CV2-5788.
Automated test updated.
=> Removes the feature flag from the data dashboard.

app/models/concerns/smooch_search.rb, app/models/project_media.rb, app/models/team.rb, app/resources/api/v2/feed_resource.rb, test/controllers/feeds_controller_test.rb, test/models/project_media_7_test.rb
Apply the following changes for most relevant articles.
References: CV2-5846
=> CV2-5846 updates to back-end functions to support recent to relevant

app/models/concerns/smooch_messages.rb, test/models/bot/smooch_7_test.rb
We saw an error in Sentry where the creation of a `Relationship` between a `ProjectMedia` and a `TiplineResource` was attempted. The creation fails, but it should not be attempted in the first place.
**Error**
- `StandardError`
- `Unable to create new relationship as requested: Related items must exist in the same workspace`
- exception_class: `ActiveRecord::RecordInvalid`
- exception_message: `Related items must exist in the same workspace`
**For this to happen**
- The media can't be of type `text`, because we do check if it's a `ProjectMedia` in that case,
- it needs to have a `caption`,
- there needs to be an existing `ProjectMedia` with the same `id` as the `TiplineResource`,
- if there isn't a  `ProjectMedia` with the same `id` as the `TiplineResource` we get a different error: …
=> Smooch Bot should not create a relationship between Media and TiplineResource

app/models/team_bot_installation.rb, test/models/team_bot_installation_test.rb
The bot_user method in the TeamBotInstallation model was previously using the `where(...).last` approach to fetch the BotUser, which could result in unnecessary database queries when called multiple times. This fix optimizes the method by replacing `where(...).last` with `find_by(id: ...)`, ensuring only a single query is executed per call.
Changes:
- Replaced `where(...).last` with `find_by(id: ...)` in the `bot_user` method.
- Added a test to verify that no extra queries are triggered when calling `bot_user`.
References: CV2-5848
A test has been added to verify that no additional queries are triggered when accessing the `bot_user` method multiple times on the same instance, ensuring that the optimized code works as expected and prevents potential N+1 query issues.
=> Fix N+1 query issue in bot_user method by using find_by

app/models/relationship.rb, config/initializers/version.rb, test/models/relationship_2_test.rb
Imagine we have items A and B. B has a similar item C. If B is added as similar to A, then C will also be moved from B to A.
Previously, in that operation, the user who created the relationship between B and C would be set as the user who created the relationship between A and C, but that's problematic - for example, it can prevent reports from being sent.
The fix here is to set that the user who created the new relationship between A and C is not the same user who created the relationship between B and C, but instead, it's the user who created the relationship between A and B.
Fixes: CV2-5837.
TDD. I was able to reproduce in a unit test:
```
Failure:
Relationship2Test#test_should_set_current_user_when_moving_targets_to_new_source [test/models/relationship_2_test.rb:504]:
--- expected
+++ …
```
=> Make sure that the current relationship user overwrites the previous user when moving targets to a new source

config/tipline_strings.yml
Regenerate translations to add  missing translations for the `no_results_in_language` string.
References: CV2-5790
- Confirmed that the strings appear as expected in tipline responses
=> Regenerate Transifex translations

app/models/annotations/dynamic.rb
If a `ProjectMedia` is deleted, handling task information about it is useless. So, return early in this case.
Fixes: CV2-5989.
Existing tests should still pass.
=> Return early from method if the item doesn't exist anymore.

app/models/concerns/smooch_search.rb, app/models/project_media.rb, test/models/project_media_7_test.rb
Use OCR information for image item instead of transaction information.
References: CV2-5847
=> CV2-5847: Use OCR information for image item

app/graph/mutations/claim_description_mutations.rb, app/models/claim_description.rb, lib/relay.idl, lib/sample_data.rb, public/relay.json, test/models/claim_description_test.rb
Adding an accessor `enable_create_blank_media` to the `ClaimDescription` model, and a `before_create` callback that reads that accessor value and creates and associate the claim with a blank item if needed. When set to `true` (default is `false`), the claim is associated with a blank item when it's not associated to any item.
Also exposed as an argument for the claim description GraphQL mutations.
Reference: CV2-5900.
Automated test added.
=> Adding an accessor `enable_create_blank_media` to the `ClaimDescription` model.

lib/tasks/migrate/20250113231210_add_blank_media_to_standalone_fact_checks.rake
Adding a rake task to migrate standalone fact-checks by adding blank media to them. How to run the rake task:
```
rake check:migrate:add_blank_media_to_standalone_fact_checks
```
Reference: CV2-5900.
I executed the rake task locally and migrated 104 fact-checks:
```
$ rake check:migrate:add_blank_media_to_standalone_fact_checks
[2025-01-14 02:21:27 +0000] [1/104] Added blank media to claim #425
... 102 lines ...
[2025-01-14 02:27:00 +0000] [104/104] Added blank media to claim #643
[2025-01-14 02:27:00 +0000] Done in 5 minutes. Number of standalone fact-checks without blank media: 0
```
Running it a second time shouldn't find any case to migrate.
- I didn't bother to improve the performance too much, or do migrate per team, since in production we have just a few cases (see referenced …
=> Adding a rake task to migrate standalone fact-checks by adding a blank media them

app/models/concerns/smooch_messages.rb, test/models/bot/smooch_3_test.rb
Fixing an  error that happens when the URL cannot be parsed. Instead of throwing an exception, we are now checking whether the link contains a URL first before attempting to use the URL.
References: CV2-5927
- Confirmed that tests pass successfully
=> Fix nil:NilClass error when parsing Link smooch messages

app/models/user.rb, test/models/user_test.rb
When we have a user sign in with their email, and then sign in using multiauth we need to merge the users. When the user had created an explainer this was causing an issue, which was fixed by adding `has_many :explainers` to the User model.
This fixes it, because of these two lines we run in `merge_with`:
```
all_associations = User.reflect_on_all_associations(:has_many).select{|a| a.foreign_key == 'user_id'}
all_associations.each do |assoc|
assoc.class_name.constantize.where(assoc.foreign_key => user.id).update_all(assoc.foreign_key => self.id)
end
```
References: CV2-5926
We create a test inside user_test.rb "when merging should be able to destroy a user even if they created an explainer": `rails test test/models/user_test.rb:1413`
Please describe parts of the change that require extra …
=> Bug – 5926 – Update foreign key on explainer

app/models/team.rb, lib/url_rewriter.rb, test/models/team_test.rb
Make sure that the URL shortening setting returns as "enabled" even when it's not explicitly enabled but there are active RSS newsletters.
Fixes: CV2-5998.
TDD. I implemented a unit test that reproduces the error.
=> Make sure that the URL shortening setting returns as "enabled" even when it's not explicitly enabled but there are active RSS newsletters

app/models/project_media.rb, test/models/relevant_results_item_test.rb
Logged two issues while testing on QA.
- user_action value: should be `relevant_articles` for relevant search selection
- selected_count: should be 1 for the selected article otherwise 0
References: CV2-5668
=> CV2-5668: fix user_action and selected_count values

app/models/team.rb, test/models/team_2_test.rb
This PR implements two things:
* Case 1: Info-level logging when no relevant articles are returned.
* Case 2: Notify Sentry when there is an error retrieving relevant articles. In that case:
* Catch the error and return an empty list, so it doesn't crash the frontend, which can then fallback to recent articles.
* Log a warning.
* Notify Sentry. The Sentry message is static and implements a custom exception class, so similar notifications can be grouped together automatically, but includes all information we need in order to debug.
Reference: CV2-5932.
Automated test implemented. I tested it manually too.
=> Log and notify Sentry when relevant articles are not retrieved.

lib/check_search.rb, test/lib/check_search_test.rb
This new value `social_media` is basically a shortcut for all the possible social media types.
Reference: CV2-4980.
I implemented a unit test for that.
=> Adding `social_media` value to media type search filter.

app/models/concerns/project_media_creators.rb, app/models/media.rb, db/migrate/20250122171640_add_original_claim_to_medias.rb, db/migrate/20250124155814_add_original_claim_to_media.rb, db/schema.rb, test/models/media_test.rb, test/models/project_media_7_test.rb
To debug items created using the API (e.g., through the Zapier integration), improve performance, and avoid duplications, it is important to store the `original_claim_url` in the `Media` object created when this attribute is present.
When a `ProjectMedia` is created (e.g., via a GraphQL mutation) and the `original_claim` attribute (a URL) is provided, a new `Media` instance is created from that URL and associated with the `ProjectMedia` instance. Currently, the reference between the original claim and the created media is lost. This reference needs to be stored.
References: CV2-6021
"should save the original_claim url and original_claim_hash when Link Media is created from original_claim"
`rails test test/models/project_media_7_test.rb:200`
"should save the original_claim text and …
=> feature – 6021 – Store original claim in Media object

app/models/concerns/alegre_v2.rb
Notify Sentry when request to Alegre fails.
Fixes: CV2-6070.
Tested locally. The most important thing is to test on QA once merged.
=> Notify Sentry when request to Alegre fails.

app/models/bot/smooch.rb
Fix N+1 query by implemented a single query to get alegre & smooch bots.
References: CV2-6079
=> CV2-6079: Fix N+1 query for BotUser query

app/models/annotations/dynamic.rb, app/models/bot/smooch.rb, app/models/dynamic_annotation/field.rb, app/models/workflow/verification_status.rb, test/models/bot/smooch_2_test.rb
Add a flag to enforce change the status while the report is published.
References: CV2-6040
=> CV2-6040: Enforce change the status while the report is published

app/graph/types/team_type.rb, app/models/team.rb, lib/relay.idl, public/relay.json
Adding a new filter to the GraphQL fields `TeamType.articles` and `TeamType.articles_count`: "created" date.
Reference: CV2-5851.
I just tested manually using the web client (branch with the same name as this). I didn't add automated tests because it's mostly declarative and/or only calls methods that are already tested.
=> Filter articles by "created" date.

app/lib/check_elastic_search.rb, app/models/annotations/embed.rb, app/models/claim_description.rb, app/models/concerns/project_media_cached_fields.rb, app/models/concerns/project_media_getters.rb, app/models/explainer_item.rb, app/repositories/media_search.rb, app/workers/elastic_search_worker.rb, db/migrate/20250205224319_add_mapping_for_explainer_title_field.rb, lib/check_search.rb, lib/tasks/migrate/20250205224319_add_mapping_for_explainer_title_field.rake, test/controllers/elastic_search_7_test.rb, test/controllers/elastic_search_9_test.rb
Refactor has_claim filter to include both FactCheck & Explainer
References: Cv2 6038
=> CV2-6038 refactor has claim search filter into has article filter

app/graph/types/query_type.rb, test/controllers/graphql_controller_11_test.rb
Don't crash when a GraphQL-requested workspace (with the `random` argument) doesn't exist.
Reported by Sentry.
Fixes: CV2-6151.
TDD. Reproduced in a unit test that passed after the fix:
```
Failure:
GraphqlController11Test#test_should_not_crash_if_workspace_doesn't_exist [test/controllers/graphql_controller_11_test.rb:397]:
Expected response to be a <2XX: success>, but was a <400: Bad Request>
Response body: {"errors":[{"message":"undefined method `reload' for nil:NilClass","code":5,"data":{}}]}
```
=> Don't crash when a GraphQL-requested workspace (with the `random` argument) doesn't exist

app/models/concerns/alegre_v2.rb, test/models/bot/alegre_4_test.rb
This commit fixes an error reported by Sentry.
Fixes: CV2-6150.
TDD. I reproduced it in a unit test that passed after the fix:
```
$ docker-compose exec api bundle exec ruby test/models/bot/alegre_4_test.rb -n /package/
Error:
Bot::Alegre4Test#test_should_not_try_to_store_package_for_blank_item:
NoMethodError: undefined method `store_package_' for Bot::Alegre:Class
Did you mean?  store_package
store_package_text
```
=> Don't try to store an Alegre package for an item of "blank" type.

app/models/team.rb
For the articles' "updated_at" filter, consider only articles that were actually modified after they were created. By default, it currently includes articles that were created but never changed.
Fixes: CV2-5851.
Manually check using Check Web. Ensure that you can filter articles by the "Item updated" date filter and that it does not include articles that were created but never changed.
=> Updating How the Articles' "updated_at" Filter Works

app/graph/types/project_media_type.rb, app/models/concerns/project_media_getters.rb, lib/tasks/data/text_similarity_data.rake
Adding a new rake task that exports text similarity data from a set of workspaces and generates a JSON file output uploaded to an S3 bucket.
References: CV2-6069 and CV2-6030.
Manually... just execute the rake task this way:
```
bundle exec rake check:data:text_similarity_data['s3_bucket_name=s3_bucket_name&workspace_slugs[]=workspace-slug-1&workspace_slugs[]=workspace-slug-2&...&workspace_slugs[]=workspace-slug-n']
```
=> Rake task to export text similarity data

app/models/claim_description.rb, app/models/concerns/team_associations.rb, app/models/fact_check.rb, lib/tasks/migrate/20230130074014_add_mapping_for_keyword_search_fields.rake, lib/tasks/migrate/20250205224319_add_mapping_for_explainer_title_field.rake
Add rake tasks to migrate existing FactCheck.
References: CV2-6038
=> CV2-6038: add rake task to migrate existing FactCheck

app/graph/types/team_statistics_type.rb, lib/check_data_points.rb, lib/relay.idl, lib/team_statistics.rb, public/relay.json, test/lib/team_statistics_test.rb
Reference: CV2-5849.
A unit test was updated to cover these two new fields. The total number of messages (existing field) should correspond to the sum of incoming plus outgoing messages (two new fields added by this PR).
=> Adding a couple of new tipline statistics data points: number of incoming messages and number of outgoing messages

app/graph/types/team_statistics_type.rb, lib/relay.idl, lib/team_statistics.rb, public/relay.json, test/lib/team_statistics_test.rb
The two new data points are for "number of incoming messages by day" and "number of outgoing messages by day".
Reference: CV2-5849.
Automated test update to cover these new data points.
=> Adding two new data points for the data dashboards.

app/graph/types/team_type.rb, app/models/team.rb, lib/relay.idl, public/relay.json, test/models/team_2_test.rb
The field returns the platforms for which analytics are available. The logic is: there is at least one media request for that platform.
Reference: CV2-5821.
I implemented an automated test for that.
=> Adding a `statistics_platforms` field to GraphQL `TeamType`.

.rubocop.yml, app/graph/types/team_type.rb, app/models/team.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_12_test.rb, test/models/team_2_test.rb
We need to add an "All Articles" list to make it easier for the users to see the entire collection of both Claim & Fact-Checks as well as Explainers under one list.
Checklist:
Reference: CV2-5007.
Automated test was added. But we need to make sure that, for the "all articles" list:
=> "All Articles" list

.github/codeql/codeql-config.yml, .github/workflows/codeql.yml, app/models/bot/tagger.rb
Fixing CodeQL Ruby warnings. Changes:
Reference: CV2-6167.
CodeQL should run without any warnings: https://github.com/meedan/check-api/actions/runs/13462695643/job/37621549981?pr=2231.
=> Fixing CodeQL warnings

app/models/bot/alegre.rb, app/models/relationship.rb, test/models/relationship_test.rb
After debugging various cases on Live, I discovered that metadata already exists, but the target is already part of another source. Therefore, based on our [method for creating relationships](https://github.com/meedan/check-api/blob/develop/app/models/relationship.rb#L161-L162), it returns the existing one without setting metadata options.
References: CV2-6141
=> CV2-6141: Update options for existing relationship

.gitlab-ci.yml
Due to issues with Python and package repositories in this Docker image, we have to revert version pins back a major version. Attempting to update pip itself, which is also out of date, did not resolve the issue.
References: https://meedan.atlassian.net/browse/CV2-6218
Verify with a successful deployment to QA.
=> Set version pins for Python 3.7.7 docker image.

app/models/relationship.rb, test/models/relationship_test.rb
There is a case for `create_unless_exists` that attempts to establish a confirmed relationship and there is a suggested relationship for the same source and target, and also go through [this case](https://github.com/meedan/check-api/blob/develop/app/models/relationship.rb#L168-L173).
so it same relationship exists but suggested then I'll update existing one to be confirmed.
References: CV2-6041
Implemented unit test
=> CV2-6041: update suggested relation if new one is confirmed

app/graph/types/team_bot_installation_type.rb, app/models/concerns/smooch_strings.rb, app/models/concerns/smooch_team_bot_installation.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_7_test.rb
This new field returns the translated default messages for supported workspace languages.
Reference: CV2-4994.
I implemented an automated test for this.
=> Add `smooch_default_messages` field to `TeamBotInstallationType` in GraphQL API

app/models/concerns/project_media_cached_fields.rb, test/models/project_media_8_test.rb, test/models/relationship_test.rb
The media origin for a media item added to a media cluster by the Smooch Bot was set to "user merged" when it should have been "auto merged," since the Smooch Bot is, after all, a bot. The fix expands the "auto merged" case to include not only the Alegre Bot but any bot.
Fixes: CV2-6205.
TDD. I was able to reproduce the bug in a unit test.
=> Fixing the media origin for an item added to a media cluster by the Smooch Bot

app/models/concerns/alegre_v2.rb, app/models/feed.rb, app/models/request.rb, app/models/team.rb, test/models/team_2_test.rb
Also, fixing some other Sentry errors.
Reference: CV2-6250.
I was able to reproduce in a unit test:
```
$ docker-compose exec api bundle exec ruby test/models/team_2_test.rb -n test_should_get_filtered_articles_by_keyword
Error:
Team2Test#test_should_get_filtered_articles_by_keyword:
ActiveRecord::PreparedStatementInvalid: wrong number of bind variables (2 for 4) in: SELECT type, id, title, language, created_at, updated_at FROM ( SELECT 'FactCheck' AS type, "fact_checks"."id", "fact_checks"."title", "fact_checks"."language", "fact_checks"."created_at", "fact_checks"."updated_at" FROM "fact_checks" INNER JOIN "claim_descriptions" ON "claim_descriptions"."id" = "fact_checks"."claim_description_id" WHERE "claim_descriptions"."team_id" = 4 AND "fact_checks"."trashed" = FALSE AND …
```
=> Make sure that question marks in filtered articles query is not interpreted as a binding variable

db/migrate/20250312190444_set_listed_to_false_for_fetch_bot.rb
Fetch is deprecated and should not be shown in the workspace. We have already removed Fetch specific code from Check-Web. But it still renders the generic parts, if the `api` sends it.
We have a boolean attribute called `listed`. Which was implemented [here](https://github.com/meedan/check-api/commit/d0cd2747bc035aebbd33a9bae3bf60fc5ebe15b8). `Listed` bots are the ones that are displayed to users so they can install in their workspaces.
Since we don't want to show Fetch we can update it's `listed` attribute to "false", so it won't be displayed anymore. Note that Fetch `listed` attribute is already set to `false` in check live. We want it to be set t false regardless of environment.
References: CV2-4916
=> 4916 – Change 'listed' attribute so we do not display Fetch

app/models/feed.rb
Comparing two arrays by using equal operator ( i.e `team_ids != self.team_ids` ) require same sort for two arrays.
for example [5, 73] != [73, 5] return wrong result so I replaced this code by diff i.e (team_ids - self.team_ids).empty?
References: CV2-6280
=> CV2-6280: Use diff to compare two arrays instead of equal operator

app/models/bot/smooch.rb
Fix sentry error by return nil if parent not exists
References: CV2-6262
=> CV2-6262: return nil if parent not exists

app/models/concerns/project_media_creators.rb, app/models/media.rb, lib/pender_data.rb, test/models/media_test.rb, test/models/project_media_7_test.rb
The current implementation for processing original_claim URLs in Check API does not account for situations where external URLs take an extended time to process. This can result in delays or failures if processing exceeds the gateway timeout (currently set at 60 seconds).
This mostly happens when we try to create an `UploadedFile` `Media` from an `original_claim`. So we see this a lot in our zapier integrations, where we might get `app took too long too respond` response. This happens somewhat frequently, and could obscure real issues.
- We configured a Timeout (shorter than 60s), 
- if that is exceeded, we create a `ClaimMedia` instead of `Audio/Image/VideoMedia`.
**Rethink how we `find_or_create_uploaded_file_media`**
I realized we would sometimes send the file, and sometimes send the …
=> (5995) Implement timeout and fallback for `original_claim` URL processing

Gemfile, Gemfile.lock
As part of implementing timeout and fallback for original_claim URL processing, we update read and open timeouts in the pender_client gem. So we need to update it in check-api's gemfile.
References: CV2-5995, CV2-6287
Relates to: PR https://github.com/meedan/check-api/pull/2243, PR https://github.com/meedan/pender-client/pull/1
=> 5995/6287 – Update pender_client gemfile

db/migrate/20250328140809_allow_nil_article_channel.rb, db/schema.rb, test/controllers/graphql_controller_12_test.rb
While QA'ing we noticed that the channel for `Explainer` was set to `manual` even when it was create by a `BotUser`.
This happened because `default` is apllied when the object is instantiated. So we are removing the constraint from the database and allowing nil values.
References: CV2-6039
```ruby
rails test test/controllers/graphql_controller_12_test.rb:1023
```
=> 6039 – Make sure the channel is set correctly

app/models/concerns/smooch_capi.rb, app/models/concerns/smooch_menus.rb, app/models/concerns/smooch_messages.rb, app/models/concerns/smooch_zendesk.rb, test/models/bot/smooch_7_test.rb, test/models/concerns/smooch_zendesk_test.rb
Create a placeholder variable like {{message_id}} that can be included in a tipline message.
References: CV2-6146
Implement unit test.
=> CV2-6146: Add a message/conversation_id placeholder

lib/tasks/data/delete_team_tags.rake
Add rake task to delete all team tags.
`bundle exec rails check:team:delete_tags[slug-1,slug-2,...,slug-N]`
References: CV2-6290
Run rake task locally
=> CV2-6290: Add rake task to delete team tags

app/graph/types/team_type.rb, lib/relay.idl, public/relay.json, test/controllers/graphql_controller_12_test.rb
We updated the argument type to be an Array of Strings, so we are able to query for different channels at once. 
References: CV2-6039
```
rails test test/controllers/graphql_controller_12_test.rb:933
```
=> 6039 – Enable API to query multiple channels at once

.codeclimate.yml, .rubocop.yml, app/models/concerns/project_media_creators.rb, app/models/concerns/smooch_team_bot_installation.rb, config/initializers/version.rb, config/locales/en.yml, config/tipline_strings.yml, lib/tasks/migrate/20250326140624_add_channel_to_articles.rake
Previously, we were returning the hard-coded tipline strings. Now, we're returning the list of customizable tipline strings.
Reference: CV2-6304.
Check the `smooch_default_messages` method of a `TeamBotInstallation` object (or the respective GraphQL field).
=> Returning the list of default tipline strings in different languages.

app/models/concerns/alegre_v2.rb, test/models/bot/alegre_v2_test.rb
Ensure we don't get similar items (both sync and async) for text items that are just a URL.
References: CV2-6298
Automated test implemented.
=> Do not get similar items for text items that are just a URL

app/models/concerns/smooch_messages.rb, db/migrate/20250403200649_add_first_manual_response_at_and_last_manual_response_at_to_tipline_requests.rb, db/schema.rb, lib/check_data_points.rb, test/controllers/graphql_controller_10_test.rb, test/lib/check_data_points_test.rb
Include manual responses when calculating average response time.
Reference: CV2-5996.
Automated tests implemented.
=> Include manual responses when calculating average response time

config/tipline_strings.yml
This PR includes the Machine Translations for the customizable messages default versions.
Except for assamese (as), bhojpuri (bho), kurdish (ckb) and kashmiri (ks), which google translate did not support translating into.
References: CV2-4994
*Requires check-web:* https://github.com/meedan/check-web/pull/2337
Go to tipline settings "Content and Translation" tab and check if the default messages are shown in the selected language
=> CV2-4994: Tipline default strings Machine Translated

Gemfile, Gemfile.lock
Update to the latest version of the `pender-client` gem, so we can send a timeout value.
Relates to: https://github.com/meedan/check-api/pull/2279, https://github.com/meedan/pender-client/pull/2
References: CV2-5995, CV2-6139
=> 6139 – Update to the latest version of the pender_client

app/models/concerns/project_media_cached_fields.rb, app/models/concerns/relationship_bulk.rb, app/models/relationship.rb, db/migrate/20250408164959_remove_targets_count_from_project_media.rb, db/schema.rb, test/controllers/elastic_search_5_test.rb, test/models/project_media_test.rb, test/models/relationship_2_test.rb, test/models/relationship_test.rb
Re-implement sources_count login using cached field approach
References: CV2-6314
=> CV2-6314: Sync `sources_count` value between PG & ES

app/lib/tipline_search_result.rb
Updating the truncation logic for tipline search results to truncate article texts, matching the behavior used in WhatsApp template messages, Fetch / batch imports and the UI.
Reference: CV2-6321.
=> Truncate articles summary when sending them as tipline search results.

app/models/media.rb, config/config.yml.example, lib/pender_data.rb, test/models/account_test.rb, test/models/media_test.rb, test/models/project_media_5_test.rb, test/models/source_test.rb
When we create a media instance through Zapier (`original_claim`) we often hit a Timeout, specially when creanting Link media or File media instances. So for those cases we want our timeout to be shorter. 
References: CV2-6319, CV2-5995
=> 6319 – Update timeout when creating Media

app/models/concerns/smooch_team_bot_installation.rb, config/tipline_strings.yml
Intermediate locale fallback on `smooch_default_messages`: e.g.: If there's no `pt_BR` try `pt` before defaulting to `en`
References: CV2-4994
Go to tipline settings "Content and Translation" tab and check if the default messages are shown in the selected language. Test specifically pt_BR and pt_PT.
=> Intermediate fallback; remove blank lines from tipline_strings.yml

app/models/relationship.rb, test/lib/check_data_points_test.rb
Fixing a Code Climate issue (deleting a useless line) and fixing flaky test.
For the Code Climate issue, I deleted a line that was left by mistake as part of the `sources_count` refactoring (PR #2278).
The fix for the flaky test is to use a fixed mocked date, instead of relying on the current date, which could cause the flakyness we were seeing.
No Jira ticket for this.
I literally executed the flaky test locally 20 times after the fix.
=> Fixing Code Climate issue and fixing flaky test.

app/models/bot/smooch.rb, app/models/concerns/smooch_team_bot_installation.rb, db/migrate/20250411153835_update_smooch_bot_default_settings.rb, test/models/team_2_test.rb
Ensure that no customized strings are set when the tipline is automatically installed for a newly created workspace.
Reference: CV2-4994.
I implemented an automated test, but here's how to test it manually: Create a new workspace using Check Web, go to the tipline settings and make sure that no messages show as "customized":
[CV2-4994]: https://meedan.atlassian.net/browse/CV2-4994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update default Smooch Bot settings.

app/models/concerns/project_association.rb, app/models/concerns/project_media_creators.rb, app/models/media.rb, app/models/project_media.rb, config/config.yml.example, test/models/project_media_7_test.rb, test/models/project_media_8_test.rb
- The method `create_media!` was being called twice - once from the method `set_media` in `app/models/concerns/project_association.rb`, and again from a `before_validation` callback in `app/models/project_media.rb`. When the first one was called, the `media_type` was changed from `Blank` to something else, which then caused the conditions for the second call to be met as well.
- We could get a timeout from the `Net::HTTP.get_response` call we use to get the content type, since no timeout was set. I replaced that with `Net::HTTP.start`, which allows us to set a timeout and use a HEAD request instead, since we're only interested in the content type. It's much faster, so I hardcoded the timeouts. If a timeout occurs at that point, the type is set as `claim`.
- I added an automated test for …
=> Fixing some issues with original claim timeout handling

app/models/bot/smooch.rb, app/models/concerns/smooch_strings.rb, db/schema.rb, test/models/bot/smooch_8_test.rb
Previously, the report sent timestamp was saved before the report was actually sent, which could result in a situation where a report was not sent but the information was incorrectly recorded as if it had been. This PR fixes the issue by ensuring that the report sent timestamp is stored in the tipline request only when, and after, the report is actually sent.
Fixes: CV2-6317.
Reproduced in a unit test:
```
Failure:
Bot::Smooch8Test#test_should_update_ticker_only_when_report_is_actually_sent [test/models/bot/smooch_8_test.rb:25]:
Expected: 0
Actual: 1744732878
```
Manually:
- Send a report to a user
- Send a report correction to a user
- Send a report from the parent to the child
=> Only save the report sent timestamp when the report is actually sent.

app/graph/types/team_type.rb
Adds a sort to the verification_statuses method, for return statuses ordered alphabetically by their label field
References: CV2-6325
tested manually through the UI 
Places to cover:
Tipline: Bulk change action button in the lists view
Tipline: Within the media cluster, the statuses button
Tipline: Report editor statuses button
Tipline:  Filter > Rating is
Articles: Within the Article statuses button
Articles: Claim & Fact-Checks > Filter > Rating is
Articles: Published > Filter > Rating is
Settings: Statuses settings page
Settings: Rules page, if condition
=> Change status sorting to alphabetical order

app/graph/mutations/saved_search_mutations.rb, app/graph/types/saved_search_type.rb, app/models/saved_search.rb, db/migrate/20250419100047_add_list_type_to_saved_search.rb, db/schema.rb, lib/relay.idl, public/relay.json, test/models/saved_search_test.rb
Refactor the SavedSearch model to include a list_type attribute. This attribute should accept either media or article as values.
References: CV2-6342
Implemented automated tests
=> CV2-6342: Refactor SavedSearch to accept list_type

app/models/concerns/smooch_menus.rb, app/models/concerns/smooch_team_bot_installation.rb
Refactoring and fixing how default messages are returned to tipline users by reusing existing default messages to avoid redundancy and duplication. This also includes a fix to ensure that, when available, localized default messages are returned instead of always falling back to English.
Fixes: CV2-6346.
Before:
After:
=> Refactoring and fixing the way default messages are returned to tipline users.

app/graph/types/explainer_item_type.rb, app/models/explainer_item.rb, app/models/project_media.rb, lib/relay.idl, public/relay.json
- Exposing `dbid` in GraphQL `ExplainerItemType`.
- De-duplicating requests, so the same user doesn't receive the same explainer more than once.
- Including child items when sending explainers to previous requests.
Reference: CV2-6335.
=> Exposing `dbid` in GraphQL `ExplainerItemType` and including child items when sending explainers

app/models/tipline_request.rb, test/models/project_media_8_test.rb
Ignoring negative search result feedback when checking if a media cluster has unanswered requests.
Reference: CV2-6335.
=> Ignore negative search result feedback when checking if a media cluster has unanswered requests.

app/workers/tipline_statistics_periodic_check_worker.rb, test/workers/tipline_statistics_periodic_check_worker_test.rb
Add Sentry notification for missing tipline statistics updates in last 24 hours
References: CV2-6363
Implemented automated tests
=> CV2-6363: Add periodic check for MonthlyTeamStatistic

app/controllers/test_controller.rb, app/graph/mutations/feed_mutations.rb, app/graph/mutations/feed_team_mutations.rb, app/graph/types/feed_team_type.rb, app/graph/types/feed_type.rb, app/graph/types/saved_search_type.rb, app/models/feed.rb, app/models/feed_team.rb, db/migrate/20250515134234_rename_saved_search_id_to_media_saved_search_id.rb, db/schema.rb, test/controllers/elastic_search_10_test.rb, test/controllers/graphql_controller_7_test.rb, test/controllers/graphql_controller_8_test.rb, test/lib/list_export_test.rb, test/models/bot/smooch_5_test.rb, test/models/feed_team_test.rb, test/models/feed_test.rb, test/models/request_test.rb
This is the first part of the work to add Articles as Available Data to Share when creating a shared feed. This is a refactoring to rename `saved_search` to `media_saved_search`. We did this because `Feed` and `FeedTeam` can store a single reference to a list (saved search), which is assumed to be a media list. We want Feeds to be able to reference `media_saved_search` and `article_saved_search`. We had to make changes in the model and graphql layer.
This is a refactoring to keep the current behavior, we didn't change how the API works, so nothing should change in the frontend. Though, we need to test thoroughly to make sure nothing broke.
References: CV2-5271, CV2-6369
I added to new tests to confirm we could get the saved_search and saved_search_id from Feed and FeedTeam:
- rails test …
=> 5271 – 6369 – Refactor to make current feed list explicitly a media list

app/models/concerns/team_duplication.rb, app/models/concerns/team_private.rb, test/models/team_test.rb
When duplicating teams, we were copying the bots from the original team into the new team. But that was causing issues, e.g.:
- We create a team with a bot that has an API key to import items
- We duplicate the team, which duplicates the bot and API key
- Now we might think we are importing items to the original team, but we are actually importing them to the duplicated team
In order to avoid different teams with same API keys, instead of copying the original team's bots, we want to just install any default bots. To do that, we just need to run the `add_default_bots_to_team` `after_create` callback even if `is_being_copied`.
References: CV2-3942 , CV2-5876
```ruby
rails test test/models/team_test.rb:903
```
Note: I replaced `setup_smooch_bot` with `create_bot_user`, since the former is …
=> 3942 – Avoid unwanted TeamBotInstallations when duplicating workspaces

lib/check_statistics.rb, test/lib/check_statistics_test.rb
We should stop retrieving WhatsApp conversation data, so I stopped calling the API and instead return '-'.
References: CV2-6430
=> CV2-6430: Stop retrieving WhatsApp conversation data

Dockerfile, production/Dockerfile
- Update key/value format
- Legacy key/value format with whitespace separator should not be used
("ENV key=value" should be used instead of legacy "ENV key value" format)
- Update to use Label
- MAINTAINER has been deprecated
References: CV2-6469
=> 6468 – 6469 – Update Dockerfile syntax

app/controllers/api/v1/graphql_controller.rb, lib/permissions_loader.rb, test/controllers/elastic_search_2_test.rb, test/controllers/elastic_search_7_test.rb, test/controllers/elastic_search_9_test.rb, test/controllers/graphql_controller_10_test.rb, test/controllers/graphql_controller_12_test.rb, test/controllers/graphql_controller_2_test.rb, test/controllers/graphql_controller_8_test.rb
The existing code skips GraphQL authentications for any query start with `query  ...`  and certain mutations like `resetPassword|changePassword|resendConfirmation|userDisconnectLoginAccount`. 
I modified this behavior to only skip `query Me`  along with the existing mutations and required authentication for other graphql quires. 
References: CV2-6510
=> CV2-6510: Require authentication for all graphql quires except `query Me`

app/models/bot/keep.rb, app/models/concerns/project_media_creators.rb, app/models/project_media.rb, test/models/bot/keep_test.rb, test/models/project_media_5_test.rb
Removes code related to Pender's deprecated social metrics feature.
References: CV2-6518, CV2-4226
=> 6518 – Removes code related to Pender's deprecated social metrics feature

app/models/bot_user.rb, app/models/concerns/team_associations.rb, app/models/team_bot_installation.rb
We are encountering an N+1 query issue when loading `team_bot_installations.bot_user`. The code requires both `team_bot_installation` and `team_bot_installations.bot_user`, so I can't load the data with a single query. One suggestion to avoid the N+1 query is to use `.includes` when loading the team object.
References: CV2-6550
=> CV2-6550: N+1 query (BotUser)
