meedan/check-api

app/models/ability.rb
test/models/status_test.rb

Allow journalist to change status of own report

Ticket #5231 - new permissions for journalist

---

app/models/ability.rb
test/models/team_user_test.rb

Don't allow any user to change their own role in a team

Ticket #5172

---

app/models/media.rb
test/models/embed_test.rb
test/models/media_test.rb

Fix two embed annotations for media creation and add test case to verify this issue

Ticket #5301

---

app/models/ability.rb
test/controllers/graphql_controller_test.rb
test/models/ability_test.rb
test/models/tag_test.rb

Ticket #5251

---

app/models/ability.rb
test/models/ability_test.rb

Allow team members to delete tags

Ticket #5266

---

app/models/user.rb
test/models/user_test.rb

I removed the tests because the spec keeps changing, hard to know what's required.

Better email handles #5343

---

app/models/ability.rb
test/models/ability_test.rb
test/models/status_test.rb

- Journalist: Can change verification status for any report
- Journalist: Can add, delete tags (including EL categories) for any report

Ticket #5373

---

app/models/project_media.rb
db/migrate/20161104183828_add_initial_status_to_media.rb
test/controllers/graphql_controller_test.rb
test/models/project_media_test.rb

Created a new annotation `undetermined` when `ProjectMedia` created

Ticket #5390

---

lib/check_search.rb
test/models/check_search_test.rb

Use "AND" operations instead of "OR" for multiple keywords search

Ticket #5397

---

lib/check_search.rb

Change aggregation size to be 10000

Ticket #5394

---

lib/check_search.rb
test/models/check_search_test.rb

Just need to use integer key `.to_i`

Ticket #5494

---

lib/check_search.rb
test/models/check_search_test.rb

Include change status and add flag to recent activity sort

Ticket #5405

---

config/initializers/newrelic.rb

Adding initializer for GC Stat collection in Ruby

Update NewRelic for GC Stats

---

app/models/concerns/check_elastic_search_model.rb
db/migrate/20170509092853_reindex_es_for_accents_and_non_latin.rb
test/models/media_search_test.rb
test/models/project_test.rb

Ticket #5977

---

lib/check_search.rb
test/models/check_search_test.rb

6224-inconsistent-search-results

Ticket #6224

---

.travis.yml
config/initializers/chromeshot.rb
lib/tasks/coverage.rake

Ticket #6114: Don't try to start chromeshot if the port is being used

---

Dockerfile.production

This reverts commit 84f1e8ccceef5ff35c57808fbec52d46c7ae152c.

Revert "Ticket #6462: Precompile assets for production"

---

app/assets/stylesheets/rails_admin/custom/theming.scss
config/locales/en.yml

Also added back the `Delete last task` button

Ticket #6567: Fix message on delete task confirmation

---

lib/tasks/check_update_accounts.rake

Also "merge" the accounts: If an account with the updated url already
exists, update the Media and AccountSource to use the existent account
and destroy the account

Ticket #6617: Add task to update accounts urls

---

lib/tasks/check_update_accounts.rake

Also add timestamp on output filename

Ticket #6617: Use old url to compare to the updated url

---

app/graph/types/team_type.rb
public/relay.json
test/controllers/project_medias_controller_test.rb

As per https://mantis.meedan.com/view.php?id=6554

Fix oEmbed `html` usage

---

app/models/concerns/has_file.rb
app/models/concerns/has_image.rb
app/models/concerns/project_association.rb
test/models/team_test.rb

Skip image size and duplicated project_source and project_media validations

Ticket #6599: Skip validations on team duplication

---

app/models/ability.rb
test/models/ability_test.rb
test/models/project_media_test.rb

Revert "Fix/6937 move action shows to contributors"

---

app/models/concerns/team_duplication.rb
config/initializers/paper_trail.rb
test/models/paper_trail_test.rb
test/models/task_test.rb

Also Check if image exist before duplicate it

Ticket #6896: Avoid error on versions when object_changes has Hash

---

app/models/team.rb
config/locales/en.yml
lib/rails_admin/yaml_field.rb
test/integration/admin_integration_test.rb
test/models/team_test.rb

The conditions should avoid crash with wrong data added on
`Raw checklist` field and allow validations
Also fixed error message with a well formatted example

Ticket #7010: Add conditions to handle checklist format

---

app/models/project.rb

Ticket #7125: Access teamwide task attributes by symbol key or string key

---

app/controllers/api/v1/invitations_controller.rb
app/graph/types/team_type.rb
app/models/concerns/user_invitation.rb
app/models/team.rb
test/controllers/invitations_controller_test.rb
test/models/user_test.rb

…leted members and include members only for team count

Ticket #7201 

---

app/models/concerns/user_invitation.rb
app/models/concerns/user_private.rb
app/models/user.rb

7350: Unable to register to Check after receiving invitations

Fix accept invitation for invited an email of social accounts

---

app/models/search/media_search.rb
lib/check_elastic_search.rb
lib/tasks/check_create_es_data_from_pg.rake

Ticket #7453 - create parent doc for es immediately if not exists

---

lib/check_export.rb
test/models/project_test.rb

Also add `Time.now` on filename to generate different download links

Ticket #7471: Add number of Smooch requests on project export

---

lib/check_export.rb
test/models/project_test.rb

Also remove generic `notes_count`

Ticket #7546: Add language and smooch_responses on project export

---

lib/check_search.rb
test/controllers/graphql_controller_3_test.rb

When only the date is sent on date range filter, with no time,
assume the period starts on the beginning of the day (00:00:00)
and end on the end of the day (23:59:59)

Ticket #7573: Date range filter: handle cases when no time is sent

---

app/mailers/admin_mailer.rb
lib/tasks/export_team.rake
test/mailers/admin_mailer_test.rb

Also removed the connection cache to avoid db problems

Ticket #7550: Rescue errors when dumping tables

---

doc/schema.sql
lib/tasks/export_team.rake

Ticket #7550: Fix query for sources table dump

---

.gitignore
Dockerfile.production

Ticket #7550: Keep `team_dump` folder

---

lib/rails_admin/duplicate_team.rb

The info will be added when raising error

Ticket #7719: store request on Admin UI when duplicating team

---

config/initializers/carrierwave.rb

It defaults to true if not specified.

Added config option for 'path_style' in Carrierwave. 

---

config/initializers/carrierwave.rb

Use endpoint only on test and dev enviroments that need MinIO

---

.gitlab-ci.yml

Kindly review it. If that's okay and works, I'll replicate to checkweb and pender

adding rule to the job

---

Dockerfile.production
production/bin/start.sh

Revert "remove asset compile from start.sh, add to dockerfile"

---

Dockerfile.production

Revert "Compile assets as last step"

---

production/bin/start.sh

Explicitly set environment.

---

Dockerfile.production
config/initializers/logstash_logger.rb.example
production/bin/start.sh

Changed file ownership and reorganized dockerfile. Set port to 3300 for unprivileged access.

Updated startup script and dockerfile

---

lib/tasks/check_move_smooch_messages_to_trash.rake

Conditions to move:
[in the list connected to Check Message OR All Items] AND [not in any other lists] AND [status: team_initial_status]

Ticket #8050: Add task to move items to trash

---

app/models/bot/smooch.rb
lib/tasks/migrate/20200309181011_add_smooch_slack_url_annotation_field.rake
test/controllers/graphql_controller_3_test.rb
test/models/version_test.rb

Ticket #8065 - query against smooch bot project

---

config/apollo-engine-proxy.json.example
config/config.yml.example
config/credentials.json.example
config/database.yml.example
config/sidekiq-test.yml.example
config/sidekiq.yml.example

@caiosba plz review updated example files (including comments)

Config updates to be reviewed

---

lib/tasks/data/push_all_configured_teams_to_workbench.rake

This time, I actually tested with a real file on S3 from my dev machine.
It worked.

check:data:push_..._to_workbench: fix S3 call for real

---

app/models/concerns/team_rules.rb
test/models/team_test.rb

Ticket #8741: Improving the rules keywords matcher to match keywords with spaces

---

lib/tasks/data/pg_export.rb

* Make PG export stop crashing
* Export the new `bot_resources` table

Pg export tweaks

---

.travis.yml
Dockerfile
production/Dockerfile

Set the locale for container runtimes. This resolves sysops ticket #33 .

Bugfix 33 locale

---

.gitlab-ci.yml

This change updates the legacy GitLab-CI based deploys of Check-API to set container environment using SSM parameters. Complements the Terraform project for Check-API which configures env vars via SSM as well.

Update Gitlab deploy to set environment configuration via SSM parameters.

---

app/models/project_media.rb

Ticket CHECK-166: remove media condition as media is mandatory field

---

app/models/bot/alegre.rb
lib/tasks/migrate/20210324152628_update_alegre_matching_model.rake
test/models/bot/alegre_test.rb

CHECK-387 extend alegre bot to pass model in explicitly from all sorts of places

---

app/models/concerns/project_media_bulk.rb
lib/tasks/data/pg_export.rb
public/rules_json_schema.json
test/models/project_media_test.rb

CHECK-437: bulk-assign/remove TeamTasks

---

db/migrate/20210727214018_add_is_child_to_team_tasks.rb
db/schema.rb
test/controllers/graphql_controller_test.rb

Ticket CHECK-84: Adding a "is_child" attribute to TeamTask model

Ticket CHECK-84: Adding a "is_child" attribute to TeamTask model

---

app/models/bot/smooch.rb
app/models/concerns/smooch_tos.rb

Ticket CHECK-738: Adding a channel placeholder to tipline TOS messages

Ticket CHECK-738: Adding a channel placeholder to tipline TOS messages

---

.gitlab-ci.yml
production/bin/start.sh

Have rails listen on port 8000 if we're not running Apollo.

Fix healthcheck sans apollo

---

Dockerfile
Gemfile
Gemfile.lock
app/models/bot/alegre.rb
app/models/concerns/alegre_similarity.rb
db/schema.rb
production/Dockerfile
test/models/bot/alegre_test.rb

Just trying to fix the feature.

Ticket CHECK-1111: Fixes

---

app/graph/types/project_media_type.rb
app/models/concerns/project_media_cached_fields.rb
app/models/concerns/project_media_getters.rb
db/schema.rb
lib/tasks/migrate/20211117172249_cache_item_picture.rake
test/models/project_media_test.rb

Cache more fields for ProjectMedia and batch-load Project and Team for ProjectMedia in GraphQL layer.

Ticket CHECK-1119: Performance improvements

---

app/graph/mutations/claim_description_mutations.rb
app/graph/mutations/fact_check_mutations.rb
app/graph/types/claim_description_type.rb
app/graph/types/fact_check_type.rb
app/graph/types/mutation_type.rb
app/graph/types/project_media_type.rb
app/models/ability.rb
app/models/claim_description.rb
app/models/concerns/project_media_associations.rb
app/models/fact_check.rb
app/models/project_media.rb
app/models/user.rb
db/migrate/20220129185504_create_claim_descriptions.rb
db/migrate/20220129185833_create_fact_checks.rb
db/schema.rb
lib/check_permissions.rb
lib/sample_data.rb
test/models/claim_description_test.rb
test/models/fact_check_test.rb
test/models/project_media_test.rb

Ticket CHECK-1316: Claims and fact-checks

---

app/models/claim_description.rb
app/models/concerns/claim_and_fact_check.rb
app/models/fact_check.rb
app/repositories/media_search.rb
db/migrate/20220202020510_add_claims_and_fact_checks_mapping.rb
db/schema.rb
lib/check_search.rb

Index claims and fact-checks in Alegre and ElasticSearch.

Tickets CHECK-1352 and CHECK-1353: Index claims and fact-checks

---

app/models/project_media.rb

Inherit claim and fact-check when adding media to imported report.

Ticket CHECK-1371: Inherit claim and fact-check when adding media to imported report

---

app/models/bot/alegre.rb
test/models/bot/alegre_test.rb
test/models/cluster_test.rb

Ticket CHECK-1387: Fixing how to get the result with highest score from Alegre

---

app/graph/types/cluster_type.rb
app/graph/types/query_type.rb
app/models/concerns/team_private.rb
app/models/project.rb
db/schema.rb
lib/check_permissions.rb
lib/check_search.rb
test/controllers/elastic_search_2_test.rb
test/controllers/elastic_search_3_test.rb
test/controllers/elastic_search_5_test.rb
test/controllers/elastic_search_6_test.rb
test/controllers/elastic_search_7_test.rb
test/controllers/elastic_search_8_test.rb
test/controllers/elastic_search_test.rb
test/controllers/graphql_controller_3_test.rb
test/controllers/graphql_controller_4_test.rb
test/controllers/graphql_controller_test.rb
test/models/project_media_test.rb

Workspaces with trends feature enabled can access data from other workspaces of the same country that are part of clusters.

Tickets CHECK-1421 and CHECK-1423: New access policy for shared DB

---

app/graph/types/cluster_type.rb
app/graph/types/query_type.rb
lib/check_basic_abilities.rb
test/models/cluster_test.rb

Make sure that permissioned users are able to access cluster data.

Ticket CHECK-1457: Cluster permissions

---

app/models/bot_user.rb
app/models/concerns/annotation_base.rb
app/models/concerns/annotation_private.rb
app/models/concerns/claim_and_fact_check.rb

* `save_annotation`
* `save_claim_description`
* `save_fact_check`

Ticket CHECK-1450: New bot events

---

config/initializers/honeycomb.rb

We are going to go over monthly limits again. Reduce sample rate further to ensure we don't exceed quota. Separately looking into increasing capacity for our plan.

Cut honeycomb sample rate again. We are over monthly estimation limits.

---

app/models/bot/fetch.rb
app/models/concerns/project_media_getters.rb
lib/tasks/migrate/20220512171339_update_blank_item_titles.rake

Fallback to the fact-check title if the claim is blank.
Fixes CHECK-1846.

Fixing blank item titles

---

app/models/team_bot_installation.rb
app/workers/tipline_newsletter_worker.rb
db/schema.rb

Versions are created only when there is a current user, so, for the tipline newsletter worker, let's set the user to be the Smooch one.
Fixes CHECK-1810.

Make sure that tipline versions are saved when newsletter is sent

---

lib/tasks/data/similarity.rake
lib/tasks/data/statistics.rake

This modification directs batch rake job output to file for subsequent upload to S3.
For the statistics batch rake task `lib/tasks/data/statistics.rake`, the upload location is specified by the environment variable `STATISTICS_S3_DIR`.
For the similarity batch rake task `lib/tasks/data/similarity.rake`, the upload location is specified by the environment variable `SIMILARITY_S3_DIR`.
Note that the configurator purge changes used to run batch jobs will be merged separately.

Send batch rake job output to file for upload to S3.

---

app/models/fact_check.rb

Set report visual card image when generating a report from a fact-check

---

app/graph/mutations/graphql_crud_operations.rb
db/schema.rb

Return updated objects in bulk mutations

---

app/controllers/api/v1/graphql_controller.rb
app/graph/mutations/graphql_crud_operations.rb
app/models/api_key.rb
app/models/bot/alegre.rb
app/models/concerns/project_media_private.rb
app/models/project_media.rb
db/migrate/20220711231024_add_rate_limits_to_api_key.rb
db/schema.rb
test/controllers/graphql_controller_2_test.rb
test/controllers/graphql_controller_5_test.rb

* Faster item creation by skipping some background jobs creation if they don't apply
* Require a user in order to save data
* Rate limits
Reference: CHECK-2093.

API changes

---

app/models/bot/smooch.rb
app/models/concerns/smooch_messages.rb
app/models/concerns/smooch_resend.rb
app/models/concerns/smooch_resources.rb
app/models/concerns/smooch_search.rb
app/models/concerns/smooch_status.rb
app/models/concerns/smooch_team_bot_installation.rb
app/workers/report_designer_worker.rb
app/workers/smooch_worker.rb
app/workers/tipline_newsletter_worker.rb

There are two Sidekiq queues for the tipline background jobs: "smooch" and "smooch_priority".
Reference: CHECK-2125.

Setting priority for various tipline background jobs

---

app/models/bot/fetch.rb
lib/tasks/data/fetch.rake

Today the Fetch rake task clears cache using Redis' `delete_matched` method. But when the size of the Redis keys space is too big, that method seems to fail silently (probably because of a timeout, since it has O(n) complexity). The suggested refactoring here is to move that logic to the `Bot::Fetch.import_claim_review` method, which now takes a `force` boolean parameter that when set to `true` forces a cache refresh and essentially re-imports that item.
Fixes CHECK-2209 but also probably CHECK-2030 and CHECK-2151.

Refactoring the way items can be re-imported using the Fetch rake task

---

app/models/bot/fetch.rb

Fixing attribution for claim and fact-check created by Fetch bot.

---

app/models/bot/fetch.rb
test/models/bot/fetch_test.rb

Fetch Bot should import claim review keywords as tags

---

config/initializers/elasticsearch.rb

Better way to verify ElasticSearch log configuration

---

app/models/team.rb
config/locales/en.yml
db/schema.rb
test/models/team_test.rb

Minor update adding a `fact_check` field to list columns, localization, and updating the unit test.

Add fact check to list columns

---

app/models/feed.rb
app/models/request.rb

Parse request media URL before storing.

---

app/models/concerns/smooch_search.rb
test/models/bot/smooch_5_test.rb

Fixing fuzzy matching on tipline/feed keyword search

---

app/models/request.rb

• Log the responses for all HTTP requests to a request `webhook_url`
• Notify Errbit if that response is not 200
Reference: CHECK-2514.

Observability for feed request webhooks.

---

app/models/bot/fetch.rb
lib/tasks/data/fetch.rake
test/models/bot/fetch_test.rb

Revert "CHECK-2476 update fetch code to use offsets when iterating"

---

app/controllers/api/v1/graphql_controller.rb
app/models/bot/fetch.rb

1) Report to Errbit when an exception happens during a GraphQL request (fixes CHECK-2560)
2) When importing an item from Fetch, fallback to default status when mapped status is invalid (fixes CHECK-2551)

A couple of small fixes

---

app/models/project_media.rb
lib/check_cached_fields.rb
test/models/bot/fetch_test.rb
test/models/project_media_test.rb

Still work in progress.
Fixes CHECK-2543.

Fixes for "add item to imported report" feature

---

app/resources/api/v2/feed_resource.rb
config/sidekiq.yml.example

Dedicated Sidekiq queue for feed operations.

---

app/models/bot_user.rb

This commit logs calls to external boots for better auditability and help improve support for partners
References CHECK-2623

CHECK-2623: Log calls to external bot webhooks

---

lib/check_open_telemetry_config.rb
test/lib/check_open_telemetry_config_test.rb

Fix logging when Otel sampling config fails

---

app/models/request.rb
test/models/request_test.rb

Add models parameter to GET request. Abstract list of models and threshold to class method.

CHECK-2672 - Fix cluster feeds with vectors

---

app/models/concerns/smooch_resend.rb

Fixing date in report introduction sent after button is clicked on template message

---

app/models/bot/fetch.rb
lib/tasks/data/fetch.rake

Adding a Fetch rake task to import a sample of articles into a tempory workspace

---

app/models/bot/smooch.rb
app/models/concerns/smooch_menus.rb

Make sure that the languages order is respected.

---

app/models/concerns/smooch_resources.rb

* Use default message when custom message is blank
* Reset the state
* Do not append the main menu to the message
Fixes CHECK-2747.

Fixing tipline timeout

---

config/environments/test.rb

Get paper trail from value from environment variable to fix check web integration tests

Get paper trail settings from environment variable

---

test/lib/tasks/statistics_test.rb

The statistics rake task test was flaking on CI. I believe this is because there is test pollution, either from relevant models hanging around in the database (since we're not using the normal test teardown to speed things up here) or because there is an override of the default language setting for teams somewhere in the code base. This commit attempts to reset both of those to known values (by deleting database objects we touch, and by setting the language on the team).
Additionally, it removes the TiplineSubscription from the test since I had misunderstood what that was -- it's only related to newsletters, which we aren't testing in this test.

Address test data pollution for statistics rake task

---

app/models/bot/smooch.rb
app/models/concerns/smooch_language.rb
app/models/concerns/smooch_search.rb
app/models/team_bot_installation.rb
config/initializers/report_designer.rb
config/tipline_strings.yml
test/models/bot/smooch_6_test.rb

* New similarity setting (boolean): send reports in different languages or only in the same language as the tipline user
* Send reports and search results depending on that setting
Reference: CHECK-2844.

Tipline reports and tipline search results in different languages

---

app/models/bot/smooch.rb
test/models/bot/smooch_6_test.rb

Bugfix: Do not send update message when not sending a report in a different language

---

lib/check_statistics.rb

Previously we were only sending this information on parent spans, which made debugging and filtering in Honeycomb difficult. This adds team, platform, and language information to the function spans so that we can filter by all of those attributes when understanding individual performance of functions.
[CHECK-2657]
[CHECK-2657]: https://meedan.atlassian.net/browse/CHECK-2657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add function attributes to statistics rake task

---

app/models/concerns/smooch_search.rb
config/tipline_strings.yml

Include language name in "no results found in this language" localizable string

---

lib/tasks/data/statistics.rake
test/lib/tasks/statistics_test.rb

In production data, there are teams that do not have a tipline bot currently installed. When this happens, we can't pull off the platforms and were receiving an error when running the rake task.
This commit skips the team entirely when generating statistics if no bot installation is currently found. This means we won't be generating historic data for any teams that have disabled their bot installation.
It also improves logging, so we have more verbose output, and silences that output in test. This make make debugging tests a bit tricker, but the capture_io lines can be commented out or removed if there is an issue.
CHECK-2892

Skip generating statistics for teams with no bot installation

---

lib/tasks/data/statistics.rake

Reducing amount of logging, making sure we don't make redundant logs

Improvements to statistics logging

---

app/models/concerns/smooch_search.rb
app/models/concerns/smooch_strings.rb

1) Get localized language name
2) Fallback to English if translation is blank
Fixes CV2-2603.

A couple localization fixes.

---

app/models/concerns/smooch_strings.rb

Bugfix: Fallback to language without dialect or to English when there is no translation for a given language and tipline string

---

config/tipline_strings.yml

Add Filipino tipline strings

---

app/graph/mutations/team_mutations.rb
app/models/concerns/smooch_search.rb
public/relay.json

Filter tipline search results that have a report

---

app/models/bot/alegre.rb
app/workers/reindex_alegre_workspace.rb
lib/tasks/migrate/2023020700000_remove_vetor_768.rake

https://meedan.atlassian.net/browse/CV2-477
adding reindex call, but BotUser failing
pass in ES urls from cli

[CV2-477] adding draft rake migration script to reindex

---

app/models/concerns/smooch_search.rb
db/schema.rb

Do not return as a tipline search result an item that is in the trash.

---

app/graph/mutations/graphql_crud_operations.rb
app/graph/mutations/project_media_mutations.rb
app/models/concerns/project_media_creators.rb
app/models/project_media.rb
db/schema.rb
public/relay.json
test/models/project_media_6_test.rb

* Set fact-check URL and language
* Set status
* Fixing JSON parsing
Reference: CV2-2807.

Improvements for fact-check GraphQL API.

---

lib/tasks/migrate/20230224205948_add_legacy_smooch_data_to_tipline_message.rake

Also modifies caching behavior to account for fact we might want to invalidate cache when running multiple times.
CV2-2647

Turn off logging for tipline message rake task

---

lib/tasks/migrate/2023020700000_remove_vetor_768.rake

was passing in url instead of usr into rake task auth .. fingers crossed that this works!

[CV2-477] fixed https auth bug

---

app/workers/tipline_newsletter_worker.rb
lib/check_statistics.rb
test/workers/tipline_newsletter_worker_test.rb

Fixing how number of newsletters sent is calculated.

---

.rubocop.yml
app/models/project_media.rb

Fixing Rubocop for Ruby 2.7.7.

Fixing Rubocop integration

---

app/views/project_medias/oembed.html.erb

Fix CodeQL `Inclusion of functionality from an untrusted source`
I used online tool [SRI Hash Generator](https://www.srihash.org/)  to generate integrity value

CV2-3137: add integrity to script tag

---

config/locales/de.yml

Add German translation for invitation mail

CV2-3139: add de locales for invited mail template

---

config/locales/de.yml

CV2-3139: add more translation for mail notifications

---

pull_request_template.md

Added the same PR template we just added for Pender. I added the description above the template here so you could see what it looks like when someone first creates the PR.
References: [TICKET-ID](url), [TICKET-ID](url), …
- Etc.

CV2-3158: add pull_request_template

---

app/graph/types/feed_type.rb
public/relay.json

Expose "user" type in GraphQL feed type.

---

app/models/concerns/smooch_menus.rb

Reply buttons are LINE are working, but we can only display a max of 13. This change displays only the first 13 if there are more than 13, which is going to be pretty rare tbh.
References: CV2-3396
- Etc.

CV2-3396 Max 13 LINE reply buttons

---

app/models/bot/alegre.rb

Fix calling gsub for nil.
References: CV2-3403
- Etc.

CV2-3403: fix sentry issue

---

public/assets/graphiql/rails/application-19d5be3c4c346620c6a2794efc4fe54b06ab9c9c07317e68d4177c4369097e14.js

Fix issues reported by CodeQL 
References: CV2-3440, CV2-3441
- Etc.

Fix/cv2  3440 3441 CodeQL issues

---

app/models/bot/smooch.rb
app/models/concerns/smooch_capi.rb
app/models/concerns/smooch_menus.rb
app/workers/tipline_newsletter_worker.rb
test/models/bot/smooch_4_test.rb
test/models/bot/smooch_7_test.rb

Cache tipline installation based on key and value given.
Reference: CV2-3462.
This is just a performance refactoring, so existing tests should cover this and coverage should not be affected.

Cache tipline installation based on key and value given.

---

app/models/concerns/team_slack_notifications.rb
lib/tasks/migrate/20230727094535_remove_add_item_slack_notification.rake
public/slack_json_schema.json
test/models/project_media_5_test.rb
test/models/team_2_test.rb

Remove slack notification related to add an item to a folder.
References: CV2-3501
- Etc.

CV2-3501: remove slack notification related to add item to a project

---

lib/tasks/migrate/20230730055732_migrate_from_folders_to_lists.rake

Try to read invalid tags using SQL query and update invalid tags with right data.
References: CV2-3556
Access an item with invalid tag as invalid tag show blank page.

CV2-3556 add rake task to fix invalid tags

---

docker-compose.yml

Upgraded Postgres to 13. Used the same image as the one in alegre and pender.
References: 3466, 3464, 3468
Ran the seeds file and went through a few to see if everything seemed fine.

3466 - Make sure check-api works with PostgreSQL 13

---

app/models/monthly_team_statistic.rb
app/models/team.rb
db/migrate/20230814235431_add_new_data_points_to_monthly_team_statistic.rb
db/schema.rb
lib/check_statistics.rb
test/models/monthly_team_statistics_test.rb
test/models/team_test.rb

Changes to workspace statistics: adding new data points, removing some data points and re-ordering the data points.
New data points added:
* Published reports (imported or created inside Check)
* Positive searches (tipline queries that return results)
* Negative searches (tipline queries that don't return results)
* Newsletters sent (number of newsletters sent to users)
Data points removed:
* Valid new requests
* Requests answered with a report
* Average messages per day
* Published native reports
* Published imported reports
Reference: CV2-2750.

Changes to workspace statistics

---

app/models/monthly_team_statistic.rb

Ticket CV2-2750: Just copy updates

---

app/lib/smooch_nlu.rb

We want to gather ongoing insights about how NLU is performing. This change outputs the data we need in a JSON format to CloudWatch. A separate Python script can read that data and generate the insights we need.
References: CV2-3606
Tested locally out of application but not within the full application
N/A

CV2-3606 Update NLU logging to make it easier to mine and gather insights

---

lib/tasks/data/export_workspace_data.rake

Adding columns "Reviewed by organization" and "Created by organization". The organization is extracted from the user name, when present. For example, if the user name is "John Lennon [Beatles]", the organization name is "Beatles". This is a convention agreed by a project that is going to use this rake task to export their data.
This rake task is pretty specific for this project for now... we'll generalize later, hopefully.
More details in CV2-3662.
I executed it locally for both cases: when a user name contains brackets and when it doesn't.
Please note this is pretty specific for now.

Adding two columns to the CSV generated by rake task `export_workspace_data`

---

CODEOWNERS

Remove me as codeowner :)

---

pull_request_template.md

This is a bit self-referential, however this change add a security consideration to the pull request template, as discussed in today's retrospective. :)

Add security considerations to pull request checklist.

---

app/graph/types/team_type.rb
app/graph/types/tipline_message_type.rb
lib/relay.idl
public/relay.json
test/controllers/graphql_controller_9_test.rb

Query TiplineMessage in TeamType by uid to get latest 100 TiplineMessages.
References: CV2-3681
- Etc.

CV2-3681: list TiplineMessage by uid

---

app/models/bot/alegre.rb

Update alegre.rb to add `PARAPHRASE_MULTILINGUAL_MODEL`

---

.gitlab-ci.yml

This fix updates version pins for python packages awscli, boto3, botocore, and ecs-deploy to fix deployments.
I tested a deployment into QA using this method.

Update version pins for Python dependencies to fix deployments.

---

test/controllers/graphql_controller_10_test.rb
test/controllers/graphql_controller_11_test.rb

Just trying to fix a flaky test by moving it to a file where it's the only test, and with empty "setup" and "teardown" methods.

Trying to fix flaky test

---

app/models/feed.rb
app/models/feed_team.rb
lib/check_search.rb
test/controllers/elastic_search_9_test.rb

Filter feed by organization
References: CV2-3800

CV2-3800: filter feed by organization

---

app/mailers/feed_invitation_mailer.rb
app/models/feed_invitation.rb
app/views/feed_invitation_mailer/notify.html.erb
app/views/feed_invitation_mailer/notify.text.erb
app/views/shared/_header.html.erb
config/locales/en.yml
test/mailers/feed_invitation_mailer_test.rb
test/models/feed_invitation_test.rb

Send an invite email after create feed invitation record.
added due to date for invitation after 30 days and we can configure this value.
things to do:
- Get the invitation link to add it to mail template 
- Should handle invitation based on due to date
References: CV2-3798
- Etc.

CV2-3798 shared feed invite emails

---

app/mailers/feed_invitation_mailer.rb
app/models/feed.rb
app/models/feed_invitation.rb
app/views/feed_invitation_mailer/notify.html.erb
lib/check_search.rb
test/controllers/elastic_search_9_test.rb
test/mailers/feed_invitation_mailer_test.rb

* Generate accept feed invitation link
* Query feed organization with empty array should return empty result
References: CV2-3611,CV2-3806
- Etc.

CV2-3611-3806: generate invitation link and handle query empty feed organization

---

app/models/feed_invitation.rb
test/mailers/feed_invitation_mailer_test.rb
test/models/feed_invitation_test.rb

Fix tests in develop branch
References: CV2-3798
- Etc.

CV2-3798: fix tests

---

lib/sample_data.rb
test/controllers/elastic_search_2_test.rb
test/controllers/elastic_search_3_test.rb
test/controllers/elastic_search_4_test.rb
test/controllers/elastic_search_5_test.rb
test/controllers/elastic_search_6_test.rb
test/controllers/elastic_search_test.rb
test/controllers/graphql_controller_10_test.rb
test/controllers/graphql_controller_2_test.rb
test/controllers/graphql_controller_6_test.rb
test/controllers/graphql_controller_8_test.rb
test/controllers/graphql_controller_test.rb
test/models/bot/smooch_3_test.rb
test/models/bot/smooch_5_test.rb
test/models/bot/smooch_7_test.rb
test/models/feed_team_test.rb
test/models/team_2_test.rb

Do a refactor in testing by:
- Reduce sleep time to be 2 instead of 5
- Avoid creating un-needed objects
Make sure that existing tests passed
- Etc.

Testing refactor 

---

app/models/concerns/smooch_search.rb
test/models/bot/smooch_7_test.rb

Include claim description content in smooch search.
References: CV2-3912
- Etc.

CV2-3912: search claim description

---

app/models/feed.rb
test/models/feed_test.rb

Delete FeedInvitation after user delete Feed.
References: CV2-3804
- Etc.

CV2-3804: delete FeedInvitation when feed deleted

---

app/models/annotations/tag.rb
test/controllers/elastic_search_2_test.rb
test/controllers/elastic_search_4_test.rb

Include delete tags in most recent update.
References: CV2-3694
- Etc.

CV2-3694: update `updated_at` column after delete tags

---

app/models/concerns/smooch_capi.rb
test/models/concerns/smooch_capi_test.rb

WhatsApp reactions.
References: CV2-3897
- Etc.

CV2-3897: ignore reaction request

---

db/seeds.rb

I forgot to push this in this [PR](https://github.com/meedan/check-api/pull/1732).
I know it was non-blocking, but I think it should be updated.
References: 3993

3993 – Update create_confirmed_relationship

---

app/models/annotations/dynamic.rb
app/models/bot/keep.rb

Fix sentry issues.
References: CV2-3829, CV2-3987
- Etc.

Fix sentry issues

---

app/mailers/feed_invitation_mailer.rb

This should send via mailer `BASEURL/check/feed/:feed_id/invitation`

Updating feed invitation mailer url

---

config/initializers/field_validators.rb
test/models/dynamic_annotation/field_test.rb

use `strip` instead of `strip!` as strip! return `nil` if str was not altered
References: CV2-4028
- Etc.

CV2-4028: fix error when answering annotation of link type

---

db/seeds.rb

Add some variation to tipline requests as per Brian's (request)[https://github.com/meedan/check-api/pull/1723#issuecomment-1802465942]
References: 3994
Ran the seeds script to create an user, and to add data to the same user.

3994 – Improve seeds file: add variation to requests

---

lib/check_search.rb
test/controllers/elastic_search_7_test.rb
test/controllers/elastic_search_9_test.rb

Make sure that team_id filter applied in PG & ES queries.
References: CV2-4062
- Etc.

CV2-4062 apply team condition for PG & ES query

---

app/lib/check_permissions.rb
app/models/ability.rb
app/models/feed.rb
app/models/team.rb
lib/sample_data.rb
test/controllers/graphql_controller_6_test.rb
test/models/ability_test.rb
test/models/feed_team_test.rb
test/models/feed_test.rb
test/models/team_2_test.rb
test/models/team_test.rb

Updating and exposing feed permissions.
Reference: CV2-3953.
Unit tests.

Updating and exposing feed permissions.

---

.gitlab-ci.yml

This change fixes deployments into QA and Live by updating ecs-deploy version pins.
I verified with test deployments in QA from this branch.
N/A.

Bugfix for aws deployments

---

app/models/concerns/alegre_v2.rb

Add some more data to the log so we can find where this is breaking more easily
References: Cv2-4233
Very little need to test this...
Any other logs we can add?

CV2-4233 add method/path/params/retries to error message so it's easier to find in cloudwatch

---

app/models/concerns/alegre_v2.rb

Adding another small log to try to capture the actual content of the Alegre fail response
References: CV2-4233
No tests on this, just a simple log line
Anything else to log to stop sending one off log PRs?

CV2-4233 yet another log

---

test/controllers/sessions_controller_test.rb

Testing devise's lock/unlock strategy is misbehaving in during CI runs.
References: CV2-4163
Ensured that rate limit checks are working
Ensure that all rate limit tests are passing.

Fix flaky test in sessions_controller_test.rb

---

app/models/monthly_team_statistic.rb
db/migrate/20240223210914_add_positive_feedback_and_negative_feedback_to_monthly_team_statistic.rb
db/schema.rb
lib/check_statistics.rb

* "Positive feedback": Number of conversations that returned at least one result and the user answered "Yes".
* "Negative feedback": Number of conversations that returned at least one result and the user answered "No".
Reference: CV2-4160.

Collecting two new data points for monthly workspace statistics

---

app/models/project_media.rb

Make it explicit.
Fixes CV2-4364.

Fixing default order of tipline requests.

---

app/workers/terms_of_service_update_worker.rb
test/workers/terms_of_service_update_worker_test.rb

Exclude empty mails and fix time format.
References: CV2-2357
- Etc.

CV2-2357: exclude empty mails and fix time format

---

app/models/bot/alegre.rb
app/models/concerns/alegre_v2.rb
test/models/bot/alegre_2_test.rb
test/models/bot/alegre_test.rb
test/models/bot/alegre_v2_test.rb

This reverts commit f614337a4872a5849f26633c9eacdb95f5d960fd.
- Etc.

Revert "CV2-4126 shift to use video via sync endpoint (#1762)"

---

lib/check_cluster_center.rb
lib/tasks/check_khousheh.rake
test/lib/check_cluster_center_test.rb

Set algorithm to set cluster center.
References: CV2-4128
- Etc.

CV2-4128: Shared Feed Item Cluster Meta Info Algorithm

---

app/models/feed.rb
lib/tasks/check_khousheh.rake
test/controllers/elastic_search_10_test.rb
test/models/bot/smooch_5_test.rb
test/models/request_test.rb

Fixing how feed filters are applied until a list is chosen.
Reference: CV2-4398.
TDD. I added an automated test that reproduces the issue.

Fixing how feed filters are applied until a list is chosen.

---

config/locales/ar.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/id.yml
config/locales/mk.yml
config/locales/pt.yml

Updating localization for March sprint, including Macedonian (mk) translation new addition
References: CV2-4418
Manually. Set my browser to Macedonian language and verified Check UI was translated as expected.
Nothing special here

Updating localization for March sprint

---

app/models/project_media.rb
test/models/project_media_5_test.rb

Log a new version when archived attribute of a ProjectMedia changes.
References: CV2-3916:
- Etc.

CV2-3916: Create version when the archived attribute of a ProjectMedia changes

---

app/models/concerns/user_private.rb
app/models/user.rb

Set a default value for last_received_terms_email_at .
References: CV2-2357
- Etc.

CV2-2357: set default value for last_received_terms_email_at

---

app/controllers/api/v1/admin_controller.rb
config/locales/en.yml
test/controllers/admin_controller_test.rb

Fix sentry issue and make code more readable.
References: CV2-4432
Depend on current tests.
- Etc.

CV2-4432: Fix sentry issue

---

app/models/claim.rb
app/models/media.rb
db/migrate/20240404154458_add_uuid_to_medias.rb
db/schema.rb
lib/tasks/check_khousheh.rake
lib/tasks/migrate/20240404154458_add_uuid_to_medias.rake
test/models/media_test.rb

Store `uuid` in media table and read the value direct from media table instead of using ElasticSearch.
References: CV2-4458
- Etc.

CV2-4458: improve-cluster-rake-task

---

app/models/claim.rb
lib/tasks/migrate/20240404154458_add_uuid_to_medias.rake

Bulk-select claims to get uuid and set the `uuid` for existing claims.
References: CV2-4458
- Etc.

CV2-4458: bulk-select claims to get uuid

---

lib/tasks/migrate/20240404154458_add_uuid_to_medias.rake

Changed a query for collecting duplicate claims based on quote.
References: CV2-4458
- Etc.

CV2-4458: fix  rake task

---

config/locales/ar.yml
config/locales/fr.yml
config/locales/mk.yml

Get latest translations from Transifex

---

app/models/concerns/alegre_v2.rb
app/models/concerns/alegre_webhooks.rb
test/controllers/webhooks_controller_test.rb

Minor debug statments and logic tweaks
N/A
N/A

CV2-4126 add some temp logs and minor logic tweaks

---

app/models/concerns/alegre_webhooks.rb
test/controllers/webhooks_controller_test.rb

A refactor for how we determine callback requests changed and we are now missing a line in our test coverage. Adding a test that ought to trigger that line
Not tested yet - that's the point! :) 
None

CV2-4126 fix missing line

---

app/models/bot/alegre.rb
app/models/concerns/alegre_similarity.rb
app/models/concerns/alegre_v2.rb
app/models/concerns/alegre_webhooks.rb
app/resources/api/v2/report_resource.rb
test/controllers/webhooks_controller_test.rb
test/models/bot/alegre_2_test.rb
test/models/bot/alegre_3_test.rb
test/models/bot/alegre_test.rb
test/models/bot/alegre_v2_test.rb

CV2-4126 revert video round 2

---

app/models/bot/alegre.rb
app/models/concerns/alegre_similarity.rb
app/models/concerns/alegre_v2.rb
app/models/concerns/alegre_webhooks.rb
app/resources/api/v2/report_resource.rb
test/controllers/webhooks_controller_test.rb
test/models/bot/alegre_2_test.rb
test/models/bot/alegre_3_test.rb
test/models/bot/alegre_test.rb
test/models/bot/alegre_v2_test.rb

Readds already accepted changes on Check API for video
Tested previously - just reintroducing history
NA

CV2-4126 readd changes for video

---

app/models/concerns/smooch_search.rb

Remove set phrases like "Is it true that..." before performing tipline search
References: CV2-4563
- Etc.

Remove set phrases like "Is it true that..." before performing tipline search

---

app/models/bot/alegre.rb
test/models/bot/alegre_4_test.rb

Cv2 4582 no urls for similarity

---

app/models/concerns/user_invitation.rb
app/models/concerns/user_private.rb
app/models/user.rb
config/locales/en.yml
db/seeds.rb
lib/sample_data.rb
test/controllers/graphql_controller_9_test.rb
test/controllers/graphql_controller_test.rb
test/controllers/omniauth_callbacks_controller_test.rb
test/controllers/registrations_controller_test.rb
test/controllers/sessions_controller_test.rb
test/lib/check_rack_attack_test.rb
test/mailers/registration_mailer_test.rb
test/models/bot_user_test.rb
test/models/user_test.rb

Add a password validation for complexity and should match the following conditions:
- Contain at least eight (8) alphanumeric characters, one of which must be a number
- Contain both upper and lowercase letters
- Contain at least one special character (e.g., $%^&*()_+|~-=\`{}[]:";'<>?,/)
References: CV2-4595
- Etc.

CV2-4595 Validate password strength in check

---

app/models/bot/smooch.rb

Make sure that reports are sent for confirmed suggestions. More context in the related ticket.
Fixes CV2-4564.

Send report for confirmed suggestions.

---

app/mailers/security_mailer.rb

Fix sentry issue related to SecurityMail notification.
References: CV2-4604
- Etc.

CV2-4604: fix sentry error

---

test/integration/api_version_integration_test.rb
test/integration/dynamic_annotation_integration_test.rb
test/integration/short_url_integration_test.rb

Trying to fix flaky integration tests.
Tests should pass consistently now.

Trying to fix flaky integration tests

---

db/seeds.rb

Add imported fact checks.
References: 4334
By creating users from scratch and adding to an existing user.
- Etc.

4434 – Update seeds script: create imported fact checks

---

app/controllers/api/v1/admin_controller.rb

Log API request and response to Facebook when connecting Messenger tipline
Reference: CV2-4559.
Not tested.

Log API request and response to Facebook when connecting Messenger tipline

---

app/models/bot/smooch.rb

Fix null byte before query DB for an existing item.
References: CV2-4722
Re-run  automated tests.
- Etc.

CV2-4722: fix null byte

---

app/graph/types/project_media_type.rb
lib/relay.idl
public/relay.json

- Expose projectMedia.fact_check_published_on field
References: CV2-3939
Tested that the value is queried and displayed correctly in Check-web
- Etc.

Expose projectMedia.fact_check_published_on field

---

db/seeds.rb

Update seed file to update project media channel when creating a tipline request
Reference: CV2-4697
- ran the seed file and verified that the channels are being displayed and consistent with the requests on check locally

Feature/cv2-4697: show channels in item card 

---

app/models/concerns/project_media_cached_fields.rb

CV2-4441: fix sentry issue

---

config/tipline_strings.yml

Just a simple string update
References: CV2-4750
- Etc.

Updated 'cancelled' button translation for mongolian

---

app/mailers/feed_invitation_mailer.rb
app/models/concerns/smooch_menus.rb

Fix sentry issues.
References: CV2-4799, CV2-4799
Current automated tests.
- Etc.

CV2-4799 & CV2-4799 sentry issues

---

app/models/concerns/smooch_messages.rb
app/models/concerns/smooch_search.rb
test/models/bot/smooch_3_test.rb

The request include on of the following types:
1. Long text (text with number of words > min_number_of_words_for_tipline_submit_shortcut) 
2. Short text (text with number of words <= min_number_of_words_for_tipline_submit_shortcut)
3. Media (image, audio, video, etc)
Based on the these types the created items should be
1. Item per each media (type 3)
2. Item per each long text (type 1)
The request text for created items include all text (long text, short text and media urls)
References: CV2-4696
- Etc.

CV2-4696 extract multiple media from tipline request

---

app/models/concerns/smooch_menus.rb
app/models/concerns/smooch_search.rb
test/models/bot/smooch_6_test.rb

CV2-4853: fix sentry issue

---

app/models/concerns/smooch_messages.rb

Ignore payload text to make request body more readable.
References: CV2-4696
- Etc.

CV2-4696: ignore payload text

---

app/models/concerns/smooch_messages.rb

Set message type as a text for short text message 
References: CV2-4696
- Etc.

CV2-4696: set message type for short text

---

app/models/concerns/alegre_v2.rb

CV2-4908: fix sentry issue

---

.github/workflows/ci-tests.yml

Adding a cron schedule to run the workflow at a particular time daily
References: [
](https://meedan.atlassian.net/browse/CV2-4838)
Do not require tests
- Etc.

CV2-4838-set-cronjob-for github-actions

---

.github/workflows/ci-tests.yml
test/format-coverage.sh
test/sum-upload-coverage.sh

Modified the test scripts to push tests coverage results to s3 bucket on push events, ie when a branch is merged to develop or master
References: https://meedan.atlassian.net/browse/CV2-4794
Added an if or statement to the test scripts
- Etc.

CV2-4794:Add coverage results to upload to s3 bucket on push event

---

lib/tasks/migrate/20240703070839_add_language_to_fact_check.rake

[Fix sentry issue](https://meedan.sentry.io/issues/5633226332/?alert_rule_id=14024980&alert_type=issue&environment=QA&notification_uuid=9133cf7f-b776-48ef-8f74-08bd3b37e975&project=4504690947653632&referrer=slack) .
References: CV2-4665
Run rake task locally against live DB.
- Etc.

CV2-4665: fix rake task

---

app/models/concerns/smooch_messages.rb
test/models/bot/smooch_3_test.rb

For tipline messages extract a message that contain a link as an item of type Link.
References: CV2-4998
- Etc.

CV2-4998: extract link as tipline message

---

app/graph/types/query_type.rb
lib/relay.idl
public/relay.json

WIP Articles deep link

---

app/models/bot/alegre.rb

Fix sentry error by adding a check before create a relationship.
References: CV2-5002
- Etc.

CV2-5002: fix sentry issue

---

app/graph/types/me_type.rb

Sort user workspaces alphabetically.
Reference: CV2-4938.

Sort workspaces alphabetically

---

lib/tasks/check_khousheh.rake

Remove clusters that have no center.
References: CV2-4869
- Etc.

CV2-4869: Delete clusters that have no center

---

.github/workflows/ci-tests.yml

run tests(github actions) on other branches

---

.github/workflows/ci-tests.yml

Run GitHub actions tests on push request to other branches

---

app/models/annotations/annotation.rb

CV2-5193: fix sentry issue

---

lib/check_search.rb

Fix Sentry issue.
References: CV2-5206
- Etc.

CV2-5206: fix sentry issue

---

app/models/claim_description.rb
app/models/project_media.rb
app/models/version.rb
test/models/project_media_5_test.rb

When user add a media do the following:
- Keep the status for the current item
- Merge assignments 
- Add a log entry for replacement
References: CV2-5191, CV2-5177
- Etc.

CV2-5191: Fix Replace by action

---

app/models/bot/smooch.rb
app/models/concerns/smooch_messages.rb

Fix sentry issues
References: CV2-5273
Re-run  automated tests.
- Etc.

CV2-5273: fix sentry issue

---

app/graph/types/project_media_type.rb
app/graph/types/team_type.rb

Sorting team.tag_texts and project_media.tags alphabetically
References: CV2-2502
Verified sorted output is correct on check-web
- Etc.

Sort tags alphabetically

---

app/models/fact_check.rb

CV2-5297: fix sentry issue

---

app/models/bot/alegre.rb
app/models/concerns/project_media_creators.rb
app/models/concerns/smooch_messages.rb
app/models/relationship.rb
test/models/relationship_test.rb

Create  a class method in Relationship model called create_unless_exists, which receives the source, the target and the type and use it everywhere.
References: CV2-5324
implemented automated tests.
- Etc.

CV2-5324: Create a method for create relationship.

---

app/models/project_media.rb

Re-order the if conditions to avoid the sentry error.
References: CV2-5371
- Etc.

CV2-5371: fix sentry error

---

app/lib/check_cached_fields.rb

References: CV2-5420:
Rerun automated tests.
- Etc.

CV2-5420: include cached fields that require ES or PG updates

---

app/models/feed.rb

Add the summary to exported feed content.
References: CV2-5392

CV2-5392: Export item summary

---

lib/check_search.rb

- Change Published at column label to Social Media Posted at
- Add column Report Published at
References: CV2-5301

CV2-5301: add a report published_at to CSV export file

---

app/models/concerns/user_multi_auth_login.rb
app/models/user.rb
app/workers/terms_of_service_update_worker.rb
test/models/user_test.rb
test/workers/terms_of_service_update_worker_test.rb

Add new flags display a ToS dialog to users and send the ToS email.
References: CV2-5388

CV2-5388: Improve ToS and Privacy Policy UX

---

app/models/bot/alegre.rb
app/models/relationship.rb

Better logging for when relationships fail to create. WIP
References: CV2-5552
- Etc.

CV2-5552 relationships better logging

---

app/lib/check_state_machine.rb
app/models/bot/smooch.rb
app/models/concerns/smooch_messages.rb
app/models/concerns/smooch_resources.rb
app/models/tipline_resource.rb
config/config.yml.example
db/schema.rb
test/models/bot/smooch_6_test.rb

This type of tipline resource can connect to external APIs and send user input. This prototype integrates with Google Civic API.
This PR introduces a new type of tipline resource. If a tipline resource is marked as "dynamic", when it is sent, more input is requested from the user. Then, a request is made to an external API and the response is sent back to the user. For this PR, since it's a prototype, only one API is integrated: the Google Civic Information API. In this case, the expected user input is an address, and then, polling locations and early vote sites are sent to the user, from the Google API.
Reference: CV2-5456.
Automated tests were added for full coverage of the newly-added code.
This is just a prototype for a specific project.

Basic prototype for a "dynamic" tipline resource type.

---

app/lib/check_cached_fields.rb

As we send the class name and id to the background job to update cached field so add a check to make sure the object still exists before run the background job.
References: CV2-5601

CV2-5601: apply the background job if the object exists

---

lib/check_data_points.rb
lib/team_statistics.rb
test/lib/team_statistics_test.rb

Some fixes and changes to the data dashboard backend:
References: CV2-4111.
Automated tests fixed/updated accordingly.

Fixes and changes for the data dashboard backend

---

test/models/bot/smooch_6_test.rb

Fixing test in order to get 100% coverage.
Fixes CV2-5621.
All tests should pass now and the coverage should be back to 100%.
Still keeping an eye for some coverage flakyness/inconsistency for the `BotUser` model.

Fixing test in order to get 100% coverage.

---

app/models/concerns/smooch_search.rb
app/models/explainer.rb
app/models/team.rb
app/resources/api/v2/feed_resource.rb
test/controllers/feeds_controller_test.rb
test/controllers/graphql_controller_5_test.rb
test/models/bot/smooch_3_test.rb
test/models/bot/smooch_4_test.rb
test/models/bot/smooch_5_test.rb
test/models/bot/smooch_7_test.rb
test/models/project_media_7_test.rb
test/models/team_2_test.rb

List most relevant FactCheck and Explainer for a ProjectMedia.
References: CV2-5761

CV2-5761 list most relevant articles fact check and explainer for project media item

---

app/graph/types/project_media_type.rb
app/graph/types/team_type.rb
app/models/concerns/smooch_search.rb
app/models/explainer.rb
app/models/project_media.rb
app/models/team.rb
app/resources/api/v2/feed_resource.rb
config/initializers/report_designer.rb
lib/relay.idl
public/relay.json
test/controllers/feeds_controller_test.rb
test/controllers/graphql_controller_11_test.rb
test/controllers/graphql_controller_5_test.rb
test/models/bot/smooch_3_test.rb
test/models/bot/smooch_4_test.rb
test/models/bot/smooch_5_test.rb
test/models/bot/smooch_7_test.rb
test/models/project_media_7_test.rb
test/models/team_2_test.rb

This is a test PR to confirm our merging strategy
References: CV2-5703

CV2-5703 bot query preview

---

lib/check_search.rb
test/controllers/elastic_search_10_test.rb
test/controllers/elastic_search_4_test.rb
test/controllers/elastic_search_7_test.rb
test/controllers/elastic_search_test.rb
test/controllers/graphql_controller_10_test.rb
test/controllers/graphql_controller_3_test.rb
test/controllers/graphql_controller_6_test.rb
test/lib/team_statistics_test.rb
test/models/bot/smooch_5_test.rb
test/models/project_media_test.rb

Remove projects filter and fix `OR` conditions .
References: CV2-5628
Re-run  automated tests.

CV2-5628: fix OR condition and remove projects filter

---

test/lib/check_search_test.rb
test/models/fact_check_test.rb
test/models/project_test.rb
test/workers/project_media_trash_worker_test.rb

Adding missing tests in order to complete code coverage.
Reference: CV2-5830.
CI should show 100% coverage.
There is a test that I think it's flaky...

Adding missing tests.

---

config/tipline_strings.yml

Revert updated translations which are causing a build failure in check-api.
References: CV2-5790
Ensured that check-api docker build is successful.

Revert translation updates

---

app/controllers/test_controller.rb

Fix helper method to proper indexing fact check in Alegre
Reference: CV2-5737, CV2-5900
running the automated tests

Test/CV2-5737: Create and associate ProjectMedia to a fact-check for proper indexing in test helper method

---

db/seeds.rb

Updated the confirmed_relationship method to include user when creating confirmed relationships in the seed script.
Updated the suggested_relationship method to include user when creating suggested relationships in the seed script.
References: CV2-5785, CV2-5510

Set user when creating relationship in seed script

---

app/models/concerns/team_private.rb
app/models/team.rb
lib/list_export.rb
test/lib/list_export_test.rb
test/models/team_test.rb

Export the dashboard data as a CSV file; it should consist of a single row with the following columns.
- Conversations
- Messages
- Conversations(Positive)
- Conversations(Negative)
- Conversations(No Response)
- Avg. Response Time
- Users(Total)
- Users(Unique)
- Users(Returning)
- Subscribers
- Subscribers(New)
- Newsletters(Sent)
- Newsletters(Delivered)
- Media Received(Text)
- Media Received(Link)
- Media Received(Audio)
- Media Received(Image)
- Media Received(Video)
- Articles Sent
- Matched Results(Fact-Checks)
- Matched Results(Explainers)
- Top Tag(from 1 to 5) based on existing data
- Top Requested(from 1 to 5) based on existing data
References: CV2-4985

CV2-4985: Export dashboard data as CSV

---

app/models/project_media.rb

Fix sentry error by check status value.
References: CV2-5503
Re-run  automated tests.

CV2-5503: Fix sentry error by check status value

---

app/models/bot/smooch.rb

Bypass the check for published items when replicating status to children.
References: CV2-6140

CV2-6140: replicating status to children

---

app/models/team.rb

Improving performance of the SQL query that retrieves the tipline platforms for which data analytics is available.
Reference: CV2-5821.
Existing test should cover this.

Improving performance of the SQL query that retrieves the tipline platforms for which data analytics is available.

---

app/models/team.rb

Fixing: Adding missing language filter for explainers.
Reference: CV2-5007.
You can test using Check Web.

Fixing: Adding missing language filter for explainers.

---

lib/tasks/migrate/20230130074014_add_mapping_for_keyword_search_fields.rake

Rake task was terminated while running on Live, so I passed arguments to the rake task to control the team slug and batch size.
References: CV2-6038
Run rake task locally.

CV2-6038: pass team_slug and batch_size to index_fact_check_fields rake task

---

lib/tasks/migrate/20230130074014_add_mapping_for_keyword_search_fields.rake

I rely on Select to obtain the necessary fields, so I must choose ClaimDescription.id as a key for find_in_batches.
References: CV2-6038
Run rake task locally

CV2-6038: Fix SQL query and set ClaimDescription ID as a key

---

app/views/security_mailer/notify.html.erb
app/views/security_mailer/notify.text.erb
config/locales/en.yml

Updating copy for the email sent when user logs in from a new location.
Reference: CV2-2594.
Easiest way to test is to login from an incognito window.

Updating copy for the email sent when user logs in from a new location.

---

.github/workflows/ci-tests.yml

removes daily test run
References: CV2-6257
N/A

remove scheduled CI workflow

---

app/models/concerns/project_association.rb

The cached field approach has already updated the value in ES, so I removed the other code to prevent hitting ES twice for the same field.
References: CV2-6314

CV2-6314: remove unneeded code related to sources_count field

---

app/models/concerns/smooch_messages.rb

Move the condition to send a message to the user to the top of the method to prevent Sentry errors.
References: CV2-6331

CV2-6331: NoMethodError: undefined method `[]' for nil:NilClass

---

app/graph/mutations/webhook_mutations.rb
app/models/concerns/smooch_capi.rb

Logging WhatsApp Cloud API requests and responses.
Also, fixing a trailing white space (reported by Code Climate).
Reference: CV2-6356.
Tested locally. I confirmed the log entries in `log/development.log`.

Logging WhatsApp Cloud API requests and responses.

---

app/lib/check_cached_fields.rb

Dedicated esqueue for index/update cached fields
References: CV2-6329

CV2-6329: Dedicated and high-priority queue for cached field jobs

---

app/models/saved_search.rb

Fix list count for channels/users filters .
References: CV2-6018

CV2-6018: fix item_counts for channel and users filter

---

app/controllers/api/v1/graphql_controller.rb
app/graph/types/team_user_type.rb
db/migrate/20250513075639_add_last_active_at_to_team_users.rb
db/schema.rb
lib/relay.idl
public/relay.json
test/controllers/graphql_controller_7_test.rb

Set last_active_date based on team.
References: CV2-6299

CV2-6299: Set last_active_date based on team

---

app/graph/types/project_media_type.rb

Just a quick fix for an error reported by Sentry.
Fixes: CV2-6371.

Account for null texts for tags

---

app/models/annotations/dynamic.rb
app/models/relationship.rb

Fix sentry issues:
- NoMethodError: undefined method `last_verification_status' for nil:NilClass
- NoMethodError: undefined method `id' for nil:NilClass
References: 6380, 6382

CV2-6380-6382 Sentry issues

---

config/tipline_strings.yml

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context, type of change (bug fix, performance, feature, etc.) and things to pay attention to during review.
References: TICKET-ID-1, TICKET-ID-2, …, TICKET-ID-N

remove empty strings to try to fix sentry error

---

.github/workflows/ci-deploy-env.yml

Use the production Dockerfile for image builds. Required for manual deployment into QA.
References: CV2-2955, CV2-6453

Use the production Dockerfile for image builds

---

config/initializers/version.rb

Update version to v0.192.0

---

app/models/bot/alegre.rb

Fix Sentry error by verifying annotation object exists
References: CV2-6492

CV2-6492: Fix sentry issue (NoMethodError: undefined method `annotated' for nil:NilClass)

---

production/Dockerfile

We don't use passenger anymore. Those variables are not used by puma.
So I think we can remove them.
References: CV2-6496

6468 – 6496 – Remove Passenger variables

---

production/Dockerfile

This seems like a leftover from the past.
I don't think we should need this now.
References: CV2-6496

6468 – 6496 – Remove GITREPO ENV

---

production/Dockerfile

This seems to be a leftover from the past and not
used anywhere.
References: CV2-6496

6468 – 6496 – Removes PRODUCT env var from Dockerfile

---

.gitignore
.transifexrc.example
.tx/config
config/locales/ar.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/id.yml
docker-entrypoint.sh

References: CV2-3704
1. Run: docker-compose build
2. Run: docker-compose up
3. Inside the container: docker-compose exec web bash
4. Run: cat ~/.transifexrc → should display token config
5. Run: tx CLI commands

Add Transifex CLI config and update localization files

---

db/migrate/20250917182614_add_index_medias_on_lower_quote.rb
db/schema.rb
test/controllers/registrations_controller_test.rb

Apply index on Claim.quote to enhance query execution time for [setting uuid](https://github.com/meedan/check-api/blob/develop/app/models/claim.rb#L22) 
References: CV2-6562

CV2-6562: Add index on Claim quote

---

docker-compose.yml

Upgrade Postgres to 17. (note: There is no `17-buster` image, so I replaced it with `17-bookworm`.)
References: CV2-6585, CV2-6573
By building and running tests.

Upgrade to Postgres 17
